#!/usr/bin/env python3
# Batch 8: Expanded CA/SoCal local, additional state foundations, construction/real estate,
# additional defense electronics, VEX ecosystem RECF partners, healthcare/biotech CA

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Local Fullerton additions
("Fullerton Chamber of Commerce Foundation","Local","Civic/Business","Fullerton Chamber connects local businesses with community programs; STEM and workforce pipeline for local youth","Chamber Education Grants","$500-$5,000","Annual","https://www.fullertonchamber.com","https://www.fullertonchamber.com/","Local business network; education and workforce; direct Fullerton CA connection","MEDIUM"),
("Rotary Club of West Fullerton","Local","Civic/Club","West Fullerton Rotary Club funds local community and youth programs; STEM adjacent through community service","Club Community Grants","$500-$3,000","Rolling - contact club","https://www.fullertonchamber.com","https://www.fullertonchamber.com/","Local Fullerton Rotary chapter; youth programs; ask to present at a meeting; small accessible grants","MEDIUM"),
("Fullerton Lions Club","Local","Civic/Club","Lions Club of Fullerton funds vision health and youth programs; youth leadership focus","Youth and Community Grants","$500-$3,000","Rolling - contact club","https://www.lionsclubs.org","https://www.lionsclubs.org/en/find-a-club","Local Fullerton Lions chapter; youth programs; easy access through local chapter meeting presentation","MEDIUM"),
("SchoolsFirst Federal Credit Union Foundation","Local","Financial (Credit Union)","SchoolsFirst FCU exclusively serves school employees in CA; funds education programs for school staff and students","Education Grants for Schools","$1,000-$10,000","Annual","https://www.schoolsfirstfcu.org","https://www.schoolsfirstfcu.org/about-us/community/donations","Serves Fullerton school employees; education programs; Troy High School staff can apply","GOOD"),
("Wescom Credit Union Foundation","Local","Financial (Credit Union)","Wescom serves Los Angeles and OC; community education grants; employee matching for CA schools","Community Education Grants","$1,000-$10,000","Annual","https://www.wescom.org","https://www.wescom.org/AboutWescom/Community","OC and LA service area; community education grants; Fullerton CA branch presence","MEDIUM"),
("Pacific Premier Bancorp Foundation (Irvine)","Local","Financial (Banking)","Pacific Premier Bank HQ in Irvine OC; community grants for education and workforce in OC","OC Community Education Grants","$1,000-$25,000","Annual","https://www.ppbi.com","https://www.ppbi.com/community/charitable-giving","Irvine OC HQ; community education in OC; Fullerton area branch network","MEDIUM"),
("CSUF Engineering Foundation","Local","Educational Partnership","Cal State Fullerton Engineering Department offers industry partnership and grants; direct university-school pipeline","University-Industry STEM Partnership","$1,000-$25,000","Annual","https://engineering.fullerton.edu","https://engineering.fullerton.edu/about/","Cal State Fullerton is walking distance from Troy High; STEM pipeline from HS to CSUF engineering","GOOD"),
("CSUF Titan STEM Partnership","Local","Educational Partnership","CSUF Titan STEM Center works with K-12 schools in Fullerton; direct school partnership grants","K-12 STEM Partnership Grants","$1,000-$10,000","Annual","https://cstem.fullerton.edu","https://cstem.fullerton.edu/","CSUF STEM center near Troy High; direct K-12 partnership; robotics and engineering education","GOOD"),
("Hanmi Financial Foundation (OC)","Local","Financial (Banking)","Hanmi Bank serves Korean-American community in OC and LA; funds education and community programs","Education and Community Grants","$1,000-$10,000","Annual","https://www.hanmi.com","https://www.hanmi.com/about-hanmi/community","Korean-American bank; OC and LA service area; community education programs","MEDIUM"),
("Cathay General Bancorp Foundation","Local","Financial (Banking)","Cathay Bank serves Asian-American community in OC and LA; funds education and community programs","Education and Community Grants","$1,000-$10,000","Annual","https://www.cathaybank.com","https://www.cathaybank.com/about-us/corporate-responsibility","Asian-American bank; OC community education; Fullerton area branch presence","MEDIUM"),
# SoCal/Regional expanded
("Fluor Corporation Irvine - Community Grants","Regional","Corporate (Engineering)","Fluor OC HQ in Irvine; local community grants specifically for OC education and STEM programs; engineering firm","OC Community STEM Grants","$5,000-$50,000","Annual","https://www.fluor.com","https://www.fluor.com/about/corporate-responsibility/fluor-foundation","OC HQ in Irvine; community grants for OC STEM; direct local tie to Fullerton area","GOOD"),
("Irvine Company Foundation","Regional","Corporate (Real Estate)","Major OC real estate developer; funds education and community in OC; STEM and arts programs","OC Education and Community Grants","$5,000-$50,000","Annual","https://www.irvinecompany.com","https://www.irvinecompany.com/company/irvine-company-foundation","Largest OC real estate developer; OC community education; Fullerton adjacent market","MEDIUM"),
("Edwards Lifesciences (Irvine) Community Grants","Regional","Corporate (Healthcare)","Edwards Lifesciences OC HQ; community investment grants for OC education and healthcare STEM","OC STEM Healthcare Education","$5,000-$50,000","Annual","https://www.edwards.com","https://www.edwards.com/gb/about-us/sustainability","Irvine OC HQ; OC community grants; STEM healthcare education; direct local tie","GOOD"),
("Kforce Foundation (SoCal)","Regional","Corporate (Staffing/Technology)","Kforce technology staffing firm; funds education and STEM workforce programs; SoCal presence","STEM Workforce Education","$1,000-$25,000","Annual","https://www.kforce.com","https://www.kforce.com/about/","Technology staffing; STEM workforce pipeline; SoCal offices; potential robotics career pathway partner","MEDIUM"),
("Panasonic North America (SoCal)","Regional","Corporate (Technology)","Panasonic NA office in Newark CA; funds STEM education and technology programs in SoCal","STEM Technology Education","$5,000-$50,000","Annual","https://www.panasonic.com","https://www.panasonic.com/us/consumer/sustainability.html","Japan-based electronics company with SoCal operations; STEM technology education; manufacturing focus","MEDIUM"),
("KYOCERA America Foundation (San Diego)","Regional","Corporate (Technology)","KYOCERA America HQ in San Diego; Japanese electronics/industrial ceramics; funds STEM education in SoCal","STEM Technology Education","$5,000-$50,000","Annual","https://www.kyocera.com","https://www.kyocera.com/csr/","San Diego CA HQ; STEM education in SoCal; electronics and advanced ceramics manufacturing","MEDIUM"),
("Samsung Semiconductor (San Jose / SoCal)","State","Corporate (Technology/Semiconductor)","Samsung Semiconductor HQ in San Jose CA; funds STEM education and innovation programs; Korean-American community focus","STEM Innovation Education","$10,000-$100,000","Annual","https://semiconductor.samsung.com","https://semiconductor.samsung.com/us/about-us/","San Jose CA HQ; STEM education; Korean-American community focus; Fullerton area Korean community connection","GOOD"),
("LG Electronics USA Foundation","State","Corporate (Technology)","LG Electronics North America; funds STEM education and innovation programs; Korean-American company","STEM and Innovation Education","$5,000-$50,000","Annual","https://www.lg.com","https://www.lg.com/us/social-responsibility","Korean electronics giant; STEM education; national programs with SoCal offices","MEDIUM"),
("HealthNet Foundation (Woodland Hills CA)","State","Corporate (Healthcare)","Health Net (WellPoint subsidiary) serves CA; community health grants for CA nonprofits and schools","CA Community Health and Education","$5,000-$50,000","Annual","https://www.healthnet.com","https://www.healthnet.com/portal/about-us/social-responsibility.action","CA health insurance; community health and education grants for CA; Woodland Hills CA HQ","MEDIUM"),
("In-N-Out Burger Foundation (Irvine CA)","State","Corporate (Food)","In-N-Out Burger is privately held with Irvine CA HQ; funds youth and community programs in CA; highly local","Youth and Community Grants CA","$1,000-$10,000","Annual","https://www.in-n-out.com","https://www.in-n-out.com/company/charitable.aspx","Irvine CA HQ private company; funds youth programs in CA; Fullerton area has multiple locations","GOOD"),
("The Wonderful Company Foundation (Fresno/LA)","State","Corporate (Agriculture)","Owner of FIJI Water, Wonderful Pistachios, Teleflora; funds STEM education in CA particularly Central Valley","STEM Education CA Grants","$5,000-$100,000","Annual","https://www.wonderfulcompany.com","https://www.wonderfulcompany.com/giving-back/","CA-based private food company; STEM education in CA; Wonderful STEM Education program","GOOD"),
("Amgen Foundation Thousand Oaks 2","State","Corporate (Biotech)","Additional Amgen grants specifically for local Thousand Oaks and Ventura County area schools","Local Area STEM Grants","$5,000-$50,000","Annual","https://www.amgen.com","https://www.amgen.com/responsibility/amgen-foundation","Thousand Oaks CA (40 miles from Fullerton); local area STEM grants; biotech career pipeline","GOOD"),
("CHOC Children's Foundation (OC)","Local","Foundation (Healthcare)","Children's Hospital of Orange County; CHOC Foundation funds youth health and STEM programs in OC","OC Youth Health and Education","$5,000-$50,000","Annual","https://www.choc.org","https://www.choc.org/foundation/","Orange County children's hospital; youth health and STEM programs; direct OC connection","MEDIUM"),
("UCI Foundation (UC Irvine)","Local","Foundation (University)","UC Irvine Foundation funds STEM education partnerships with K-12 schools in OC","OC K-12 STEM Partnerships","$5,000-$25,000","Annual","https://www.uci.edu","https://www.uci.edu/giving/","UC Irvine is major OC university; K-12 STEM partnerships; direct local connection to TroyVEX","GOOD"),
# Construction / Real Estate with STEM
("Lennar Foundation","National","Corporate (Real Estate)","Lennar Corporation (Miami FL) builds homes nationally including CA; funds education near communities","Community Education Grants","$5,000-$50,000","Annual","https://www.lennar.com","https://www.lennar.com/about-lennar/community","National homebuilder with CA operations; community education grants near developments","MEDIUM"),
("KB Home Foundation","State","Corporate (Real Estate)","KB Home HQ in Los Angeles CA; major California homebuilder; funds education and community programs in CA","CA Community Education Grants","$5,000-$50,000","Annual","https://www.kbhome.com","https://www.kbhome.com/community","Los Angeles CA HQ; California homebuilder; community education programs in CA","MEDIUM"),
("PulteGroup Foundation","National","Corporate (Real Estate)","PulteGroup funds education and veteran programs; builds homes for military families through Built to Honor","Education and Veterans Grants","$5,000-$100,000","Annual","https://www.pultegroup.com","https://www.pultegroup.com/news-media/press-releases/","Veteran housing and education; Built to Honor military families; JROTC affiliation connects to veteran families","GOOD"),
("AECOM Foundation (Los Angeles)","Regional","Corporate (Engineering)","AECOM global engineering firm HQ in LA; funds STEM education and engineering career programs","STEM Engineering Education","$10,000-$250,000","Annual","https://www.aecom.com","https://aecom.com/about-aecom/citizenship/","LA HQ engineering firm; STEM engineering education; large OC operations; 10 miles from Fullerton","GOOD"),
("Jacobs Engineering Foundation","National","Corporate (Engineering)","Jacobs funds STEM education and engineering programs; global engineering and construction firm","STEM Engineering Grants","$5,000-$100,000","Annual","https://www.jacobs.com","https://www.jacobs.com/societal-impact","Engineering firm; STEM education; Dallas TX HQ with major CA operations","GOOD"),
("Black and Veatch Foundation","National","Corporate (Engineering)","Black and Veatch funds STEM education and engineering workforce; water and energy infrastructure","STEM Engineering Workforce","$5,000-$50,000","Annual","https://www.bv.com","https://www.bv.com/social-responsibility","Infrastructure engineering; STEM education; Overland Park KS HQ with national programs","MEDIUM"),
("Parsons Corporation Foundation","National","Corporate (Engineering)","Parsons Corporation (defense/infrastructure) funds STEM education; Centreville VA HQ; defense adjacent","STEM Defense Engineering","$5,000-$100,000","Annual","https://www.parsons.com","https://www.parsons.com/social-responsibility/","Defense and infrastructure engineering; STEM education; defense adjacent aligns with JROTC","GOOD"),
("Bechtel Foundation","National","Corporate (Engineering)","Bechtel Corporation funds STEM education and engineering; global construction and engineering firm","STEM Engineering Education","$10,000-$250,000","Annual","https://www.bechtel.com","https://www.bechtel.com/sustainability/social-impact/","Global engineering firm; STEM education; San Francisco CA HQ; major infrastructure projects","GOOD"),
# Additional VEX/RECF ecosystem partners
("Innovation First International (VEX parent)","National","Corporate (Technology/Robotics)","Innovation First International makes VEX Robotics hardware; direct manufacturer of TroyVEX robots; equipment grants","VEX Team Equipment Grants","Equipment kits at cost/free","Rolling - through RECF","https://www.vexrobotics.com","https://www.vexrobotics.com/","Direct manufacturer of VEX robots; contact for equipment discounts and team grants; APPLY FIRST","GOOD"),
("Robomatter / Carnegie Learning VEX","National","Corporate (Education Technology)","Robomatter provides VEX coding curriculum; CS2N platform for VEX programming education","VEX Coding Curriculum / CS2N","In-kind - free curriculum","Rolling","https://www.cs2n.org","https://www.cs2n.org/","VEX coding curriculum partner; free educational resources; APPLY NOW for curriculum access","GOOD"),
("HEXBUG (Innovation First)","National","Corporate (Technology/Robotics)","HEXBUG/Innovation First makes VEX IQ and robotics kits; team equipment and competition support","VEX IQ Equipment Support","Equipment grants","Annual through RECF","https://www.hexbug.com","https://www.hexbug.com/","VEX IQ equipment maker; team equipment support; pipeline to younger STEM students","GOOD"),
("Avatech Solutions (3D Printing/CAD)","National","Corporate (Technology)","Avatech (Autodesk partner) provides CAD and 3D printing education tools for teams","CAD and 3D Print Education","In-kind/discount","Rolling","https://www.avatech.com","https://www.avatech.com/education","Autodesk authorized reseller; CAD education tools for robotics design; free Autodesk student licenses","GOOD"),
("VEX Worlds Official Hotel Partners","National","Corporate (Hospitality)","Official VEX World Championship hotel partners offer discounted team rates; connect for travel support","Team Travel Support","Discounted rates","Annual","https://www.vexrobotics.com/vex-worlds","https://www.vexrobotics.com/vex-worlds","Official VEX Worlds partners; discounted team travel accommodation; cost reduction for competition travel","MEDIUM"),
# Additional pharma/biotech CA
("Allergan Foundation (Irvine CA) 2","Local","Corporate (Healthcare)","AbbVie/Allergan has major Irvine OC presence; additional local community grants beyond national programs","OC Community Grants","$5,000-$25,000","Annual","https://www.allergan.com","https://www.allergan.com/en/corporate-responsibility","Irvine OC major employer; local community grants; OC STEM education focus","GOOD"),
("Beckman Coulter Foundation (Brea CA)","Local","Corporate (Healthcare/Technology)","Beckman Coulter laboratory instruments HQ in Brea CA (adjacent to Fullerton); funds STEM education in OC","OC STEM Laboratory Education","$5,000-$50,000","Annual","https://www.beckmancoulter.com","https://www.beckmancoulter.com/en/about-us/our-company/corporate-citizenship","Brea CA HQ - walking distance from Fullerton; laboratory instruments; OC STEM education; HIGH PRIORITY local","GOOD"),
("St. Jude Medical Foundation (Sylmar CA)","Regional","Corporate (Healthcare)","Abbott/St. Jude Medical has Sylmar CA facility; medical devices; SoCal community grants","SoCal Community STEM Grants","$5,000-$50,000","Annual","https://www.sjm.com","https://www.abbott.com/responsibility/foundation.html","Sylmar CA (near Fullerton); medical device manufacturing; SoCal community grants; healthcare STEM","GOOD"),
# Financial / Banking local and regional
("First Foundation Bank (Irvine CA)","Local","Financial (Banking)","First Foundation Bank HQ in Irvine OC; community grants for OC education and nonprofits","OC Community Education Grants","$1,000-$25,000","Annual","https://www.firstfoundationinc.com","https://www.firstfoundationinc.com/community/","Irvine OC HQ; community education in OC; Fullerton area branch presence","MEDIUM"),
("Pacific City Financial (Los Angeles/OC)","Local","Financial (Banking)","Pacific City Bank serves OC and LA Korean-American community; funds education and community","Education and Community Grants","$1,000-$10,000","Annual","https://www.pcbcorp.com","https://www.pcbcorp.com/community/","Korean-American bank; OC and LA; community education programs; Fullerton area connection","MEDIUM"),
("Bank of the West (Fullerton)","Local","Financial (Banking)","Bank of the West (now BMO Harris) has Fullerton CA branch; local community education grants","Local Community Education Grants","$1,000-$10,000","Annual","https://www.bankofthewest.com","https://www.bankofthewest.com/","Fullerton branch bank; local community education; contact branch manager for local grants","MEDIUM"),
("Golden 1 Credit Union Foundation (CA)","State","Financial (Credit Union)","Golden 1 Credit Union (California's largest CU) funds education for CA students and communities","CA Education and Community","$1,000-$25,000","Annual","https://www.golden1.com","https://www.golden1.com/content/golden_1/en_us/about-us/community-commitment.html","California's largest CU; statewide education funding; CA students directly eligible","GOOD"),
# More engineering/industrial
("Emerson Electric STEM (Additional programs)","National","Corporate (Manufacturing)","Emerson Electric has multiple STEM education programs; automation and process control technology","Automation STEM Education","$10,000-$100,000","Annual","https://www.emerson.com","https://www.emerson.com/en-us/sustainability/","Automation and process control technology; STEM education directly relevant to robotics controls","GOOD"),
("ABB Robotics Foundation","National","Corporate (Robotics/Industrial)","ABB is one of world's largest robotics companies; funds STEM education and robotics programs; direct robotics industry","Robotics and STEM Education","$10,000-$100,000","Annual","https://www.abb.com","https://www.abb.com/en/sustainability/social-impact","Major robotics company; STEM education directly in robotics industry; Swiss HQ with US operations","GOOD"),
("FANUC America Foundation","National","Corporate (Robotics/Industrial)","FANUC makes industrial robots and CNC; direct robotics industry; funds STEM education programs","Robotics STEM Education","$5,000-$50,000","Annual","https://www.fanucamerica.com","https://www.fanucamerica.com/home/about/sustainability","Major industrial robot manufacturer; STEM education directly in robotics industry; Rochester Hills MI HQ","GOOD"),
("Universal Robots Foundation (Teradyne)","National","Corporate (Robotics)","Universal Robots makes collaborative robots; direct robotics industry; educational programs and grants","Collaborative Robotics Education","$5,000-$50,000","Annual","https://www.universal-robots.com","https://www.universal-robots.com/about-universal-robots/social-responsibility/","Collaborative robotics manufacturer; STEM education in robotics; Danish company with US HQ in Ann Arbor MI","GOOD"),
("Yaskawa America Foundation","National","Corporate (Robotics/Industrial)","Yaskawa makes industrial robots and servo motors; direct robotics industry; STEM education programs","Robotics and Motion STEM","$5,000-$50,000","Annual","https://www.yaskawa.com","https://www.yaskawa.com/en/sustainability/","Industrial robots and motion control; direct robotics industry; STEM education; Waukesha WI HQ","GOOD"),
("Kuka Robotics Foundation","National","Corporate (Robotics)","KUKA makes industrial robots; one of world's largest robot manufacturers; STEM education programs","Industrial Robotics STEM","$5,000-$50,000","Annual","https://www.kuka.com","https://www.kuka.com/en-us/company/sustainability","Major robot manufacturer; STEM education for robotics; German company with US operations","GOOD"),
("Boston Dynamics Education","National","Corporate (Robotics)","Boston Dynamics makes advanced robots (Spot, Atlas); STEM education and robotics programs","Advanced Robotics STEM","$5,000-$50,000","Annual","https://www.bostondynamics.com","https://www.bostondynamics.com/about","Advanced robotics pioneer; STEM education; Waltham MA HQ; extremely relevant to VEX robotics","GOOD"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 8 complete: {len(ENTRIES)} new entries appended")
