import csv, os

output_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'troyvex_donor_list.csv')

entries = [
    # ---- NATIONAL CORPORATE - INDUSTRIAL / MANUFACTURING ADDITIONAL ----
    ("Parker Hannifin Foundation","National","Corporate Foundation (Industrial)","Parker Hannifin (motion/control tech) is a robotics-adjacent industrial company","STEM / Engineering Education","$10,000-$100,000","Annual","https://www.parker.com","https://www.parker.com/us/en/community-relations.html","Motion and control technology; robotics-adjacent; Cleveland OH HQ; STEM engineering education","GOOD"),
    ("Eaton Corporation Foundation","National","Corporate Foundation (Industrial)","Eaton (power management) supports STEM education and workforce","STEM / Workforce Education","$10,000-$100,000","Annual","https://www.eaton.com/us/en-us/company/corporate-responsibility.html","https://www.eaton.com/us/en-us/company/corporate-responsibility/community-relations.html","Power management/electrical; STEM education; Dublin Ireland/Dublin OH HQ; accessible programs","MEDIUM"),
    ("Illinois Tool Works (ITW) Foundation","National","Corporate Foundation (Industrial)","ITW (diversified manufacturing) funds education and community","Education Grants","$5,000-$50,000","Annual","https://www.itw.com","https://www.itw.com/social-responsibility","Diversified manufacturer; STEM education; Glenview IL HQ; accessible school programs","MEDIUM"),
    ("Roper Technologies Foundation","National","Corporate Foundation (Industrial Technology)","Roper Technologies (measurement/analytics instruments) STEM programs","STEM / Technology Education","$5,000-$50,000","Annual","https://www.ropertech.com","https://www.ropertech.com/social-responsibility","Industrial tech; measurement instruments; STEM education; Sarasota FL HQ; accessible","MEDIUM"),
    ("AMETEK Foundation","National","Corporate Foundation (Electronic Instruments)","AMETEK (electronic instruments/electromechanical) STEM education","STEM / Engineering Education","$5,000-$25,000","Annual","https://www.ametek.com","https://www.ametek.com/about-ametek/corporate-responsibility","Electronic instruments; electromechanical devices (motors for robotics); STEM education focus","GOOD"),
    ("Watts Water Technologies Foundation","National","Corporate Foundation (Industrial)","Watts Water (flow control systems) supports STEM and community","STEM / Engineering Education","$5,000-$25,000","Annual","https://www.watts.com","https://www.watts.com/about/corporate-responsibility","Flow control and water systems; STEM engineering; North Andover MA HQ; accessible programs","MEDIUM"),
    ("Rexnord Foundation","National","Corporate Foundation (Industrial)","Rexnord (process/motion control) supports STEM and manufacturing education","STEM / Manufacturing Education","$5,000-$25,000","Annual","https://www.rexnord.com","https://www.rexnord.com/community","Process and motion control; manufacturing STEM; Milwaukee WI; accessible programs","MEDIUM"),
    ("Hubbell Foundation","National","Corporate Foundation (Electrical)","Hubbell (electrical products) supports STEM and community","STEM / Electrical Engineering Education","$5,000-$25,000","Annual","https://www.hubbell.com","https://www.hubbell.com/hubbell/en/sustainability","Electrical products; STEM education; Shelton CT HQ; engineering education focus","MEDIUM"),
    ("Watts Foundation (Harold and Mimi Steinberg)","National","Private Foundation","Steinberg Charitable Trust for theater and arts education","Arts / Theater Education","$25,000-$200,000","Annual (invitation)","https://www.steinbergcharitabletrust.org","https://www.steinbergcharitabletrust.org","Theater/arts focus; not robotics-relevant; invitation-only; wrong fit for VEX program","BAD"),
    ("Olin Foundation","National","Private Foundation (Manufacturing)","Franklin W. Olin Foundation focused on engineering education","Engineering Education","$100,000-$1,000,000","Annual (invitation)","https://www.franklinfoundation.org","https://www.franklinfoundation.org","Engineering education; Olin College affiliated; primarily invitation-based; large grants","MEDIUM"),

    # ---- NATIONAL CORPORATE - TECHNOLOGY SERVICES / SOFTWARE ADDITIONAL ----
    ("Salesforce Foundation","National","Corporate Foundation (SaaS/CRM)","Salesforce.org (1-1-1 model) funds STEM education and nonprofits","Salesforce.org Grants / STEM","$10,000-$100,000","Annual","https://www.salesforce.org","https://www.salesforce.org/resources/grants/","1% of product/equity/time to charity; STEM education; SF CA HQ; accessible school programs","GOOD"),
    ("ServiceNow Foundation","National","Corporate Foundation (Enterprise Software)","ServiceNow (workflow automation) supports digital skills and STEM","RiseUp / Digital Skills Education","$10,000-$100,000","Annual","https://www.servicenow.com/company/social-responsibility.html","https://www.servicenow.com/company/social-responsibility.html","Enterprise software; digital skills + STEM; Santa Clara CA HQ; accessible programs","MEDIUM"),
    ("Workday Foundation","National","Corporate Foundation (HR Software)","Workday (HCM software) foundation supports education and workforce","Education / Workforce Grants","$10,000-$100,000","Annual","https://www.workday.com/en-us/company/social-responsibility.html","https://www.workday.com/en-us/company/social-responsibility/workday-foundation.html","HR software company; education + workforce; Pleasanton CA HQ; accessible programs","MEDIUM"),
    ("Zoom Foundation","National","Corporate Foundation (Video Conferencing)","Zoom (video communication) funds education and community","Education / Digital Equity Grants","$10,000-$100,000","Annual","https://zoom.us/en/trust/social-impact/","https://zoom.us/en/trust/social-impact/","Video communication; education + digital equity; San Jose CA HQ; COVID-era education grants","MEDIUM"),
    ("Dropbox Foundation","National","Corporate Foundation (Cloud Storage)","Dropbox supports digital literacy and underrepresented communities","Digital Literacy / STEM Inclusion","$10,000-$50,000","Annual","https://blog.dropbox.com/company/responsibility","https://blog.dropbox.com/company/responsibility","Cloud storage; STEM inclusion; San Francisco CA HQ; accessible programs; underrepresented youth","MEDIUM"),
    ("Twilio.org","National","Corporate Foundation (Cloud Communications)","Twilio.org (1% social impact model) funds nonprofits with tech","Social Impact Technology Grants","$10,000-$100,000","Annual","https://www.twilio.org","https://www.twilio.org/social-impact/grant-program","Cloud communications; tech grants for nonprofits; San Francisco CA; accessible programs","MEDIUM"),
    ("Autodesk Foundation","National","Corporate Foundation (Design Software)","Autodesk Foundation funds design-powered social change","Design for Innovation Grants","$25,000-$500,000","Annual","https://www.autodesk.org","https://www.autodesk.org/grantee-stories","CAD/3D design software; design for good; San Francisco CA; STEM design education; accessible","GOOD"),
    ("Adobe Foundation","National","Corporate Foundation (Creative Software)","Adobe Foundation focuses on creativity and digital literacy","Creativity / Digital Literacy Grants","$10,000-$100,000","Annual","https://www.adobe.com/corporate-responsibility.html","https://www.adobe.com/corporate-responsibility/community.html","Creative software; digital literacy; San Jose CA HQ; accessible education programs","MEDIUM"),
    ("Zendesk Neighbor Foundation","National","Corporate Foundation (Customer Service Software)","Zendesk funds community and education in its locations","Community / Education Grants","$5,000-$50,000","Annual","https://www.zendesk.com/company/social-impact/","https://www.zendesk.com/company/social-impact/","Customer service software; community grants; SF CA HQ; accessible programs; STEM-adjacent","MEDIUM"),
    ("Splunk Foundation","National","Corporate Foundation (Data/Security)","Splunk (Cisco subsidiary) funds data literacy and STEM education","Data Literacy / STEM Grants","$10,000-$50,000","Annual","https://www.splunk.com/en_us/about-splunk/social-responsibility.html","https://www.splunk.com/en_us/about-splunk/social-responsibility.html","Data analytics/security; STEM literacy; San Francisco CA; now Cisco subsidiary; accessible","MEDIUM"),

    # ---- NATIONAL - ADDITIONAL AEROSPACE/DEFENSE ----
    ("Collins Aerospace Foundation","National","Corporate Foundation (Aerospace)","Collins Aerospace (RTX subsidiary) funds STEM and community","STEM / Aerospace Education","$10,000-$100,000","Annual","https://www.collinsaerospace.com","https://www.collinsaerospace.com/en/who-we-are/corporate-responsibility","RTX division; aerospace + defense; Cedar Rapids IA HQ; major STEM funder; strong fit","GOOD"),
    ("Spirit AeroSystems Foundation","National","Corporate Foundation (Aerospace Manufacturing)","Spirit AeroSystems (Boeing fuselages) has STEM education programs","STEM / Aerospace Manufacturing Education","$10,000-$50,000","Annual","https://www.spiritaero.com","https://www.spiritaero.com/citizenship/","Aerospace manufacturing; STEM education; Wichita KS HQ; accessible for school programs","GOOD"),
    ("Leonardo DRS Foundation","National","Corporate Foundation (Defense Electronics)","Leonardo DRS (defense electronics) supports STEM and veteran programs","STEM / Military Support Grants","$5,000-$50,000","Annual","https://www.leonardodrs.com","https://www.leonardodrs.com/about/corporate-responsibility/","Defense electronics; STEM education; Arlington VA HQ; military community + NJROTC relevant","GOOD"),
    ("Curtiss-Wright Foundation","National","Corporate Foundation (Defense/Industrial)","Curtiss-Wright (defense electronics) STEM and engineering education","STEM / Engineering Education","$5,000-$25,000","Annual","https://www.curtisswright.com","https://www.curtisswright.com/about-us/corporate-responsibility","Defense electronics and motion control; STEM education; Davidson NC HQ; accessible programs","MEDIUM"),
    ("DXC Technology Foundation","National","Corporate Foundation (IT Services)","DXC Technology (defense/government IT services) STEM education","STEM / IT Education Grants","$10,000-$100,000","Annual","https://www.dxc.com","https://www.dxc.com/us/en/about-us/corporate-responsibility","Defense/government IT; STEM education; Tysons VA HQ; accessible school programs","MEDIUM"),
    ("Parsons Corporation Foundation","National","Corporate Foundation (Defense/Engineering)","Parsons Corp (defense/infrastructure engineering) STEM programs","STEM / Engineering Education","$10,000-$100,000","Annual","https://www.parsons.com","https://www.parsons.com/sustainability/","Defense and infrastructure engineering; STEM education; Centreville VA HQ; accessible","GOOD"),
    ("Cubic Corporation Foundation","National","Corporate Foundation (Defense/Transportation)","Cubic (defense and transportation) STEM education and community","STEM / Defense Technology Education","$5,000-$50,000","Annual","https://www.cubic.com","https://www.cubic.com/about/corporate-citizenship","Defense + transportation systems; STEM education; San Diego CA HQ; CA-based; accessible","GOOD"),

    # ---- NATIONAL - ADDITIONAL STEM / EDUCATION ORGANIZATIONS ----
    ("MATHCOUNTS Foundation","National","STEM Organization (Math)","MATHCOUNTS runs national math competitions for middle schoolers","Math Competition / STEM Outreach","$1,000-$10,000","Annual","https://www.mathcounts.org","https://www.mathcounts.org/programs/mathcounts-foundation","Math competitions; STEM ecosystem; VEX ecosystem overlap; accessible for programs; good networking","MEDIUM"),
    ("American Chemical Society Foundation","National","Professional Society Foundation","ACS funds chemistry education and STEM outreach programs","ChemClub / STEM Education Grants","$2,500-$25,000","Annual","https://www.acs.org/education/students/highschool/chemiclub.html","https://www.acs.org/funding.html","Chemistry STEM; ACS high school programs; ChemClub grants; STEM overlap with robotics","MEDIUM"),
    ("American Physical Society Foundation","National","Professional Society Foundation","APS funds physics education and STEM outreach","Physics Education Grants","$5,000-$25,000","Annual","https://www.aps.org/programs/outreach/","https://www.aps.org/programs/outreach/","Physics education; STEM foundation for robotics; APS outreach grants; accessible programs","MEDIUM"),
    ("Society of Women Engineers (SWE) Foundation","National","Professional Society Foundation","SWE funds scholarships and outreach for women in engineering","Scholarships / Outreach Grants","$5,000-$25,000","Annual","https://www.swe.org","https://www.swe.org/scholarships/","Women in engineering; STEM diversity; Troy HS students eligible for scholarships; outreach grants","GOOD"),
    ("National Society of Black Engineers (NSBE) Foundation","National","Professional Society Foundation","NSBE supports Black engineering students; outreach and scholarships","Scholarships / Outreach Grants","$5,000-$50,000","Annual","https://www.nsbe.org","https://www.nsbe.org/programs/scholarships/","Black engineering community; STEM diversity; accessible scholarships; robotics-adjacent","GOOD"),
    ("Society of Hispanic Professional Engineers (SHPE) Foundation","National","Professional Society Foundation","SHPE supports Hispanic engineering students; scholarships and outreach","Scholarships / STEM Outreach","$5,000-$25,000","Annual","https://shpe.org","https://shpe.org/community/scholarships/","Hispanic engineering community; STEM diversity; accessible scholarships; robotics-adjacent","GOOD"),
    ("National Action Council for Minorities in Engineering (NACME)","National","STEM Diversity Organization","NACME funds engineering education for underrepresented minorities","Engineering Scholarships / Block Grants","$25,000-$100,000","Annual","https://www.nacme.org","https://www.nacme.org/scholarships","Minority engineering education; STEM diversity; block grants to schools; accessible programs","GOOD"),
    ("Project Lead The Way (PLTW) Foundation","National","STEM Curriculum Organization","PLTW provides engineering and CS curriculum to K-12 schools","Curriculum / Program Support Grants","$10,000-$100,000","Annual","https://www.pltw.org","https://www.pltw.org/grants","Engineering curriculum provider; STEM education; accessible grants for school programs","GOOD"),
    ("TeachSTEM Foundation","National","STEM Education Nonprofit","TeachSTEM funds hands-on STEM experiences for K-12 students","Hands-On STEM Grants","$2,500-$25,000","Annual","https://www.teachstem.org","https://www.teachstem.org/grants","Hands-on STEM; robotics-adjacent; accessible school grants; education-focused nonprofit","GOOD"),
    ("Digital Promise","National","STEM Education Nonprofit","Digital Promise funds innovative education technology and STEM programs","Education Innovation / Maker Grants","$10,000-$100,000","Annual","https://digitalpromise.org","https://digitalpromise.org/grants/","Education technology innovation; maker/STEM; DC-based; accessible school programs","MEDIUM"),

    # ---- NATIONAL - ADDITIONAL MILITARY/VETERAN ORGANIZATIONS ----
    ("American Legion Foundation","National","Military Organization Foundation","American Legion auxiliary education and scholarship programs","Legion Scholarship / Education Grants","$5,000-$50,000","Annual","https://www.legion.org","https://www.legion.org/scholarship","Largest veteran organization; JROTC-relevant; education scholarships; accessible programs","GOOD"),
    ("VFW (Veterans of Foreign Wars) Foundation","National","Military Organization Foundation","VFW funds STEM, patriotism, and youth education programs","Voice of Democracy / STEM Outreach","$5,000-$25,000","Annual","https://www.vfw.org","https://www.vfw.org/community/youth-and-education","Veteran organization; youth + patriotism + STEM; NJROTC-adjacent; accessible programs","GOOD"),
    ("AMVETS (American Veterans) Foundation","National","Military Organization Foundation","AMVETS supports veterans and STEM/youth education","Scholarship / Youth Programs","$1,000-$10,000","Annual","https://amvets.org","https://amvets.org/scholarships/","Veteran support + youth education; NJROTC-adjacent; accessible scholarship programs","GOOD"),
    ("Disabled American Veterans Charitable Service Trust","National","Military Organization Foundation","DAV Charitable Service Trust funds programs for disabled veterans","Veteran Services / Education","$10,000-$100,000","Annual","https://www.dav.org","https://www.dav.org/charitable-service-trust/","Disabled veteran support; not directly robotics-relevant; military community adjacent","MEDIUM"),
    ("Military Officers Association of America (MOAA) Foundation","National","Military Officer Association","MOAA funds scholarships and education for military-affiliated students","MOAA Scholarships","$5,000-$25,000","Annual","https://www.moaa.org","https://www.moaa.org/content/find-career-and-education-resources/scholarships-and-grants/","Officer association; education scholarships; NJROTC graduates may be eligible; military focus","GOOD"),
    ("Chief Petty Officers Scholarship Fund","National","Military Scholarship","CPO Scholarship Fund for Navy CPO dependents and ROTC students","CPO Scholarships","$2,000-$5,000","Annual","https://www.cpos.org","https://www.cpos.org/scholarship-program","Navy CPO community; NJROTC cadets may be eligible; Navy-focused scholarship fund","GOOD"),
    ("Fleet Reserve Association Education Foundation","National","Military Foundation","FRA (Navy/Marine/Coast Guard) funds education for members and families","FRA Scholarships","$5,000-$30,000","Annual","https://www.fra.org","https://www.fra.org/desktopmodules/FRA/content/foundation","Navy/Marine/Coast Guard focus; NJROTC directly relevant; education scholarships; accessible","GOOD"),
    ("Marine Corps Scholarship Foundation","National","Military Scholarship Foundation","Marine Corps Scholarship Foundation for children of Marines","Marine Corps Scholarships","$3,000-$10,000","Annual","https://www.mcsf.org","https://www.mcsf.org/scholarships/apply-for-scholarship/","Marine Corps families eligible; NJROTC-adjacent; education scholarships; accessible","GOOD"),

    # ---- NATIONAL - ADDITIONAL CIVIC/COMMUNITY ORGANIZATIONS ----
    ("Elks National Foundation","National","Civic Organization","Elks (BPOE) funds scholarships and youth programs nationally","Most Valuable Student Scholarships","$4,000-$50,000","Annual","https://www.elks.org/enf/","https://www.elks.org/enf/scholars/mvs.cfm","Large civic org; Most Valuable Student scholarship; accessible for high school seniors; national program","GOOD"),
    ("Rotary Foundation","National","Civic Organization Foundation","Rotary International funds education and community through local clubs","District Grants / Vocational Training Teams","$5,000-$50,000","Annual","https://www.rotary.org/en/our-programs/grants","https://www.rotary.org/en/our-programs/grants","Many OC Rotary clubs; local club grants accessible; education + youth focus; strong local option","GOOD"),
    ("Kiwanis International Foundation","National","Civic Organization Foundation","Kiwanis funds youth development and education programs","Youth Programs / Education Grants","$5,000-$25,000","Annual","https://www.kiwanis.org","https://www.kiwanis.org/resources-for-clubs/club-and-division-resources/grants/","Youth development; education focus; many OC clubs; Key Club connection; accessible programs","GOOD"),
    ("Optimist International Foundation","National","Civic Organization Foundation","Optimist funds youth programs and academic scholarships","Oratorical Contest / CCDHH Scholarship","$5,000-$15,000","Annual","https://www.optimist.org","https://www.optimist.org/learn/scholarships.cfm","Youth development + academic scholarships; many OC clubs; accessible scholarship programs","GOOD"),
    ("Soroptimist International","National","Women's Civic Organization","Soroptimist funds women's education and empowerment programs","Live Your Dream Awards / STEM","$2,500-$12,500","Annual","https://www.soroptimist.org","https://www.soroptimist.org/our-work/grant-and-award-programs.html","Women in STEM adjacent; education scholarships; OC chapters; accessible for women students","MEDIUM"),
    ("League of Women Voters Education Fund","National","Civic Organization","LWV education fund for civic education and democracy","Civic Education Grants","$5,000-$25,000","Annual","https://www.lwv.org","https://www.lwv.org/league-management/financial-resources/grant-opportunities","Civic education; not robotics-specific; accessible but wrong focus for VEX program","BAD"),
    ("Junior Achievement USA Foundation","National","Youth Civic Organization","Junior Achievement (financial literacy + entrepreneurship for K-12)","JA Programs / STEM + Entrepreneurship","$5,000-$50,000","Annual","https://www.juniorachievement.org","https://www.juniorachievement.org/web/ja-usa/why-ja","Entrepreneurship + STEM education; OC JA chapter; accessible programs; corporate-sponsored","MEDIUM"),

    # ---- NATIONAL - ADDITIONAL MEDIA/ENTERTAINMENT ----
    ("Walt Disney Company Foundation","National","Corporate Foundation (Entertainment)","Disney supports arts, education, and youth development","Disney Community Grants / VoluntEARS","$5,000-$50,000","Annual","https://thewaltdisneycompany.com/corporate-social-responsibility/","https://thewaltdisneycompany.com/corporate-social-responsibility/","Burbank CA HQ (near OC); community grants; education + arts focus; accessible for local programs","GOOD"),
    ("Warner Bros Discovery Foundation","National","Corporate Foundation (Entertainment)","Warner Bros Discovery funds education and community programs","Education Grants / Community Impact","$10,000-$100,000","Annual","https://www.warnerbros.com/company/social-responsibility","https://www.warnerbros.com/company/social-responsibility","Burbank CA HQ; education + community; accessible corporate grants; media company","MEDIUM"),
    ("Sony Pictures Foundation","National","Corporate Foundation (Entertainment)","Sony Pictures (Culver City CA) supports education and community","Community Grants / Education","$10,000-$50,000","Annual","https://www.sonypictures.com/corp/responsibility.html","https://www.sonypictures.com/corp/responsibility.html","Culver City CA (SoCal); education + community; accessible for SoCal school programs","GOOD"),
    ("NBCUniversal Foundation","National","Corporate Foundation (Media)","NBCUniversal (Universal City CA) funds education + STEM","21st Century Solutions / STEM Education","$10,000-$100,000","Annual","https://www.nbcuniversal.com/pages/corporate-social-responsibility","https://www.nbcuniversal.com/pages/corporate-social-responsibility","Universal City CA (SoCal/LA); STEM + education; accessible for SoCal school programs","GOOD"),
    ("ViacomCBS Foundation","National","Corporate Foundation (Media)","Paramount/ViacomCBS funds education + youth media programs","Youth Education / Media Literacy","$10,000-$100,000","Annual","https://www.paramount.com/social-responsibility","https://www.paramount.com/social-responsibility","West Hollywood CA office; education + media literacy; youth programs; SoCal-accessible","MEDIUM"),

    # ---- NATIONAL - CONSTRUCTION/ARCHITECTURE/REAL ESTATE ADDITIONAL ----
    ("Turner Construction Foundation","National","Corporate Foundation (Construction)","Turner Construction (major builder) supports STEM and community","STEM / Trades Education","$10,000-$100,000","Annual","https://www.turnerconstruction.com","https://www.turnerconstruction.com/about-us/responsibility","Major construction company; STEM + trades education; NYC HQ; SoCal offices; accessible","MEDIUM"),
    ("Kiewit Foundation","National","Corporate Foundation (Construction/Engineering)","Kiewit (infrastructure/construction) has large STEM scholarship program","Kiewit Foundation Scholarships","$3,000-$5,000","Annual","https://www.kiewit.com","https://www.kiewitfoundation.org","Major construction/engineering company; engineering scholarships; Omaha NE; STEM education","GOOD"),
    ("Skanska USA Foundation","National","Corporate Foundation (Construction)","Skanska (Swedish construction company US) supports STEM education","STEM / Green Building Education","$5,000-$50,000","Annual","https://www.usa.skanska.com","https://www.usa.skanska.com/about-skanska/sustainability/","Green construction; STEM + sustainability education; NYC HQ; accessible for school programs","MEDIUM"),
    ("AECOM Foundation","National","Corporate Foundation (Engineering/Construction)","AECOM (global engineering firm) funds STEM and infrastructure education","STEM / Infrastructure Engineering","$10,000-$100,000","Annual","https://aecom.com","https://aecom.com/social-value/","Global engineering firm; STEM + infrastructure; Los Angeles CA HQ; SoCal-accessible; excellent fit","GOOD"),
    ("Jacobs Engineering Foundation","National","Corporate Foundation (Engineering)","Jacobs Engineering (global) supports STEM and education","STEM / Engineering Education","$10,000-$100,000","Annual","https://www.jacobs.com","https://www.jacobs.com/impact","Global engineering/construction; STEM education; Dallas TX HQ; accessible programs","GOOD"),
    ("HNTB Foundation","National","Corporate Foundation (Infrastructure Engineering)","HNTB (infrastructure design) supports STEM and transportation","STEM / Transportation Engineering","$5,000-$25,000","Annual","https://www.hntb.com","https://www.hntb.com/about-hntb/social-responsibility","Infrastructure engineering; transportation; STEM education; Kansas City MO HQ; accessible","MEDIUM"),

    # ---- NATIONAL FOUNDATIONS - ADDITIONAL ACCESSIBLE ----
    ("Newman's Own Foundation","National","Corporate Foundation (Food/Philanthropy)","Newman's Own Foundation (100% profits to charity) funds education + camps","Education / Youth Development","$25,000-$200,000","Annual (LOI)","https://www.newmansown.com/newmans-own-foundation/","https://www.newmansown.com/newmans-own-foundation/grant-application/","100% profits to charity; education + youth development; Westport CT; accessible LOI process","MEDIUM"),
    ("Ben & Jerry's Foundation","National","Corporate Foundation (Food/Social Justice)","Ben & Jerry's foundation funds grassroots social change","Grassroots Social Change Grants","$5,000-$15,000","Annual","https://www.benandjerryfoundation.org","https://www.benandjerryfoundation.org/grant-programs/","Social justice + community; Burlington VT; grassroots focus; not robotics-specific fit","BAD"),
    ("Patagonia Environmental Grants","National","Corporate Foundation (Outdoor/Environmental)","Patagonia funds environmental activism and STEM nature education","Environmental / STEM Nature Grants","$5,000-$20,000","Annual","https://www.patagonia.com/how-we-fund-grassroots-activism.html","https://www.patagonia.com/how-we-fund-grassroots-activism.html","Environmental focus; Ventura CA (SoCal!); STEM + nature; not robotics-specific; accessible","BAD"),
    ("REI Co-op Foundation","National","Corporate Foundation (Outdoor Retail)","REI funds outdoor recreation and environmental stewardship","Outdoor STEM / Conservation Grants","$5,000-$25,000","Annual","https://www.rei.com/stewardship","https://www.rei.com/stewardship/grants","Outdoor recreation + conservation; not robotics-specific; accessible for programs with outdoor tie","BAD"),
    ("Levi Strauss Foundation","National","Corporate Foundation (Apparel)","Levi Strauss Foundation funds worker rights and education","Worker Rights / Education Grants","$25,000-$200,000","Annual (invitation)","https://www.levistrauss.com/sustainability/foundation/","https://www.levistrauss.com/sustainability/foundation/","Worker rights + education; San Francisco CA; primarily invitation-based; wrong focus for VEX","BAD"),
    ("Gap Foundation","National","Corporate Foundation (Apparel)","Gap Foundation supports education and economic empowerment","Education / Workforce Development","$10,000-$100,000","Annual","https://www.gap.com/socialresponsiblity","https://www.gap.com/socialresponsiblity","Retail/apparel; education + workforce; San Francisco CA; accessible but not robotics-specific","BAD"),
    ("Nike Foundation","National","Corporate Foundation (Sports/Apparel)","Nike Foundation (Girl Effect) supports girls' empowerment globally","Girl Effect / Youth Development","$100,000-$1,000,000","Annual (invitation)","https://www.nikefoundation.org","https://www.nikefoundation.org","Girls' empowerment globally; Beaverton OR; primarily invitation-based; not robotics fit","BAD"),
    ("Under Armour Foundation","National","Corporate Foundation (Sports/Apparel)","UA Foundation supports youth sport and fitness programs","Youth Fitness / Sport Grants","$10,000-$100,000","Annual","https://www.underarmour.com/en-us/t/ua-community.html","https://www.underarmour.com/en-us/t/ua-community.html","Youth fitness/sports; Baltimore MD; sports focus not robotics; accessible but wrong fit","BAD"),

    # ---- ADDITIONAL CALIFORNIA FOUNDATIONS ----
    ("LA84 Foundation","Regional","Foundation (Youth Sports/Fitness CA)","LA84 Foundation (1984 Olympic legacy) funds youth sports in SoCal","Youth Sports / Active Kids Grants","$5,000-$50,000","Annual","https://la84.org","https://la84.org/grant-programs/","SoCal youth sports; Los Angeles; STEM-adjacent but sports focus; accessible for OC programs","MEDIUM"),
    ("Blue Shield of California Foundation","State","Corporate Foundation (Health Insurance CA)","Blue Shield CA Foundation funds health + community in California","Clinic / Community Health Grants","$50,000-$500,000","Annual (invitation)","https://www.blueshieldcafoundation.org","https://www.blueshieldcafoundation.org/grants","California health focus; primarily invitation; health not robotics; wrong fit but accessible","BAD"),
    ("Kaiser Permanente Community Benefit","State","Corporate Foundation (Healthcare CA)","Kaiser Permanente (CA-based HMO) community benefit programs in California","Community Health / Education Grants","$10,000-$100,000","Annual","https://healthy.kaiserpermanente.org/about-kaiser-permanente/community-health","https://healthy.kaiserpermanente.org/about-kaiser-permanente/community-health","California HMO; community health + education; OC Kaiser facilities; accessible local programs","MEDIUM"),
    ("Dignity Health Foundation","State","Corporate Foundation (Healthcare CA)","Dignity Health (CommonSpirit, CA hospitals) community programs","Community Health / Education Grants","$10,000-$100,000","Annual","https://www.dignityhealth.org","https://www.dignityhealth.org/about-us/community-benefit","California hospital system; community + education grants; OC hospitals; accessible programs","MEDIUM"),
    ("Western Digital Foundation","Regional","Corporate Foundation (Data Storage CA)","Western Digital (San Jose CA) funds STEM education and community","STEM / Data Technology Education","$10,000-$50,000","Annual","https://www.westerndigital.com","https://www.westerndigital.com/company/corporate-responsibility","Data storage/HDD maker; STEM education; San Jose CA HQ; accessible programs; tech focus","MEDIUM"),
    ("Broadcom Foundation","Regional","Corporate Foundation (Semiconductor CA)","Broadcom (Irvine CA) funds STEM education and innovation","STEM / Science Innovation Grants","$10,000-$100,000","Annual","https://www.broadcomfoundation.org","https://www.broadcomfoundation.org/grants","Semiconductor company HQ in Irvine CA (OC!); science + STEM education; VERY LOCAL; excellent fit","GOOD"),
    ("Masimo Foundation","Local","Corporate Foundation (Medical Tech OC)","Masimo Corporation (Irvine CA) blood monitoring; STEM + community","STEM / Community Education Grants","$5,000-$50,000","Annual","https://www.masimo.com","https://www.masimo.com/company/social-responsibility/","Irvine CA (OC!) medical technology company; local STEM + community; very accessible for OC schools","GOOD"),
    ("Edwards Lifesciences Foundation","Local","Corporate Foundation (Medical Tech OC)","Edwards Lifesciences (Irvine CA) heart valves; STEM + community","STEM / Healthcare Education Grants","$5,000-$50,000","Annual","https://www.edwards.com","https://www.edwards.com/about/corporate-citizenship","Irvine CA (OC!) medical devices; STEM education; local funder; very accessible for OC schools","GOOD"),
    ("PIMCO Foundation","Local","Corporate Foundation (Finance OC)","PIMCO (Newport Beach CA) investment firm; community + education","Education / Community Grants","$10,000-$100,000","Annual","https://www.pimco.com/en-us/us/our-firm/responsibility","https://www.pimco.com/en-us/us/our-firm/responsibility","Newport Beach CA (OC!) major investment firm; community + education; very local OC funder","GOOD"),
    ("Pacific Life Foundation","Local","Corporate Foundation (Insurance OC)","Pacific Life (Newport Beach CA) insurance company foundation","Education / Community Grants","$10,000-$100,000","Annual","https://www.pacificlife.com","https://www.pacificlife.com/home/about/community-relations.html","Newport Beach CA (OC!) insurance company; community + education; very local OC funder; accessible","GOOD"),
    ("Hoag Hospital Foundation","Local","Hospital Foundation (OC)","Hoag Hospital (Newport Beach CA) foundation for community health + education","Community Health / STEM Education","$5,000-$50,000","Annual","https://www.hoag.org","https://www.hoag.org/giving","Newport Beach CA (OC!) hospital; community health + education; local OC funder; accessible","MEDIUM"),
    ("CHOC Foundation (Children's Health OC)","Local","Hospital Foundation (OC)","Children's Hospital of Orange County foundation for pediatric health + education","Pediatric Health / STEM Education","$5,000-$50,000","Annual","https://www.choc.org","https://www.choc.org/give/","Orange CA (OC!); children's hospital + education; local OC funder; accessible for school programs","MEDIUM"),
    ("St. Joseph Health Foundation","Local","Hospital Foundation (OC)","St. Joseph Health (Providence) hospitals in OC; community + education grants","Community Health / Education Grants","$5,000-$50,000","Annual","https://www.providence.org/locations/southern-california","https://www.providence.org/locations/southern-california","OC Providence/St. Joseph hospitals; community + education; local OC funder; accessible programs","MEDIUM"),

    # ---- ADDITIONAL NATIONAL STEM COMPETITIONS / ORGANIZATIONS ----
    ("TEAMS (Tests of Engineering Aptitude) Foundation","National","STEM Organization","TEAMS (NSPE) engineering aptitude tests and scholarships for HS students","TEAMS Competition / Scholarships","$1,000-$5,000","Annual","https://www.nspe.org/resources/students/teams","https://www.nspe.org/resources/students/teams","NSPE engineering competition; STEM/robotics adjacent; accessible for engineering-focused students","MEDIUM"),
    ("SkillsUSA Foundation","National","CTE Organization Foundation","SkillsUSA competitions and scholarships for technical/trade students","SkillsUSA Championship / Scholarships","$1,000-$10,000","Annual","https://www.skillsusa.org","https://www.skillsusa.org/programs/scholarships/","CTE/technical education; robotics competition adjacent; accessible for engineering/tech students","MEDIUM"),
    ("DECA Foundation","National","Business/STEM Organization","DECA (marketing/business/entrepreneurship) foundation scholarships","Scholarships / Program Support","$1,000-$10,000","Annual","https://www.deca.org","https://www.deca.org/programs/scholarships/","Business + entrepreneurship; STEM adjacent; accessible scholarships; not robotics-specific","MEDIUM"),
    ("Technology Student Association (TSA) Foundation","National","STEM Organization","TSA competitions and STEM programs for K-12 technology students","TSA Scholarships / STEM Competitions","$1,000-$10,000","Annual","https://tsaweb.org","https://tsaweb.org/programs-competitions/scholarships","Technology Student Association; robotics-adjacent; STEM competitions; accessible programs","GOOD"),
    ("HOSA Future Health Professionals Foundation","National","Healthcare/STEM Organization","HOSA (healthcare education) competitions and scholarships","Healthcare STEM Scholarships","$1,000-$5,000","Annual","https://www.hosa.org","https://www.hosa.org/scholarships","Healthcare education; STEM adjacent; not robotics-specific; accessible scholarships","MEDIUM"),
    ("National FFA Organization Foundation","National","Agricultural/STEM Organization","FFA (Future Farmers of America) agri-STEM scholarships + programs","FFA Scholarships / Agri-STEM","$1,000-$25,000","Annual","https://www.ffa.org","https://www.ffa.org/participate/grants-and-scholarships","Agriculture + STEM; engineering adjacent; accessible scholarship programs; national reach","MEDIUM"),

    # ---- LOCAL OC/FULLERTON ADDITIONAL ----
    ("Fullerton Lions Club Foundation","Local","Civic Organization (Lions)","Fullerton Lions Club funds local education and youth programs","Community Education Grants","$500-$5,000","Annual","https://www.lionsclubs.org","https://www.lionsclubs.org/en/discover-our-clubs/find-a-club","Directly serves Fullerton; local civic club; youth and education grants; very accessible","GOOD"),
    ("Fullerton Rotary Club Foundation","Local","Civic Organization (Rotary)","Fullerton Rotary Club funds local community projects and education","Community Education Grants","$1,000-$10,000","Annual","https://www.rotary5320.org","https://www.rotary5320.org","Directly serves Fullerton; local Rotary club; youth + education; very accessible","GOOD"),
    ("Brea Kiwanis Club","Local","Civic Organization (Kiwanis)","Brea (adjacent to Fullerton) Kiwanis Club supports youth programs","Youth / Education Grants","$500-$5,000","Annual","https://www.kiwanis.org","https://www.kiwanis.org","Adjacent to Fullerton; local civic club; youth development; accessible for school programs","GOOD"),
    ("Placentia-Yorba Linda USD Foundation","Local","School District Foundation","PYLUSD Foundation funds education programs in adjacent district","Education / STEM Grants","$1,000-$10,000","Annual","https://www.pylusd.org","https://www.pylusd.org/district/pylusd-foundation","Adjacent school district; STEM education; accessible for neighboring school programs","MEDIUM"),
    ("Fullerton PTSA Council","Local","Parent/Community Organization","Fullerton PTSA and Troy PTSA parent fundraising and grants","PTSA Education Grants","$500-$5,000","Annual","https://www.capta.org","https://www.capta.org/chapters/ptsa/","Troy's own PTSA; direct school support; parent fundraising; very accessible local source","GOOD"),
    ("Fullerton Museum Center","Local","Cultural Organization (Fullerton)","Fullerton Museum Center supports education and community programs","Community Education Grants","$1,000-$10,000","Annual","https://www.fullertonmuseum.com","https://www.fullertonmuseum.com","Fullerton cultural org; STEM + education tie-ins; accessible for local school programs","MEDIUM"),
    ("Discovery Cube Orange County","Local","STEM Education Nonprofit (OC)","Discovery Cube (Santa Ana CA) is OC's STEM museum for K-12","STEM / Robotics Education Grants","$5,000-$25,000","Annual","https://www.discoverycube.org","https://www.discoverycube.org/learn/educators/grants/","OC STEM museum; robotics programs; Santa Ana CA (OC); very accessible for local schools","GOOD"),
    ("Pretend City Children's Museum","Local","Children's Museum (OC)","Pretend City (Irvine CA) is OC's children's museum; STEM focus","STEM Education / Community Grants","$1,000-$10,000","Annual","https://www.pretendcity.org","https://www.pretendcity.org/educators/","Irvine CA (OC); STEM education; children's museum; community grants for local schools","MEDIUM"),

    # ---- REMAINING NATIONAL GAPS ----
    ("Toshiba America Foundation","National","Corporate Foundation (Electronics)","Toshiba funds K-12 STEM education across the US","K-12 STEM Classroom Grants","$1,000-$20,000","Annual","https://www.toshiba.com/taf","https://www.toshiba.com/taf/index.cfm","Japanese electronics company US foundation; K-12 STEM classroom grants; very accessible; electronics","GOOD"),
    ("Panasonic Foundation","National","Corporate Foundation (Electronics)","Panasonic Foundation funds education innovation and STEM","Education Innovation Grants","$10,000-$100,000","Annual","https://www.panasonic.com/us/corporate/sustainability/community.html","https://www.panasonic.com/us/corporate/sustainability/community.html","Japanese electronics company; STEM education; Newark NJ HQ; accessible school programs","MEDIUM"),
    ("Ricoh Foundation","National","Corporate Foundation (Electronics)","Ricoh (printers/imaging) supports STEM and sustainability education","STEM / Sustainability Education","$5,000-$25,000","Annual","https://www.ricoh-usa.com/en/about-ricoh/sustainability","https://www.ricoh-usa.com/en/about-ricoh/sustainability","Printers and imaging; STEM + sustainability; Malvern PA HQ; accessible programs","MEDIUM"),
    ("Sharp Electronics Foundation","National","Corporate Foundation (Electronics)","Sharp (display/electronics) supports STEM and community programs","STEM / Electronics Education","$5,000-$25,000","Annual","https://www.sharpusa.com","https://www.sharpusa.com/corporate-citizenship","Japanese electronics company; displays and electronics; STEM education; accessible","MEDIUM"),
    ("Seagate Foundation","National","Corporate Foundation (Data Storage)","Seagate (hard drives/data storage) funds STEM education","STEM / Data Technology Education","$10,000-$50,000","Annual","https://www.seagate.com","https://www.seagate.com/corporate-sustainability/","Data storage company; STEM education; Fremont CA HQ; accessible programs; Silicon Valley-based","MEDIUM"),
    ("Sandisk / Western Digital STEM","National","Corporate Foundation (Flash Storage)","SanDisk (WD subsidiary) flash storage; STEM education programs","STEM / Technology Education","$5,000-$25,000","Annual","https://www.westerndigital.com","https://www.westerndigital.com/company/corporate-responsibility","Flash storage; STEM education; Silicon Valley CA; accessible for school programs; tech focus","MEDIUM"),
    ("Raytheon STEM Outreach","National","Corporate (Defense Electronics)","Raytheon (RTX subsidiary) runs MathMovesU and STEM education programs","MathMovesU / STEM Outreach","$10,000-$100,000","Annual","https://www.rtx.com/raytheon/who-we-are/community","https://www.rtx.com/raytheon/who-we-are/community","RTX division; MathMovesU math education; STEM outreach; major defense company; accessible","GOOD"),
    ("Honeywell Hometown Solutions","National","Corporate Foundation (Industrial/Defense)","Honeywell's science + math education initiative for K-12","Science + Math + Sustainability","$10,000-$100,000","Annual","https://www.honeywell.com/us/en/social-impact","https://www.honeywell.com/us/en/social-impact","Industrial/defense/aerospace company; K-12 science + math; Charlotte NC HQ; accessible programs","GOOD"),
    ("3M Foundation","National","Corporate Foundation (Industrial)","3M Foundation funds STEM education across the US","3M Visiting Wizards / STEM Grants","$10,000-$100,000","Annual","https://www.3m.com/3M/en_US/gives-us/","https://www.3m.com/3M/en_US/gives-us/","Industrial materials/electronics company; STEM education; St. Paul MN; accessible programs","GOOD"),
    ("BASF Foundation","National","Corporate Foundation (Chemicals)","BASF (German chemicals company US) funds STEM education","STEM / Chemistry Education","$10,000-$100,000","Annual","https://www.basf.com/us/en/who-we-are/sustainability/employees-and-society/social-engagement.html","https://www.basf.com/us/en/who-we-are/sustainability/employees-and-society/social-engagement.html","Chemical company; STEM + chemistry; Florham Park NJ HQ; accessible school programs","MEDIUM"),
    ("DuPont Education Foundation","National","Corporate Foundation (Materials Science)","DuPont (specialty materials) funds STEM and education programs","STEM / Materials Science Education","$10,000-$100,000","Annual","https://www.dupont.com","https://www.dupont.com/about/corporate-stewardship.html","Materials science company; STEM education; Wilmington DE HQ; accessible school programs","MEDIUM"),
    ("Corning Incorporated Foundation","National","Corporate Foundation (Glass/Materials)","Corning (specialty glass and ceramics) funds STEM education","STEM / Innovation Education","$10,000-$100,000","Annual","https://www.corning.com","https://www.corning.com/worldwide/en/sustainability/communities.html","Specialty glass and ceramics; STEM education; Corning NY HQ; accessible school programs","MEDIUM"),
    ("Dow Foundation","National","Corporate Foundation (Chemicals)","Dow (chemical company) funds STEM, environment, and community","STEM / Community Grants","$10,000-$100,000","Annual","https://www.dow.com","https://www.dow.com/sustainability/dow-foundation.html","Chemical company; STEM + community; Midland MI HQ; accessible school programs; major funder","MEDIUM"),
    ("Eastman Chemical Foundation","National","Corporate Foundation (Chemicals)","Eastman Chemical funds STEM education and community programs","STEM / Community Education","$5,000-$50,000","Annual","https://www.eastman.com","https://www.eastman.com/Company/Sustainability/Pages/Community.aspx","Specialty chemicals; STEM education; Kingsport TN HQ; accessible school programs","MEDIUM"),
]

with open(output_file, 'a', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerows(entries)

print(f"Batch 11 complete: {len(entries)} new entries appended")
