import csv, os

output_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'troyvex_donor_list.csv')

entries = [
    ("Qualcomm Foundation (Thinkabit Lab)","Local","Corporate Foundation (Semiconductor SoCal)","Qualcomm (San Diego CA) Thinkabit Lab STEM education programs","Thinkabit / STEM Education Grants","$10,000-$100,000","Annual","https://www.qualcomm.com","https://www.qualcomm.com/company/qualcomm-foundation","San Diego CA (SoCal!) HQ; major semiconductor; Thinkabit STEM lab; strong fit for VEX","GOOD"),
    ("Unity Technologies Foundation","National","Corporate Foundation (Game Engine)","Unity (game engine used in robotics simulation) funds STEM education","STEM / 3D Simulation Education","$10,000-$100,000","Annual","https://unity.com","https://unity.com/our-company/social-impact","Unity used in robotics simulation + VR; STEM + 3D education; San Francisco CA; accessible","GOOD"),
    ("Snap Inc. Foundation","Regional","Corporate Foundation (Social Media)","Snap (Snapchat) HQ Santa Monica CA; Yellow fund for youth entrepreneurs","Yellow Fund / Youth Entrepreneur Grants","$10,000-$150,000","Annual","https://www.snap.com","https://www.snapfoundation.org","Santa Monica CA (SoCal!); youth + tech entrepreneurship; accessible; excellent local fit","GOOD"),
    ("SpaceX STEM Outreach","National","Corporate Program (Aerospace)","SpaceX (Elon Musk) supports STEM + aerospace education; Hawthorne CA HQ","STEM / Aerospace Education","$10,000-$100,000","Annual","https://www.spacex.com","https://www.spacex.com/human-spaceflight/","Hawthorne CA (SoCal!) HQ; rockets + aerospace; STEM education; very local CA company","GOOD"),
    ("Anduril Industries Education","Local","Corporate Program (Defense Tech OC)","Anduril (defense AI drones) HQ Costa Mesa CA (OC!) STEM programs","STEM / Autonomous Systems Education","$10,000-$100,000","Annual","https://www.anduril.com","https://www.anduril.com/company/","Costa Mesa CA (OC!!) defense AI; drones/autonomous systems; very relevant robotics; local","GOOD"),
    ("Relativity Space Education","National","Corporate Program (3D Printing / Rockets)","Relativity Space (Long Beach CA!) 3D-printed rockets; STEM education","STEM / 3D Printing / Aerospace","$10,000-$50,000","Annual","https://www.relativityspace.com","https://www.relativityspace.com/","Long Beach CA (SoCal!) rocket company; 3D printing + aerospace; STEM education; very local","GOOD"),
    ("Rocket Lab Education","National","Corporate Program (Small Rockets)","Rocket Lab (Long Beach CA!) small satellite launchers; STEM programs","STEM / Space Education","$10,000-$50,000","Annual","https://www.rocketlabusa.com","https://www.rocketlabusa.com/mission-archive/","Long Beach CA (SoCal!) space company; STEM + aerospace; very local; excellent VEX fit","GOOD"),
    ("NASA JPL Education Outreach","Local","Federal Research Lab (Adjacent SoCal)","JPL (NASA lab Pasadena CA, near OC) education + outreach programs","JPL Education Outreach / STEM","$5,000-$50,000","Annual","https://www.jpl.nasa.gov","https://www.jpl.nasa.gov/edu/","Pasadena CA (adjacent OC!); NASA JPL; STEM education + internships; very local; top priority","GOOD"),
    ("NASA STEM Engagement","National","Federal Agency (Space)","NASA K-12 education and outreach programs; multiple opportunity types","NASA STEM Programs","$1,000-$50,000","Annual (various)","https://www.nasa.gov/audience/foreducators/","https://www.nasa.gov/audience/foreducators/","NASA STEM education; Artemis + aerospace; JPL in Pasadena CA; TOP PRIORITY for VEX","GOOD"),
    ("Department of Energy STEM Programs","National","Federal Grant Agency","DOE funds STEM education through national labs and school programs","DOE STEM Rising / Internships","$5,000-$50,000","Annual","https://www.energy.gov","https://www.energy.gov/stem","Federal STEM; Lawrence Livermore (CA!) + other DOE labs; accessible programs for schools","GOOD"),
    ("NSF STEM Education Grants","National","Federal Grant Agency","National Science Foundation funds STEM education at all levels","NSF Education Grants","$10,000-$500,000","Annual (various)","https://www.nsf.gov","https://www.nsf.gov/funding/education.jsp","Federal STEM funding; education grants school/district level; highly competitive; accessible","MEDIUM"),
    ("NJROTC Foundation","National","Military Foundation (NJROTC Direct)","National NJROTC Foundation supports NJROTC cadet programs directly","NJROTC Program Support","$5,000-$25,000","Annual","https://www.njrotcfoundation.org","https://www.njrotcfoundation.org","DIRECTLY funds NJROTC programs like Troy; cadet support; TOP PRIORITY for Troy NJROTC","GOOD"),
    ("Navy League OC Council","Local","Military Organization (Navy League)","OC Navy League Council supports naval/NJROTC programs locally","NJROTC / Sea Cadet Support","$1,000-$10,000","Annual","https://www.navyleague.org","https://www.navyleague.org/councils/","OC council of Navy League; NJROTC DIRECTLY SUPPORTED; very accessible; local top priority","GOOD"),
    ("American Legion Post 142 Fullerton","Local","Military Civic Organization (Fullerton)","Fullerton American Legion Post 142 supports local veterans + youth","JROTC / Youth Education Support","$500-$2,500","Annual","https://www.legion.org","https://www.legion.org","Fullerton Legion post; JROTC directly supported; very accessible; local veteran community","GOOD"),
    ("VFW Post Fullerton","Local","Military Civic Organization (Fullerton)","Fullerton VFW Post supports veterans + youth military programs","JROTC / Youth Grants","$500-$2,500","Annual","https://www.vfw.org","https://www.vfw.org","Fullerton VFW post; JROTC directly supported; very accessible; local veteran community","GOOD"),
    ("DAR OC Chapter","Local","Civic/Patriotic Organization","OC Daughters of the American Revolution chapter; scholarships for JROTC","JROTC Scholarships / DAR Medals","$500-$5,000","Annual","https://www.dar.org","https://www.dar.org/national-society/scholarships","Patriotic organization; JROTC program scholarships; NJROTC directly relevant; accessible","GOOD"),
    ("SAR OC Chapter","Local","Civic/Patriotic Organization","OC Sons of the American Revolution; JROTC connections and awards","JROTC Medal / Scholarships","$500-$2,500","Annual","https://www.sar.org","https://www.sar.org/programs/scholarships/","Patriotic organization; JROTC medal program; NJROTC directly recognized; accessible","GOOD"),
    ("Orange County STEM Initiative","Local","Regional STEM Organization","OC STEM Initiative connecting OC schools to STEM opportunities","OC STEM School Grants","$5,000-$25,000","Annual","https://www.ocstem.org","https://www.ocstem.org/educators","OC-specific STEM initiative; directly serves Fullerton area; very accessible for Troy HS","GOOD"),
    ("OCDE STEM Department","Local","County Education Agency","OC Dept of Education STEM programs for all OC school districts","OCDE STEM Grants","$5,000-$25,000","Annual","https://www.ocde.us","https://www.ocde.us/STEM","OC Dept of Ed; DIRECT OC funder; STEM grants for OC schools; Troy HS directly eligible","GOOD"),
    ("CSUF Engineering Foundation","Local","University Foundation (Adjacent)","Cal State Fullerton Engineering Dept; adjacent to Troy HS; STEM collaboration","STEM / Engineering Collaboration","$1,000-$10,000","Annual","https://www.fullerton.edu/engineering","https://www.fullerton.edu/engineering/","CSUF adjacent to Troy HS; STEM engineering; university-school collaboration; top priority","GOOD"),
    ("Discovery Cube OC","Local","STEM Museum (OC)","Discovery Cube (Santa Ana CA) is OC STEM museum for K-12 programs","STEM / Robotics Education Grants","$5,000-$25,000","Annual","https://www.discoverycube.org","https://www.discoverycube.org/learn/educators/grants/","OC STEM museum; robotics programs; Santa Ana CA (OC); very accessible for local schools","GOOD"),
    ("Port of Long Beach STEM Fund","Local","Port Authority (Adjacent SoCal)","Port of Long Beach (adjacent to OC) STEM + maritime education grants","Maritime STEM Grants","$5,000-$25,000","Annual","https://www.polb.com","https://www.polb.com/community/grants/","Long Beach CA (adjacent OC); maritime STEM; logistics + engineering; local OC funder","GOOD"),
    ("Broadcom Foundation (Irvine CA)","Local","Corporate Foundation (Semiconductor OC)","Broadcom (Irvine CA!) foundation for science + STEM education","STEM / Science Innovation Grants","$10,000-$100,000","Annual","https://www.broadcomfoundation.org","https://www.broadcomfoundation.org/grants","Irvine CA (OC!) HQ; science + STEM; Broadcom Masters competition; TOP LOCAL PRIORITY","GOOD"),
    ("Samueli Foundation (Irvine CA)","Local","Private Foundation (OC Tech)","Henry Samueli (Broadcom co-founder, Irvine CA) OC foundation for education","STEM / Education Grants","$25,000-$1,000,000","Annual (invitation)","https://www.samuelifoundation.org","https://www.samuelifoundation.org","Irvine CA (OC!); Broadcom co-founder; education + STEM; major OC funder; excellent fit","GOOD"),
    ("Irvine Company Foundation","Local","Corporate Foundation (Real Estate OC)","Irvine Company (largest OC landowner) education + community grants","Education / Community Grants","$25,000-$500,000","Annual","https://www.irvinecompany.com","https://www.irvinecompany.com/corporate-responsibility","Irvine CA (OC!) major developer; education + community; largest OC employer; excellent fit","GOOD"),
    ("Taco Bell Foundation (Irvine CA)","Local","Corporate Foundation (Restaurant OC)","Taco Bell HQ Irvine CA; Live Mas Scholarship for ambitious youth","Live Mas Scholarship","$5,000-$25,000","Annual","https://www.tacobellfoundation.org","https://www.tacobellfoundation.org/live-mas-scholarship/","Irvine CA (OC!) HQ; Live Mas Scholarship for ambitious young people; VERY LOCAL; accessible","GOOD"),
    ("In-N-Out Foundation (Irvine CA)","Local","Corporate Foundation (Restaurant OC)","In-N-Out Burger (Irvine CA HQ) foundation for youth and community","Youth / Community Grants","$5,000-$25,000","Annual","https://www.in-n-out.com","https://www.in-n-out.com/foundation.aspx","Irvine CA HQ (OC!); local CA company; youth + community; accessible for OC school programs","GOOD"),
    ("PIMCO Foundation (Newport Beach)","Local","Corporate Foundation (Finance OC)","PIMCO (Newport Beach CA) investment firm; community + education grants","Education / Community Grants","$10,000-$100,000","Annual","https://www.pimco.com","https://www.pimco.com/en-us/us/our-firm/responsibility","Newport Beach CA (OC!) major investment firm; education + community; very local OC funder","GOOD"),
    ("Pacific Life Foundation (Newport Beach)","Local","Corporate Foundation (Insurance OC)","Pacific Life (Newport Beach CA) insurance company foundation","Education / Community Grants","$10,000-$100,000","Annual","https://www.pacificlife.com","https://www.pacificlife.com/home/about/community-relations.html","Newport Beach CA (OC!) insurance; community + education; very local OC funder; accessible","GOOD"),
    ("SCE Foundation (Fullerton Service Area)","Local","Corporate Foundation (Utility OC)","Southern California Edison serves Fullerton; strong STEM programs in OC","STEM Workforce / Education Grants","$5,000-$100,000","Annual","https://www.sce.com","https://www.sce.com/about-sce/community/foundation","DIRECTLY serves Fullerton/OC; STEM workforce development; very accessible for local schools","GOOD"),
    ("National Robotics Week Mini Grants","National","STEM Organization (Robotics)","National Robotics Week annual event + mini grants for robotics programs","Robotics Week Mini Grants","$500-$5,000","Annual (April)","https://www.nationalroboticsweek.org","https://www.nationalroboticsweek.org/grants/","Robotics Week; mini grants for robotics programs; VEX directly eligible; accessible","GOOD"),
    ("RECF Team Grants (VEX)","National","Robotics Foundation (VEX)","RECF (VEX governing foundation) team grants for new and active teams","Team Startup Grants","$500-$5,000","Annual","https://www.roboticseducation.org","https://www.roboticseducation.org/grants/","VEX ecosystem; DIRECTLY relevant team grants; Troy VEX teams eligible; apply immediately","GOOD"),
    ("VEX Robotics World Championship Sponsor Fund","National","Robotics Competition (VEX)","VEX Worlds has sponsor-funded travel assistance for qualifying teams","World Championship Travel Aid","$1,000-$5,000","Annual (post-qualify)","https://www.vexrobotics.com","https://www.roboticseducation.org/scholarships/","VEX DIRECTLY - Troy qualified for Worlds; travel + registration assistance; urgent apply","GOOD"),
    ("Code.org CS Education Grants","National","STEM Organization (CS Education)","Code.org funds computer science education in K-12 schools","CS Education Grants","$10,000-$100,000","Annual","https://code.org","https://code.org/educate","CS education; Seattle WA; programming + robotics STEM; accessible for school programs","GOOD"),
    ("Girls Who Code Foundation","National","STEM Organization (CS/Women)","Girls Who Code funds CS education for girls in K-12 schools","CS / STEM for Women Grants","$5,000-$50,000","Annual","https://girlswhocode.com","https://girlswhocode.com/programs","CS + STEM for women; NJROTC women cadets eligible; accessible school programs","GOOD"),
    ("Science Olympiad Foundation","National","STEM Competition Organization","Science Olympiad funds competitions + STEM education programs","Science Olympiad Scholarships + Grants","$1,000-$10,000","Annual","https://www.soinc.org","https://www.soinc.org/about/national-headquarters/science-olympiad-foundation","STEM competition org; robotics events; accessible scholarships + team programs","GOOD"),
    ("Project Lead The Way Foundation","National","STEM Curriculum Organization","PLTW provides engineering and CS curriculum to K-12 schools","Curriculum / Program Support Grants","$10,000-$100,000","Annual","https://www.pltw.org","https://www.pltw.org/grants","Engineering curriculum; STEM education; accessible grants for school programs; engineering focus","GOOD"),
    ("Army Educational Outreach Program","National","Military STEM Program","U.S. Army STEM education programs for students and teachers","eCYBERMISSION / STEM Competitions","$5,000-$50,000","Annual","https://www.usaeop.com","https://www.usaeop.com","Army STEM; eCYBERMISSION competition; NJROTC-adjacent; accessible for military-affiliated","GOOD"),
    ("Office of Naval Research STEM (Sea Perch)","National","Federal Military STEM Program","ONR funds Naval STEM including Sea Perch underwater robotics program","Sea Perch / Naval STEM","$5,000-$50,000","Annual","https://www.nre.navy.mil","https://www.nre.navy.mil/work-with-us/","Sea Perch underwater robotics; NJROTC directly relevant; aquatic robotics; accessible","GOOD"),
    ("Civil Air Patrol National Foundation","National","Military Youth Foundation","CAP (Air Force Auxiliary) aerospace + STEM education for cadets","Aerospace / STEM Education","$5,000-$25,000","Annual","https://www.gocivilairpatrol.com","https://www.capnhq.gov/CAP.PublicSiteHomePage.aspx","Air Force Auxiliary; aerospace + STEM; NJROTC adjacent; accessible cadet programs","GOOD"),
    ("Medtronic Foundation","National","Corporate Foundation (Medical Devices)","Medtronic (medical device + robotics) funds STEM + healthcare education","STEM / Healthcare Education","$10,000-$100,000","Annual","https://www.medtronic.com","https://www.medtronic.com/us-en/about/medtronic-foundation.html","Medical device maker (surgical robots adjacent); STEM education; Minneapolis MN; accessible","GOOD"),
    ("Intuitive Foundation","National","Corporate Foundation (Surgical Robotics)","Intuitive Surgical (da Vinci robot) STEM + robotics education programs","Robotics / STEM Education","$10,000-$100,000","Annual","https://www.intuitive.com","https://www.intuitive.com/en-us/about-us/foundation","Makes da Vinci surgical robot; EXTREMELY relevant to robotics; Sunnyvale CA; excellent fit","GOOD"),
    ("Stryker Foundation","National","Corporate Foundation (Medical Robotics)","Stryker (Mako surgical robot) STEM and community programs","STEM / Surgical Robotics Education","$5,000-$100,000","Annual","https://www.stryker.com","https://www.stryker.com/us/en/about/responsibility.html","Makes Mako surgical robot; robotics-adjacent; STEM education; Kalamazoo MI; accessible","GOOD"),
    ("Jack Kent Cooke Foundation","National","Scholarship (High-Achieving Low-Income)","JKC Foundation for high-achieving students with financial need","Young Scholars / College Scholarship","$40,000-$55,000/yr","Annual","https://www.jkcf.org","https://www.jkcf.org/our-scholarships/","High-achieving + financial need; STEM students; Troy NJROTC seniors; individual scholarships","GOOD"),
    ("Davidson Fellows Scholarship","National","Scholarship (Gifted STEM)","Davidson Institute for gifted students who complete major STEM projects","Davidson Fellows Award","$10,000-$50,000","Annual (April deadline)","https://www.davidsongifted.org","https://www.davidsongifted.org/gifted-programs/davidson-fellows-scholarship/","Gifted STEM projects; robotics competition wins qualify; Troy VEX students may qualify","GOOD"),
    ("Accenture Foundation","National","Corporate Foundation (Consulting)","Accenture funds skills development and STEM education globally","Skills to Succeed / STEM","$10,000-$100,000","Annual","https://www.accenture.com","https://www.accenture.com/us-en/about/corporate-citizenship","Global consulting; STEM + workforce; accessible school programs","MEDIUM"),
    ("Autodesk Foundation","National","Corporate Foundation (Design Software)","Autodesk Foundation funds design-powered innovation + STEM education","Design for Innovation Grants","$25,000-$500,000","Annual","https://www.autodesk.org","https://www.autodesk.org/grantee-stories","CAD/3D design software; San Francisco CA; STEM design education; robotics-adjacent; accessible","GOOD"),
    ("3M Foundation","National","Corporate Foundation (Industrial)","3M Foundation funds STEM education and community across the US","3M Visiting Wizards / STEM Grants","$10,000-$100,000","Annual","https://www.3m.com/3M/en_US/gives-us/","https://www.3m.com/3M/en_US/gives-us/","Industrial + electronics company; STEM education; St. Paul MN; accessible school programs","GOOD"),
    ("Honeywell Hometown Solutions","National","Corporate Foundation (Industrial/Defense)","Honeywell STEM + math education initiative for K-12 schools","STEM / Science and Math Education","$10,000-$100,000","Annual","https://www.honeywell.com","https://www.honeywell.com/us/en/social-impact","Industrial/defense/aerospace; K-12 STEM; Charlotte NC; accessible for school programs","GOOD"),
    ("Raytheon MathMovesU","National","Corporate Program (Defense)","Raytheon funds MathMovesU STEM + math education programs","MathMovesU / STEM Outreach","$10,000-$100,000","Annual","https://www.rtx.com/raytheon","https://www.rtx.com/raytheon/who-we-are/community","RTX division; math + STEM outreach; accessible for schools; major defense STEM funder","GOOD"),
    ("Weingart Foundation","Regional","Private Foundation (SoCal)","Weingart Foundation funds nonprofits in Southern California communities","Community / Education Grants","$25,000-$300,000","Annual","https://www.weingartfnd.org","https://www.weingartfnd.org/Grants","SoCal community foundation; education + nonprofits; Los Angeles; accessible programs","GOOD"),
]

with open(output_file, 'a', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerows(entries)

with open(output_file, encoding='utf-8-sig') as f:
    total = sum(1 for _ in f) - 1
print(f"Batch 14 complete: {len(entries)} new entries appended")
print(f"GRAND TOTAL: {total} entries")
