#!/usr/bin/env python3
# Batch 2: National Aerospace / Defense / Space companies
# APPENDS to existing CSV

import csv

OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
("SAIC Foundation","National","Corporate (Aerospace/Defense)","Science Applications International Corporation; major defense IT contractor; funds STEM education and JROTC-aligned programs; workforce pipeline","STEM and Workforce Education Grants","$5,000-$100,000","Annual","https://www.saic.com","https://www.saic.com/who-we-are/corporate-responsibility","Defense IT contractor; STEM education and workforce development; JROTC alignment through defense mission","GOOD"),
("Leidos Foundation","National","Corporate (Aerospace/Defense)","Defense and health IT company; funds STEM education and veteran programs; STEM workforce pipeline","STEM Education and Veterans Grants","$5,000-$100,000","Annual","https://www.leidos.com","https://www.leidos.com/company/citizenship","Defense technology; STEM education funding; military and veterans focus aligns with JROTC","GOOD"),
("Booz Allen Hamilton Foundation","National","Corporate (Aerospace/Defense)","Major defense consulting firm; funds STEM education and cybersecurity programs for youth; JROTC demographic overlap","STEM and Cybersecurity Education","$10,000-$250,000","Annual","https://www.boozallen.com","https://www.boozallen.com/about/social-impact.html","Defense consulting; STEM education and cyber security for youth; JROTC demographic overlap strong","GOOD"),
("Aerojet Rocketdyne Foundation","National","Corporate (Aerospace/Defense)","Rocket and propulsion manufacturer; funds STEM education near facilities; aerospace engineering pipeline; military programs","STEM Aerospace Education Grants","$5,000-$100,000","Annual","https://www.l3harris.com","https://www.l3harris.com/","Propulsion and aerospace engineering; STEM education pipeline; military contractor alignment with JROTC","GOOD"),
("Sierra Nevada Corporation Foundation","National","Corporate (Aerospace/Defense)","Aerospace and defense company; Dream Chaser spacecraft; funds STEM education and aerospace programs","Aerospace STEM Education","$5,000-$50,000","Annual","https://www.sncorp.com","https://www.sncorp.com/about-snc/community/","Aerospace and defense contractor; Dream Chaser spacecraft inspiration for cadets; STEM education grants","GOOD"),
("Mercury Systems Foundation","National","Corporate (Aerospace/Defense)","Defense electronics; funds STEM education and engineering programs for youth; processing and sensor systems","STEM Engineering Grants","$5,000-$50,000","Annual","https://www.mrcy.com","https://www.mrcy.com/company/corporate-responsibility/","Defense electronics; STEM engineering education; military application aligns with JROTC","MEDIUM"),
("Viasat Foundation","National","Corporate (Aerospace/Defense/Telecom)","Satellite communications company; funds STEM education and digital access programs; Internet for communities","STEM and Digital Access Grants","$5,000-$100,000","Annual","https://www.viasat.com","https://www.viasat.com/about/corporate-responsibility/","Satellite communications; STEM education and digital access; connects to robotics and engineering","MEDIUM"),
("Kratos Defense Foundation","National","Corporate (Aerospace/Defense)","Drone and unmanned systems company; STEM education aligned with UAV technology; robotics-adjacent","STEM and Unmanned Systems Education","$5,000-$50,000","Annual","https://www.kratosdefense.com","https://www.kratosdefense.com/about/community/","Drone and unmanned systems; directly aligned with robotics and autonomous vehicle programs","GOOD"),
("FLIR / Teledyne Technologies Foundation","National","Corporate (Aerospace/Defense)","Thermal imaging and sensing technology; funds STEM and engineering education; defense technology pipeline","STEM Technology Education","$5,000-$50,000","Annual","https://www.flir.com","https://www.flir.com/about-flir/corporate-citizenship/","Thermal imaging and sensing; STEM engineering education; technology pipeline for defense careers","MEDIUM"),
("Leonardo DRS Foundation","National","Corporate (Aerospace/Defense)","Italian defense company US subsidiary; defense electronics; funds STEM education for youth near facilities","STEM Defense Education","$5,000-$50,000","Annual","https://www.leonardodrs.com","https://www.leonardodrs.com/about/community/","Defense electronics contractor; STEM education for youth; military technology pipeline","MEDIUM"),
("Elbit Systems of America","National","Corporate (Aerospace/Defense)","Israeli defense company US operations; funds STEM education and youth programs near US facilities","STEM and Defense Education","$5,000-$50,000","Annual","https://www.elbitsystems.com","https://www.elbitsystems.com/about/corporate-social-responsibility/","Defense technology contractor; STEM education programs; military application aligns with JROTC","MEDIUM"),
("Woodward Inc Foundation","National","Corporate (Aerospace/Defense)","Fuel management systems for aerospace and defense; funds STEM education and engineering programs in communities near facilities","STEM Engineering Grants","$5,000-$50,000","Annual","https://www.woodward.com","https://www.woodward.com/about-us/corporate-responsibility","Aerospace and defense systems; engineering STEM; community grants near Woodward facilities","MEDIUM"),
("Ducommun Foundation","National","Corporate (Aerospace/Defense)","Structural systems and electronic components for aerospace/defense; CA-based (Gardena); funds STEM education near facilities","STEM Aerospace Education","$5,000-$50,000","Annual","https://www.ducommun.com","https://www.ducommun.com/about/community","CA-based aerospace manufacturer (Gardena near Fullerton); community grants for STEM education","GOOD"),
("TransDigm Group Foundation","National","Corporate (Aerospace)","Aerospace components manufacturer; funds STEM education and engineering programs","STEM Engineering Education","$5,000-$50,000","Annual","https://www.transdigm.com","https://www.transdigm.com/responsibility/","Aerospace components; engineering STEM education; career pipeline to aerospace engineering","MEDIUM"),
("Spirit AeroSystems Foundation","National","Corporate (Aerospace)","Major commercial aircraft structures manufacturer; funds STEM education in communities near facilities","STEM Aerospace Education","$5,000-$100,000","Annual","https://www.spiritaero.com","https://www.spiritaero.com/about-spirit/citizenship/","Commercial aerospace manufacturer; STEM education near facilities; engineering career pipeline","MEDIUM"),
("Triumph Group Foundation","National","Corporate (Aerospace)","Aerospace systems and components; funds STEM education and workforce programs near facilities","STEM and Workforce Grants","$5,000-$50,000","Annual","https://www.triumphgroup.com","https://www.triumphgroup.com/citizenship/","Aerospace systems; STEM education; workforce pipeline to aerospace careers","MEDIUM"),
("StandardAero Foundation","National","Corporate (Aerospace)","Aircraft engine maintenance and overhaul; STEM and technical education pipeline","STEM Technical Education","$5,000-$50,000","Annual","https://www.standardaero.com","https://www.standardaero.com/about/community","Aircraft engine maintenance; technical STEM education; aviation career pipeline aligned with JROTC","MEDIUM"),
("Day and Zimmermann Foundation","National","Corporate (Aerospace/Defense)","Defense munitions and staffing; funds community and STEM programs; JROTC-aligned military mission","Community and STEM Grants","$5,000-$50,000","Annual","https://www.dayzim.com","https://www.dayzim.com/about/corporate-responsibility","Defense munitions contractor; STEM and community programs; military mission aligns with JROTC","MEDIUM"),
("Southwest Research Institute Education","National","Research (Nonprofit)","Nonprofit applied research organization (San Antonio TX); operates STEM education outreach programs; science and engineering focus","STEM Education Outreach","$5,000-$50,000","Rolling","https://www.swri.org","https://www.swri.org/corporate/community/education","Nonprofit applied research; engineering STEM outreach; science and technology pipeline","MEDIUM"),
("Battelle Memorial Institute","National","Research (Nonprofit)","Largest nonprofit research and development organization; manages national laboratories; STEM education programs","STEM Education Grants","$10,000-$100,000","Annual","https://www.battelle.org","https://www.battelle.org/about/responsibility","Manages DOE national labs; STEM education and research pipeline; scientific workforce development","GOOD"),
("MITRE Corporation Education","National","Research (Nonprofit)","Nonprofit that manages FFRDCs (federally funded research centers); funds STEM education and cybersecurity programs","STEM and Cyber Education","$5,000-$100,000","Annual","https://www.mitre.org","https://www.mitre.org/our-impact/community","Operates FFRDCs; STEM education programs; cybersecurity and defense technology aligns with JROTC","GOOD"),
("RAND Corporation Education Programs","National","Research (Nonprofit)","Nonprofit global policy research; funds STEM education research and programs; policy-driven STEM investment","STEM Education Research Grants","$10,000-$250,000","Annual","https://www.rand.org","https://www.rand.org/about/community.html","Education policy research; STEM programs; connects well to JROTC and military STEM pipeline","MEDIUM"),
("SRI International Education","National","Research (Nonprofit)","Formerly Stanford Research Institute; independent nonprofit R&D; funds STEM education and innovation programs","STEM Innovation Education","$10,000-$100,000","Annual","https://www.sri.com","https://www.sri.com/about/community/","Innovation and STEM research; education programs for youth; science and engineering pipeline","GOOD"),
("Charles Stark Draper Laboratory","National","Research (Nonprofit)","Cambridge MA nonprofit research center for defense and aerospace; STEM education programs and scholarships for youth","STEM Defense Education","$5,000-$50,000","Annual","https://www.draper.com","https://www.draper.com/about/corporate-responsibility","Defense aerospace research; STEM scholarship programs for youth; engineering career pipeline","GOOD"),
("Institute for Defense Analyses (IDA)","National","Research (Nonprofit)","Nonprofit FFRDC providing analysis to DoD; STEM education outreach for youth interested in defense careers","STEM Defense Analysis Education","$5,000-$50,000","Annual","https://www.ida.org","https://www.ida.org/about/community","DoD-aligned nonprofit; STEM education for youth; defense career pipeline aligns with JROTC","MEDIUM"),
# Space companies
("SpaceX Foundation","National","Corporate (Space)","Elon Musk aerospace company in Hawthorne CA (near Fullerton); occasional STEM event sponsorship; aspirational brand for cadets interested in aerospace careers","SpaceX Community Outreach","Varies - no formal program","Contact directly","https://www.spacex.com","https://www.spacex.com/","No formal grant program; pursue as corporate sponsor or for cadet site visits; 30 miles from Fullerton","MEDIUM"),
("Blue Origin Foundation","National","Corporate (Space)","Jeff Bezos space company; Club for the Future program sends postcards to space; STEM education pipeline for youth; national programs","Club for the Future / STEM Education","In-kind; education kits","Rolling","https://www.blueorigin.com","https://www.clubforthefuture.org/","Club for the Future educational program for youth; STEM pipeline; inspirational for robotics cadets","MEDIUM"),
("Rocket Lab Education","National","Corporate (Space)","Small satellite launch company; STEM education programs; aerospace engineering pipeline for youth","STEM Aerospace Education","$1,000-$10,000","Annual","https://www.rocketlabusa.com","https://www.rocketlabusa.com/about/community/","Satellite launch company; STEM education programs; aerospace engineering career pipeline","MEDIUM"),
("Planet Labs Foundation","National","Corporate (Space)","Earth observation satellite company; STEM education and geospatial data programs for youth","STEM Earth Observation Education","$1,000-$10,000","Annual","https://www.planet.com","https://www.planet.com/company/social-impact/","Earth observation satellites; geospatial STEM education; unique data for robotics navigation projects","MEDIUM"),
("Maxar Technologies Foundation","National","Corporate (Space)","Satellite imagery and space technology company; funds STEM education and geospatial programs","STEM Space Technology","$5,000-$50,000","Annual","https://www.maxar.com","https://www.maxar.com/company/social-impact","Satellite imagery; STEM education; geospatial technology relevant to robotics navigation and mapping","MEDIUM"),
("Relativity Space Foundation","National","Corporate (Space)","3D-printed rocket company (Long Beach CA - near Fullerton); STEM education and additive manufacturing programs","STEM 3D Printing/Manufacturing Education","$5,000-$25,000","Annual","https://www.relativityspace.com","https://www.relativityspace.com/community","Long Beach CA near Fullerton; 3D printing and additive manufacturing STEM; robotics fabrication overlap","GOOD"),
("Intuitive Machines Foundation","National","Corporate (Space)","NASA lunar lander company; STEM education programs and space exploration engagement for youth","STEM Space Education","$1,000-$10,000","Annual","https://www.intuitivemachines.com","https://www.intuitivemachines.com/about/community","NASA lunar program contractor; STEM space education; inspirational for aerospace-interested cadets","MEDIUM"),
("Aerospace Industries Association (AIA) Foundation","National","Industry Association","Trade association for US aerospace and defense; funds STEM education and workforce programs for the industry pipeline","STEM Workforce Grants","$5,000-$50,000","Annual","https://www.aia-aerospace.org","https://www.aia-aerospace.org/our-work/stem/","Industry-wide STEM workforce pipeline; connects to VEX aerospace-interested cadets; grant programs available","GOOD"),
("National Defense Industrial Association (NDIA) Foundation","National","Industry Association","Defense industry trade association; funds STEM education for youth interested in defense careers; STEM scholarship programs","STEM Defense Education","$1,000-$25,000","Annual","https://www.ndia.org","https://www.ndia.org/divisions/divisions/stem-division","Defense industry; STEM scholarships and education for youth; JROTC affiliation directly aligns","GOOD"),
("AFCEA Educational Foundation (STEM)","National","Military-Affiliated","Armed Forces Communications and Electronics Association; funds STEM scholarships for youth pursuing IT and electronics careers","STEM Scholarships and Grants","$1,000-$25,000","Annual","https://www.afcea.org","https://www.afcea.org/signal-media/foundation/scholarships-and-grants","IT and electronics STEM; JROTC affiliation relevant; local San Diego chapter active in SoCal","GOOD"),
("Lockheed Martin Foundation (Broader Programs)","National","Corporate (Aerospace/Defense)","Additional Lockheed Martin foundation programs beyond STEM outreach; engineering scholarships and community investment","Engineering Scholarships / Community Investment","$5,000-$100,000","Annual","https://www.lockheedmartin.com","https://www.lockheedmartin.com/en-us/who-we-are/communities/applying-for-contributions.html","Broader foundation programs; engineering scholarships for cadets entering college; community investment","GOOD"),
("Northrop Grumman Employee Volunteer Grants","National","Corporate (Aerospace/Defense)","NG employees who volunteer 40+ hours unlock $500 volunteer grants; additional funding through employee-led initiatives","Employee Volunteer Grants","$500 per employee volunteer","Rolling - employee triggered","https://www.northropgrumman.com","https://www.northropgrumman.com/corporate-responsibility/corporate-citizenship/resources","Seek NG employees willing to volunteer 40+ hours with TroyVEX; each volunteer unlocks a $500 grant","GOOD"),
("RTX Employee Volunteer Matching","National","Corporate (Aerospace/Defense)","RTX employees who volunteer time with nonprofits trigger matching grants; Fullerton facility employees are ideal champions","RTX Volunteer Matching Grants","$500-$5,000 per employee","Rolling - employee triggered","https://www.rtx.com","https://www.rtx.com/our-responsibility/corporate-responsibility/partners","Fullerton RTX employees; volunteer and match grants; JROTC-friendly corporation","GOOD"),
("Boeing Employee Gift Match","National","Corporate (Aerospace/Defense)","Boeing employees can match their personal donations to nonprofits; $5 for $1 match up to $10K per employee per year","Employee Gift Match Program","Up to $10,000 per employee per year","Rolling - employee triggered","https://www.boeing.com","https://www.boeing.com/company/community-engagement","Seek Boeing employees in SoCal willing to donate; each $2K donation becomes $10K with match","GOOD"),
("General Dynamics Employee Giving","National","Corporate (Aerospace/Defense)","GD employees can trigger community investment grants through volunteer programs; military-affiliated employer","Employee Volunteer and Giving Grants","$500-$5,000 per employee","Rolling","https://www.gd.com","https://www.gd.com/our-commitment/community","Defense contractor; employee-triggered grants; military employment aligns with JROTC parents/mentors","GOOD"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 2 complete: {len(ENTRIES)} new entries appended")
