#!/usr/bin/env python3
# Batch 6: Government agencies, Military organizations, STEM societies, Professional engineering orgs

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Government
("DARPA Education Outreach","National","Government (Federal)","DARPA funds cutting-edge STEM and robotics youth pipeline programs; Mentor Apprentice Program; defense research agency","STEM Robotics Pipeline / Mentor Apprentice Program","Varies","Rolling/Invitation","https://www.darpa.mil","https://www.darpa.mil/about-us/contact","Defense robotics funding; military NJROTC connection strong; robotics competitions aligned with DARPA mission","GOOD"),
("DoD STEM Office (dodSTEM.us)","National","Government (Federal)","DoD STEM Office coordinates all service branch STEM education; JROTC robotics grants centrally coordinated; direct military connection","DoD STEM Grants / JROTC Programs","$1,000-$50,000","Annual - check dodSTEM.us","https://dodstem.us","https://dodstem.us/","HIGH PRIORITY | JROTC SPECIFIC | Coordinates Army Navy Air Force JROTC STEM funding; apply through dodSTEM.us","GOOD"),
("US Army Research Laboratory Education","National","Government (Military)","Army Research Lab funds STEM education programs; STEM apprentice programs for youth; Army JROTC support","Army STEM Education Apprenticeships","$5,000-$50,000","Annual","https://www.arl.army.mil","https://www.arl.army.mil/business/educational-outreach/","Army STEM education; youth apprenticeships; JROTC affiliation directly relevant to Army branch","GOOD"),
("Air Force Research Laboratory Education","National","Government (Military)","AFRL funds STEM education and aerospace research programs; youth STEM pipeline for Air Force careers","AFRL STEM Pipeline Programs","$5,000-$50,000","Annual","https://afresearchlab.com","https://afresearchlab.com/education/","Air Force STEM education; aerospace pipeline; NJROTC cadets pursuing aerospace careers","GOOD"),
("US Space Force STEM Education","National","Government (Military)","Space Force funds STEM education and space career pipeline for youth; newest military branch","Space Force STEM Programs","$5,000-$50,000","Annual","https://www.spaceforce.mil","https://www.spaceforce.mil/","Space career pipeline; newest military branch; aerospace and technology STEM education","GOOD"),
("Department of Education STEM Grants","National","Government (Federal)","US Department of Education funds STEM education through multiple grant programs; Title I and IDEA eligible schools","Federal STEM Education Grants","$25,000-$500,000","Annual RFP","https://www.ed.gov","https://www.ed.gov/fund/grant/apply/appbase/step1.html","Federal STEM grants; public school eligibility; Troy High School may qualify through district","MEDIUM"),
("21st Century Community Learning Centers","National","Government (Federal)","Federal afterschool program that funds STEM and enrichment activities; school district or nonprofit applies","21st CCLC Afterschool STEM","$50,000-$500,000","Annual RFP through state","https://www.ed.gov/21stcclc","https://www.ed.gov/21stcclc","Afterschool STEM enrichment; public school district applies; best through FJUHSD administration","MEDIUM"),
("NSA STEM Education Programs","National","Government (Federal)","NSA funds STEM education and cybersecurity career pipeline; GenCyber summer camps and grants","GenCyber / STEM Education","$5,000-$50,000","Annual","https://www.nsa.gov/What-We-Do/Research/Math-Programs/","https://www.nsa.gov/","Cybersecurity and mathematics STEM education; military intelligence alignment with JROTC","GOOD"),
("DHS STEM Education Programs","National","Government (Federal)","Department of Homeland Security funds STEM education for youth interested in security careers; HS/STEM","DHS STEM Education / HS-STEM","$5,000-$50,000","Annual","https://www.dhs.gov","https://www.dhs.gov/science-and-technology/hs-stem","Security career pipeline; STEM education for youth; border and cybersecurity focus aligns with JROTC","GOOD"),
("NIST Manufacturing Extension Partnership","National","Government (Federal)","NIST MEP funds manufacturing STEM education and workforce; robotics and advanced manufacturing focus","MEP Advanced Manufacturing STEM","$10,000-$100,000","Annual RFP","https://www.nist.gov/mep","https://www.nist.gov/mep","Advanced manufacturing and robotics STEM; workforce pipeline; national network of MEP centers","GOOD"),
("Argonne National Laboratory Education","National","Government/Research","DOE national lab; STEM education outreach programs for K-12 youth; robotics and materials science","STEM Education Outreach","$5,000-$25,000","Annual","https://www.anl.gov","https://www.anl.gov/education","DOE national lab; K-12 STEM outreach; robotics and materials science programs","MEDIUM"),
("Lawrence Berkeley National Laboratory Education","State","Government/Research","UC-managed DOE lab in Berkeley CA; funds STEM education and research pipeline for CA youth","STEM Education Programs","$5,000-$25,000","Annual","https://www.lbl.gov","https://education.lbl.gov/","CA-based DOE national lab; STEM education for CA youth; Berkeley CA HQ","GOOD"),
("Lawrence Livermore National Laboratory Education","State","Government/Research","LLNL in Livermore CA; funds STEM education and science pipeline for CA youth; national security research","STEM National Security Education","$5,000-$25,000","Annual","https://www.llnl.gov","https://education.llnl.gov/","CA national lab; national security STEM; aligns with JROTC mission; CA youth programs","GOOD"),
("Sandia National Laboratories Education","National","Government/Research","Sandia manages nuclear stockpile; funds STEM education near facilities; defense research pipeline","STEM Defense Research Education","$5,000-$25,000","Annual","https://www.sandia.gov","https://www.sandia.gov/education/","Defense research; STEM education; Albuquerque NM HQ with CA operations in Livermore","GOOD"),
("Los Alamos National Laboratory Education","National","Government/Research","LANL funds STEM education for youth in national security and physics; New Mexico HQ","STEM Physics and National Security","$5,000-$25,000","Annual","https://www.lanl.gov","https://www.lanl.gov/community/education.php","National security STEM; physics and engineering education; JROTC alignment through defense mission","MEDIUM"),
("Jet Propulsion Laboratory Education (NASA/Caltech)","State","Government/Research","JPL in Pasadena CA (near Fullerton); NASA/Caltech facility; extensive K-12 STEM outreach programs for SoCal youth","JPL Education STEM Outreach","$5,000-$25,000","Annual; educator workshops rolling","https://www.jpl.nasa.gov/edu","https://www.jpl.nasa.gov/edu","HIGH PRIORITY | Pasadena CA near Fullerton; NASA's premier robotic spacecraft lab; SoCal youth STEM programs","GOOD"),
("National Renewable Energy Laboratory Education","National","Government/Research","NREL funds clean energy and STEM education; renewable energy technology pipeline","STEM Clean Energy Education","$5,000-$25,000","Annual","https://www.nrel.gov","https://www.nrel.gov/education/","Clean energy STEM; technology pipeline for youth; Golden CO HQ with national programs","MEDIUM"),
("Pacific Northwest National Laboratory Education","National","Government/Research","PNNL funds STEM education and science pipeline; energy and environment research","STEM Science Education","$5,000-$25,000","Annual","https://www.pnnl.gov","https://www.pnnl.gov/education","Energy and environment STEM; science pipeline; Richland WA HQ","MEDIUM"),
("Battelle Education (National Labs Management)","National","Government/Research","Battelle manages multiple national labs; STEM education through managed lab outreach programs","STEM National Lab Outreach","$5,000-$50,000","Annual","https://www.battelle.org","https://www.battelle.org/education/","National lab manager; STEM education through managed lab programs; Columbus OH HQ","MEDIUM"),
("SRI International Education Programs","National","Research (Nonprofit)","SRI International (Stanford Research Institute) funds STEM education and innovation; Menlo Park CA HQ","STEM Innovation Education","$10,000-$100,000","Annual","https://www.sri.com","https://www.sri.com/about/community/","Menlo Park CA HQ; STEM innovation education; research pipeline for youth","GOOD"),
# Military Organizations
("Marine Corps Scholarship Foundation","National","Military-Affiliated Foundation","Funds college scholarships for Marine Corps and Navy children; JROTC cadets pursuing college","Marine Corps Scholarship","$10,000/yr renewable","Annual","https://www.mcsf.org","https://www.mcsf.org/apply/","Scholarship for children of Marines; Navy/Marine JROTC cadets eligible; APPLY NOW for college-bound cadets","GOOD"),
("Military Officers Association of America (MOAA)","National","Military-Affiliated Foundation","MOAA funds scholarships and programs for military dependents; education and career support","MOAA Education Grants / Scholarships","$1,000-$5,000","Annual","https://www.moaa.org","https://www.moaa.org/scholarships/","Military dependent scholarships; JROTC cadets and children of officers qualify; national programs","GOOD"),
("Reserve Officers Association","National","Military-Affiliated Foundation","ROA funds education and programs for reserve component youth; JROTC support","ROA Education Programs","$500-$5,000","Annual","https://www.roa.org","https://www.roa.org/","Reserve component youth; JROTC education support; national programs","MEDIUM"),
("National Guard Association Educational Foundation","National","Military-Affiliated Foundation","Funds education programs for National Guard members and dependents; STEM and leadership","STEM Leadership Education","$500-$5,000","Annual","https://www.ngaus.org","https://www.ngaus.org/content/scholarship","National Guard association; education and STEM programs; cadets with Guard family connections","MEDIUM"),
("Non-Commissioned Officers Association (NCOA)","National","Military-Affiliated Foundation","Funds scholarships and programs for enlisted military and their families; education focus","NCOA Scholarships / Education","$500-$2,000","Annual","https://www.ncoausa.org","https://www.ncoausa.org/grants-scholarships","Enlisted military families; scholarships for dependents; JROTC cadets from enlisted families qualify","MEDIUM"),
("Fleet Reserve Association","National","Military-Affiliated Foundation","Funds scholarships and programs for Navy Marine Corps and Coast Guard families; sea service focus","FRA Scholarships / Education","$500-$5,000","Annual","https://www.fra.org","https://www.fra.org/fra/Web/Sections/Scholarship/Web/Sections/Scholarship/FRAScholarship.aspx","Sea service scholarships; NJROTC cadets from Navy families directly eligible; Scholarships annually","GOOD"),
("Air Force Association Scholarship","National","Military-Affiliated Foundation","AFA funds scholarships for JROTC cadets pursuing STEM; Air Force ROTC scholarship support","AFA STEM Scholarships / JROTC","$500-$10,000","Annual","https://www.afa.org","https://www.afa.org/afa-foundation/scholarships/","JROTC cadet scholarships; STEM focus; Air Force affiliated; annual scholarships for high school seniors","GOOD"),
("Special Operations Forces Foundation","National","Military-Affiliated Foundation","Funds education and programs for SOF personnel and families; elite military community","SOF Education and Grants","$1,000-$10,000","Annual","https://www.sof-foundation.org","https://www.sof-foundation.org/","Elite military community; education grants; JROTC cadets aspiring to SOF careers","MEDIUM"),
("Military Child Education Coalition","National","Military-Affiliated Foundation","Funds education programs specifically for military children; MCEC grants for schools serving military students","MCEC Education Grants","$5,000-$50,000","Annual","https://www.militarychild.org","https://www.militarychild.org/contact-us","Military children education specifically; JROTC programs directly eligible; national programs","GOOD"),
("Operation Homefront","National","Military-Affiliated Foundation","Funds family support and education for military families; Back-to-School program","Back-to-School / Family Education","$500-$5,000","Annual","https://www.operationhomefront.org","https://www.operationhomefront.org/programs","Military family support; education programs; Back-to-School assistance for military children","MEDIUM"),
("Blue Star Families","National","Military-Affiliated Foundation","Funds programs for military families including education and youth development; community connections","Education and Youth Programs","$5,000-$50,000","Annual","https://www.bluestarfam.org","https://www.bluestarfam.org/","Military family programs; youth development and education; JROTC families directly eligible","GOOD"),
("USO (United Service Organizations)","National","Military-Affiliated Foundation","USO funds programs supporting military and families; education and entertainment for military youth","Military Youth and Education Programs","$5,000-$50,000","Annual","https://www.uso.org","https://www.uso.org/","Military support organization; youth and education programs; JROTC cadets and military families","MEDIUM"),
# Professional Engineering Societies
("ASME Foundation","National","Professional Society (Engineering)","American Society of Mechanical Engineers; funds STEM education and mechanical engineering scholarships; K-12 outreach","STEM Engineering Scholarships / K-12","$1,000-$25,000","Annual","https://www.asme.org","https://www.asme.org/about-asme/engineering-for-change/donations","Mechanical engineering STEM; K-12 outreach programs; scholarships for students entering engineering","GOOD"),
("IEEE Foundation","National","Professional Society (Engineering)","Institute of Electrical and Electronics Engineers; funds STEM education and electrical engineering pipeline","IEEE Educational Activities / STEM","$1,000-$25,000","Annual","https://www.ieee.org","https://ieefoundation.org/","Electrical and electronics engineering STEM; TryEngineering program for K-12; scholarships","GOOD"),
("SAE International Foundation","National","Professional Society (Engineering)","Society of Automotive Engineers; funds STEM and automotive/aerospace engineering; A World in Motion program","A World in Motion / STEM","$1,000-$25,000","Annual","https://www.sae.org","https://www.saeaef.org/","Automotive and aerospace engineering STEM; A World in Motion K-12 program; competition teams supported","GOOD"),
("AIAA Foundation","National","Professional Society (Engineering)","American Institute of Aeronautics and Astronautics; funds aerospace engineering education and scholarships for youth","Aerospace Engineering Scholarships / STEM","$1,000-$10,000","Annual","https://www.aiaa.org","https://www.aiaa.org/about/AIAA-Foundation","Aerospace engineering STEM; scholarships for youth; JROTC aerospace career pipeline","GOOD"),
("ASCE Foundation","National","Professional Society (Engineering)","American Society of Civil Engineers; funds civil engineering education and scholarships; infrastructure STEM","Civil Engineering STEM / Scholarships","$1,000-$10,000","Annual","https://www.asce.org","https://www.ascefoundation.org/","Civil and infrastructure engineering STEM; scholarships; construction and robotics manufacturing overlap","MEDIUM"),
("AIChE Foundation","National","Professional Society (Engineering)","American Institute of Chemical Engineers; funds chemical engineering education and scholarships; STEM pipeline","Chemical Engineering STEM","$1,000-$10,000","Annual","https://www.aiche.org","https://www.aiche.org/community/aiche-foundation","Chemical engineering STEM; scholarships; science pipeline for youth interested in chemistry and biology","MEDIUM"),
("Society of Manufacturing Engineers Foundation","National","Professional Society (Engineering)","SME funds manufacturing STEM education and scholarships; fabrication and production technology","Manufacturing STEM / Scholarships","$1,000-$25,000","Annual","https://www.sme.org","https://www.sme.org/education/","Manufacturing engineering STEM; fabrication technology; robotics manufacturing directly relevant","GOOD"),
("ASM International Foundation","National","Professional Society (Engineering)","American Society for Metals; funds materials science STEM and scholarships for youth","Materials Science STEM","$1,000-$10,000","Annual","https://www.asminternational.org","https://www.asminternational.org/education","Materials science STEM; scholarships; materials relevant to robot construction and design","MEDIUM"),
("ASHRAE Foundation","National","Professional Society (Engineering)","ASHRAE funds HVAC and building systems engineering STEM; scholarships and K-12 education","Building Systems Engineering STEM","$1,000-$10,000","Annual","https://www.ashrae.org","https://www.ashrae.org/about/ashrae-foundation","HVAC and building engineering STEM; not direct robotics fit but engineering pipeline","MEDIUM"),
("American Nuclear Society Foundation","National","Professional Society (Engineering)","ANS funds nuclear science and engineering education; scholarships for youth interested in nuclear energy","Nuclear Engineering STEM","$1,000-$10,000","Annual","https://www.ans.org","https://www.ans.org/education/scholarships/","Nuclear engineering STEM; scholarships; energy and defense pipeline aligns with JROTC","MEDIUM"),
("American Chemical Society Foundation","National","Professional Society (Science)","ACS funds chemistry education and scholarships; Hach grants for high school chemistry teachers","Hach Grants / Chemistry STEM","$1,500-$3,000 (Hach)","Annual","https://www.acs.org","https://www.acs.org/content/acs/en/funding.html","Hach grants for HS chemistry teachers (no 501c3 needed); chemistry STEM pipeline; national programs","GOOD"),
("Society of Naval Architects and Marine Engineers","National","Professional Society (Engineering)","SNAME funds naval architecture and marine engineering education; sea service STEM pipeline","Naval Architecture STEM","$1,000-$10,000","Annual","https://www.sname.org","https://www.sname.org/education/scholarships","Sea service engineering STEM; NJROTC directly relevant to naval architecture career pipeline","GOOD"),
("Tau Beta Pi Engineering Honor Society","National","Professional Society (Engineering)","Tau Beta Pi funds engineering STEM scholarships and K-12 outreach; largest engineering honor society","Engineering Scholarships / K-12 Outreach","$500-$5,000","Annual","https://www.tbp.org","https://www.tbp.org/info/scholar.cfm","Engineering scholarships for high-achieving students; K-12 STEM outreach events; college chapter partnerships","GOOD"),
("National Action Council for Minorities in Engineering","National","Professional Society (STEM)","NACME funds engineering education for underrepresented minorities; scholarship and career programs","Minority Engineering Scholarships","$2,500-$5,000","Annual","https://www.nacme.org","https://www.nacme.org/scholarships","Underrepresented minorities in engineering; scholarships and career programs; JROTC demographic overlap","GOOD"),
("Computing Research Association Education","National","Professional Society (CS)","CRA funds CS research education and equity programs; government relations for CS education funding","CS Research Education Grants","$5,000-$50,000","Annual","https://cra.org","https://cra.org/about/giving/","CS research education; equity in computing programs; pipeline to computer science careers","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 6 complete: {len(ENTRIES)} new entries appended")
