import csv, os

output_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'troyvex_donor_list.csv')

entries = [
    # ---- LOCAL OC CULTURAL/EDUCATION (missed) ----
    ("Bowers Museum Foundation","Local","Cultural Institution (OC)","Bowers Museum (Santa Ana CA, OC) STEM + science education programs","STEM / Cultural Education Grants","$5,000-$25,000","Annual","https://www.bowers.org","https://www.bowers.org/index.php/education/","Santa Ana CA (OC!); STEM + cultural education; accessible for OC school programs","GOOD"),
    ("Muzeo Foundation (Anaheim)","Local","Cultural Institution (Adjacent)","Muzeo (Anaheim CA, adjacent to Fullerton) community education programs","Community / STEM Education","$1,000-$10,000","Annual","https://muzeo.org","https://muzeo.org","Anaheim CA adjacent to Fullerton; community education; accessible for local school programs","GOOD"),
    ("Fullerton Arboretum Foundation","Local","Cultural Institution (Fullerton)","Fullerton Arboretum at CSUF campus (adjacent to Troy HS); STEM + nature education","STEM / Nature Education Grants","$1,000-$10,000","Annual","https://fullertonarboretum.org","https://fullertonarboretum.org","Adjacent to Troy HS on CSUF campus; STEM + nature; very local; accessible for Troy programs","GOOD"),
    ("Muckenthaler Cultural Center","Local","Cultural Institution (Fullerton)","Muckenthaler Center (Fullerton CA) arts + STEM education programs","Arts / STEM Education","$1,000-$10,000","Annual","https://www.muckross.com","https://www.muckross.com","Fullerton CA; directly in Troy community; arts + STEM education; very accessible local funder","GOOD"),
    ("CKE Restaurants Foundation (Carl's Jr)","Local","Corporate Foundation (Restaurant OC)","CKE Restaurants (Carl's Jr/Hardee's) HQ Franklin TN; OC roots; education programs","Community / Education Grants","$5,000-$25,000","Annual","https://www.ckr.com","https://www.ckr.com","Carl's Jr originally founded in Anaheim CA (OC!); community + education; accessible programs","MEDIUM"),

    # ---- COAST GUARD / SPACE FORCE (missed military) ----
    ("Coast Guard Foundation","National","Military Foundation","Coast Guard Foundation funds education + safety for Coast Guard community","Coast Guard Scholarship / Education","$5,000-$25,000","Annual","https://www.coastguardfoundation.org","https://www.coastguardfoundation.org/scholarships","Coast Guard community; NJROTC-adjacent (naval branch); education scholarships; accessible","GOOD"),
    ("Air Force Space Force Association","National","Military Association Foundation","Space Force Association (SFA) funds aerospace + STEM education","Space STEM / Scholarships","$5,000-$25,000","Annual","https://www.sfa.org","https://www.sfa.org/scholarships","Space Force + Air Force; STEM aerospace; NJROTC-adjacent; accessible scholarships","GOOD"),
    ("Space Force Education Foundation","National","Military Foundation (Space Force)","Space Force Foundation funds STEM + space education for youth","Space STEM Education","$5,000-$50,000","Annual","https://www.spaceforce.edu","https://www.spaceforce.edu","Space Force-affiliated education; STEM + space; accessible for military-adjacent programs","GOOD"),

    # ---- SEMICONDUCTOR EQUIPMENT (missed) ----
    ("Applied Materials Foundation","National","Corporate Foundation (Semiconductor Equip)","Applied Materials (semiconductor manufacturing equipment) STEM education","STEM / Engineering Education","$10,000-$100,000","Annual","https://www.appliedmaterials.com","https://www.appliedmaterials.com/us/en/about/corporate-responsibility.html","Largest semiconductor equipment maker; STEM education; Santa Clara CA HQ; accessible","GOOD"),
    ("Lam Research Foundation","National","Corporate Foundation (Semiconductor Equip)","Lam Research (semiconductor etch/deposition equipment) STEM programs","STEM / Engineering Education","$10,000-$100,000","Annual","https://www.lamresearch.com","https://www.lamresearch.com/corporate-citizenship/","Semiconductor equipment; STEM education; Fremont CA HQ; accessible school programs","GOOD"),
    ("KLA Foundation","National","Corporate Foundation (Semiconductor Equip)","KLA (process control semiconductor equipment) STEM education programs","STEM / Engineering Education","$10,000-$50,000","Annual","https://www.kla.com","https://www.kla.com/about/corporate-responsibility/community","Semiconductor equipment; STEM education; Milpitas CA HQ; accessible school programs","MEDIUM"),
    ("ASML Foundation","National","Corporate Foundation (Semiconductor Equipment)","ASML (EUV lithography machines) STEM education + university programs","STEM / Physics Education","$10,000-$100,000","Annual","https://www.asml.com","https://www.asml.com/en/company/sustainability/community","Dutch company; EUV chip machines; physics + STEM; San Diego CA US office; accessible","MEDIUM"),

    # ---- AEROSPACE PARTS (missed) ----
    ("Heico Corporation Foundation","National","Corporate Foundation (Aerospace Parts)","Heico (aircraft replacement parts) supports STEM + aviation education","Aviation / STEM Education","$5,000-$25,000","Annual","https://www.heico.com","https://www.heico.com/about-heico/citizenship","Aircraft parts maker; aviation + STEM; Hollywood FL HQ; accessible programs","MEDIUM"),
    ("Ducommun Foundation","Regional","Corporate Foundation (Aerospace Parts SoCal)","Ducommun (aerospace structural parts) HQ Gardena CA (SoCal!) STEM programs","STEM / Aerospace Education","$5,000-$25,000","Annual","https://www.ducommun.com","https://www.ducommun.com/sustainability/","Gardena CA (SoCal!) aerospace parts maker; STEM education; very local; excellent fit","GOOD"),
    ("Triumph Group Foundation","National","Corporate Foundation (Aerospace)","Triumph Group (aerospace structures/systems) STEM education","STEM / Aerospace Manufacturing","$5,000-$25,000","Annual","https://www.triumphgroup.com","https://www.triumphgroup.com/company/corporate-citizenship","Aerospace structures; STEM education; Berwyn PA HQ; accessible school programs","MEDIUM"),

    # ---- DATA/AI TECH (missed) ----
    ("Databricks Foundation","National","Corporate Foundation (AI/Data)","Databricks (data + AI platform) funds STEM and data science education","AI / Data Science Education","$10,000-$100,000","Annual","https://www.databricks.com","https://www.databricks.com/company/databricks-foundation","AI data platform; data science + STEM; San Francisco CA HQ; accessible programs","MEDIUM"),
    ("Snowflake Foundation","National","Corporate Foundation (Cloud Data)","Snowflake (cloud data warehouse) funds STEM and data education","Data Science / STEM Education","$10,000-$50,000","Annual","https://www.snowflake.com","https://www.snowflake.com/company/snowflake-impact/","Cloud data; STEM + data science; Bozeman MT/San Mateo CA; accessible programs","MEDIUM"),
    ("Palantir Foundation","National","Corporate Foundation (Defense Data/AI)","Palantir (defense data analytics) supports STEM + national security education","Defense STEM / Data Analytics","$10,000-$100,000","Annual","https://www.palantir.com","https://www.palantir.com/impact/","Defense data + AI; NJROTC-adjacent (military tech); Denver CO HQ; accessible programs","GOOD"),
    ("Stripe Foundation","National","Corporate Foundation (Fintech)","Stripe (online payments) funds economic access and STEM education","Economic Access / STEM","$10,000-$100,000","Annual","https://stripe.com","https://stripe.com/about","Payments company; economic access + STEM; San Francisco CA HQ; accessible programs","MEDIUM"),
    ("Uber Foundation","National","Corporate Foundation (Gig Economy)","Uber Foundation funds mobility + economic opportunity programs","Mobility / Economic Opportunity","$10,000-$100,000","Annual","https://www.uber.com","https://www.uber.com/us/en/community/","Rideshare; economic opportunity; San Francisco CA; not robotics-specific; accessible","BAD"),
    ("DoorDash Foundation","National","Corporate Foundation (Delivery)","DoorDash funds economic opportunity and food access programs","Economic Opportunity Grants","$10,000-$50,000","Annual","https://www.doordash.com","https://www.doordash.com/impact/","Food delivery; economic focus; San Francisco CA; not robotics-specific; wrong fit","BAD"),
    ("Lyft Foundation","National","Corporate Foundation (Rideshare)","Lyft funds transportation access and community programs","Community Transportation Grants","$10,000-$50,000","Annual","https://www.lyft.com","https://www.lyft.com/our-commitments","Rideshare; transportation access; San Francisco CA; not robotics focus; wrong fit","BAD"),

    # ---- ADDITIONAL OC LOCAL BUSINESSES ----
    ("Allergan/AbbVie Foundation (Irvine CA)","Local","Corporate Foundation (Pharma OC)","Allergan (AbbVie subsidiary, Irvine CA OC!) funds STEM + health education","STEM / Healthcare Education","$10,000-$100,000","Annual","https://www.allergan.com","https://www.allergan.com/en-us/corporate-responsibility","Irvine CA (OC!!) major pharma HQ; STEM + health education; very local OC funder; accessible","GOOD"),
    ("Glaukos Corporation Foundation","Local","Corporate Foundation (Medical OC)","Glaukos (Aliso Viejo CA, OC) eye surgery devices; STEM + community","STEM / Healthcare Education","$5,000-$25,000","Annual","https://www.glaukos.com","https://www.glaukos.com/company/social-responsibility/","Aliso Viejo CA (OC!) eye surgery devices; STEM + community; local OC funder; accessible","GOOD"),
    ("Acushnet Foundation (Golf Equipment)","National","Corporate Foundation (Sports Equipment)","Acushnet (Titleist golf) community and education programs","Community / Education Grants","$5,000-$25,000","Annual","https://www.acushnetcompany.com","https://www.acushnetcompany.com/sustainability","Golf equipment; community + education; Fairhaven MA; not robotics-specific; general STEM","MEDIUM"),
    ("First American Financial Foundation","Local","Corporate Foundation (Title Insurance OC)","First American (Santa Ana CA, OC!) title insurance; community + education","Community / Education Grants","$10,000-$100,000","Annual","https://www.firstam.com","https://www.firstam.com/about-us/corporate-social-responsibility/","Santa Ana CA (OC!); large OC-HQ company; community + education; accessible for OC schools","GOOD"),
    ("Ingram Micro Foundation","Local","Corporate Foundation (Tech Distribution OC)","Ingram Micro (Irvine CA, OC!) global tech distributor; STEM + community","STEM / Community Grants","$10,000-$100,000","Annual","https://www.ingrammicro.com","https://www.ingrammicro.com/en-us/our-company/corporate-social-responsibility","Irvine CA (OC!); massive tech distributor; STEM + community; very local OC funder; accessible","GOOD"),
    ("Western Digital Foundation (Irvine CA)","Local","Corporate Foundation (Data Storage OC)","Western Digital (Irvine CA, OC!) HDD/SSD maker; STEM education","STEM / Technology Education","$10,000-$50,000","Annual","https://www.westerndigital.com","https://www.westerndigital.com/company/corporate-responsibility","Irvine CA (OC!) HQ; data storage; STEM education; very local OC funder; excellent fit","GOOD"),
    ("Verizon Fios / Frontier OC","Local","Corporate Program (Telecom OC)","Local OC telecom providers; community investment programs","Community / STEM Grants","$1,000-$10,000","Annual","https://www.frontier.com","https://www.frontier.com/about-us/frontier-foundation","OC telecom service; community investment; accessible for local school programs","MEDIUM"),
    ("OC Supervisors District 4 (Fullerton)","Local","Government (OC Board of Supervisors)","OC 4th District supervisor represents Fullerton; discretionary community funds","Discretionary Community Grants","$1,000-$10,000","Annual","https://bos.ocgov.com","https://bos.ocgov.com/4th-district","4th District OC Supervisor represents Fullerton; discretionary funds for community programs","GOOD"),
    ("Fullerton City Council Grants","Local","Government (City of Fullerton)","City of Fullerton may have community benefit funds for youth programs","City Community Grants","$500-$5,000","Annual","https://www.cityoffullerton.com","https://www.cityoffullerton.com","Troy HS is in Fullerton; city council community benefit discretionary funds; worth inquiring","GOOD"),
]

with open(output_file, 'a', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerows(entries)

with open(output_file, encoding='utf-8-sig') as f:
    total = sum(1 for _ in f) - 1
print(f"Batch 15 complete: {len(entries)} new entries appended")
print(f"GRAND TOTAL: {total} entries")
