import csv, os

output_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'troyvex_donor_list.csv')

entries = [
    # ---- ADDITIONAL TECH COMPANIES WITH KNOWN EDUCATION PROGRAMS ----
    ("Snap Inc. Foundation","Regional","Corporate Foundation (Social Media)","Snap (Snapchat) HQ Santa Monica CA; Yellow fund for youth entrepreneurs","Yellow Fund / Youth Entrepreneur Grants","$10,000-$150,000","Annual","https://www.snap.com/en-US/values/citizenship","https://www.snapfoundation.org","Santa Monica CA (SoCal!); youth + tech entrepreneurship; accessible; OC proximity; strong tech tie-in","GOOD"),
    ("SpaceX Education","National","Corporate Program (Aerospace)","SpaceX (Elon Musk) supports STEM + aerospace education; Hawthorne CA HQ","STEM / Aerospace Education","$10,000-$100,000","Annual","https://www.spacex.com","https://www.spacex.com/human-spaceflight/","Hawthorne CA (SoCal!); rockets + aerospace; STEM education; very relevant; local CA company","GOOD"),
    ("Anduril Industries","Local","Corporate (Defense Technology)","Anduril (defense AI drones) HQ Costa Mesa CA (OC!); STEM + defense programs","STEM / Defense Technology Education","$10,000-$100,000","Annual","https://www.anduril.com","https://www.anduril.com/company/","Costa Mesa CA (OC!!) defense AI company; drones/autonomous systems; very relevant to robotics; local","GOOD"),
    ("Shield AI","Regional","Corporate (Defense AI/Drones)","Shield AI (defense AI for autonomous drones) San Diego CA HQ","STEM / Autonomous Systems Education","$10,000-$50,000","Annual","https://www.shield.ai","https://www.shield.ai/mission/","San Diego CA; autonomous AI systems; drones + robotics; STEM education; SoCal-accessible","GOOD"),
    ("Joby Aviation","National","Corporate (Electric Aircraft)","Joby Aviation (Santa Cruz CA) electric vertical takeoff air taxis","STEM / Aviation Education","$5,000-$50,000","Annual","https://www.jobyaviation.com","https://www.jobyaviation.com/community/","Electric aviation; STEM + aerospace; Santa Cruz CA; accessible programs; robotics-adjacent","GOOD"),
    ("Archer Aviation","National","Corporate (Electric Aircraft)","Archer Aviation (San Jose CA) electric air mobility; STEM programs","STEM / Aerospace Education","$5,000-$25,000","Annual","https://www.archer.com","https://www.archer.com/","Electric air mobility; STEM + aerospace; San Jose CA; accessible programs; engineering focus","GOOD"),
    ("Relativity Space","National","Corporate (3D Printing / Rockets)","Relativity Space (Long Beach CA!) 3D-printed rockets; STEM education","STEM / 3D Printing / Aerospace","$10,000-$50,000","Annual","https://www.relativityspace.com","https://www.relativityspace.com/","Long Beach CA (SoCal!) rocket company; 3D printing + aerospace; STEM education; very local","GOOD"),
    ("Rocket Lab","National","Corporate (Small Rockets/Spacecraft)","Rocket Lab (Long Beach CA!) small satellite launchers; STEM programs","STEM / Space Education","$10,000-$50,000","Annual","https://www.rocketlabusa.com","https://www.rocketlabusa.com/mission-archive/","Long Beach CA (SoCal!) space company; STEM + aerospace; very local; excellent fit for VEX","GOOD"),
    ("Vast Space","National","Corporate (Space Stations)","Vast Space (Long Beach CA!) private space station company; STEM programs","STEM / Space Education","$5,000-$25,000","Annual","https://www.vastspace.com","https://www.vastspace.com/","Long Beach CA (SoCal!) space company; STEM + space; very local; emerging company; accessible","GOOD"),
    ("HRL Laboratories","Local","Corporate (Research Lab OC)","HRL Laboratories (Malibu CA, Boeing/GM JV) advanced research; STEM programs","STEM / Advanced Research Education","$10,000-$50,000","Annual","https://www.hrl.com","https://www.hrl.com/community/","Malibu CA (SoCal!); Boeing/GM research lab; STEM education; very relevant; accessible","GOOD"),

    # ---- ADDITIONAL MILITARY / JROTC PROGRAMS ----
    ("NJROTC Foundation","National","Military Foundation (NJROTC)","National NJROTC Foundation supports NJROTC cadet programs directly","NJROTC Program Support","$5,000-$25,000","Annual","https://www.njrotcfoundation.org","https://www.njrotcfoundation.org","DIRECTLY funds NJROTC programs like Troy's; cadet support; TOP PRIORITY for Troy NJROTC","GOOD"),
    ("Patriot Foundation","National","Military Foundation","Patriot Foundation funds education for children of fallen military","Patriot Scholarships","$10,000-$25,000","Annual","https://www.patriotfoundation.org","https://www.patriotfoundation.org/scholarships/","Military family scholarships; NJROTC-adjacent; education focus; accessible programs","MEDIUM"),
    ("Special Operations Warrior Foundation","National","Military Foundation","SOWF funds college scholarships for children of special operations forces","SOF Scholarships","$5,000+","Annual","https://specialops.org","https://specialops.org/programs/scholarships/","Special operations families; military community; not directly NJROTC but military adjacent","MEDIUM"),
    ("Navy SEAL Foundation","National","Military Foundation","Navy SEAL Foundation supports SEALs and families; education programs","SEAL Education / Community Grants","$10,000-$50,000","Annual","https://www.navysealfoundation.org","https://www.navysealfoundation.org/programs/educational-assistance/","Navy SEAL community; NJROTC-adjacent (Navy focus); education + community; accessible","MEDIUM"),
    ("Wounded Warrior Project Foundation","National","Military Foundation","WWP funds veteran rehabilitation and education programs","Veteran Education / Rehabilitation","$10,000-$100,000","Annual","https://www.woundedwarriorproject.org","https://www.woundedwarriorproject.org/programs","Veteran rehabilitation + education; military community; NJROTC-adjacent; accessible","MEDIUM"),

    # ---- ADDITIONAL ACCESSIBLE NATIONAL FOUNDATIONS ----
    ("Ralph Lauren Foundation","National","Corporate Foundation (Fashion)","Ralph Lauren Corporation funds education + fashion/arts programs","Education / Community Grants","$10,000-$100,000","Annual","https://www.ralphlauren.com/content/rrl/category/us-en/stories-about-us/corporate-responsibility-and-citizenship","https://www.ralphlauren.com/corporate-responsibility","Fashion + education; New York HQ; education programs accessible for school programs","BAD"),
    ("PVH Foundation (Calvin Klein, Tommy Hilfiger)","National","Corporate Foundation (Fashion)","PVH Corp foundation for education + youth development","Education / Youth Development","$10,000-$100,000","Annual","https://www.pvh.com","https://www.pvh.com/pvh-foundation","Fashion company; education + youth; New York HQ; wrong industry fit for robotics","BAD"),
    ("Hasbro Foundation","National","Corporate Foundation (Toys)","Hasbro funds children's education + play programs","Children's Education / Play","$5,000-$50,000","Annual","https://hasbro.com","https://corporate.hasbro.com/en-us/social-responsibility","Toy company; children's education + play; Pawtucket RI; STEM adjacent (toys/games)","MEDIUM"),
    ("LEGO Foundation","National","Corporate Foundation (Toys/Education)","LEGO Foundation funds learning through play and STEM education","Learning Through Play / STEM","$25,000-$500,000","Annual (invitation)","https://www.legogroup.com/en-us/sustainability/lego-foundation","https://www.legogroup.com/en-us/sustainability/lego-foundation","LEGO is robotics-adjacent (LEGO Mindstorms); STEM education; primarily invitation; Denmark HQ","MEDIUM"),
    ("Fisher-Price Foundation","National","Corporate Foundation (Toys)","Fisher-Price (Mattel) funds early STEM education for children","Early STEM / Children's Education","$5,000-$25,000","Annual","https://www.mattel.com","https://www.mattel.com/en-us/corporate-responsibility/society","Toy company (Barbie/Mattel); early childhood STEM; East Aurora NY; accessible programs","MEDIUM"),
    ("Crayola Foundation","National","Corporate Foundation (Arts Supplies)","Crayola funds creative expression and arts education for youth","Arts Education / Creativity Grants","$5,000-$25,000","Annual","https://www.crayola.com","https://www.crayola.com/for-educators/cedp-landing/","Arts + creativity; Easton PA; STEM-adjacent (design thinking); accessible school programs","BAD"),

    # ---- CA STEM SPECIFIC ADDITIONAL ----
    ("Irvine Company Foundation","Local","Corporate Foundation (Real Estate OC)","Irvine Company (largest OC landowner/developer) education + community grants","Education / Community Grants","$25,000-$500,000","Annual","https://www.irvinecompany.com","https://www.irvinecompany.com/corporate-responsibility","Irvine CA (OC!) major developer; education + community; largest OC landowner; excellent fit","GOOD"),
    ("Lennar Foundation","Regional","Corporate Foundation (Homebuilder SoCal)","Lennar (major homebuilder, SoCal presence) community + education grants","Education / Community Grants","$10,000-$100,000","Annual","https://www.lennar.com","https://www.lennar.com/lennar-cares","Major homebuilder; SoCal communities; education + community grants; accessible for schools","MEDIUM"),
    ("KB Home Foundation","Regional","Corporate Foundation (Homebuilder SoCal)","KB Home (Los Angeles HQ!) homebuilder community grants","Education / Community Grants","$5,000-$50,000","Annual","https://www.kbhome.com","https://www.kbhome.com/sustainability","Los Angeles CA HQ (SoCal!); homebuilder; community + education; accessible for SoCal schools","GOOD"),
    ("William Lyon Homes Foundation","Regional","Corporate Foundation (Homebuilder OC)","William Lyon Homes (Newport Beach OC) builder community grants","Community / Education Grants","$5,000-$25,000","Annual","https://www.lyonhomes.com","https://www.lyonhomes.com","Newport Beach CA (OC!) homebuilder; community + education; very local OC funder; accessible","GOOD"),
    ("Sustaining Technology Foundation","National","Foundation (STEM Innovation)","Foundation supporting sustainable technology and STEM innovation","STEM / Sustainable Tech","$10,000-$100,000","Annual","https://www.sustainingtechnology.org","https://www.sustainingtechnology.org","Sustainable technology; STEM + innovation; accessible for school programs; engineering focus","MEDIUM"),
    ("Green Future Foundation","National","Foundation (Environment/STEM)","Green Future Foundation funds sustainability and STEM education","Environmental STEM Grants","$5,000-$50,000","Annual","https://www.greenfuturefoundation.org","https://www.greenfuturefoundation.org","Environmental + STEM; sustainability education; accessible for school programs","MEDIUM"),

    # ---- ADDITIONAL SCHOLARSHIPS AND COMPETITIONS ----
    ("Regeneron ISEF","National","STEM Competition (International Science Fair)","International Science and Engineering Fair; Regeneron sponsored","Science Fair Awards","$500-$75,000","Annual","https://www.societyforscience.org/isef/","https://www.societyforscience.org/isef/","Biggest HS science fair; STEM; engineering projects win; Troy students can compete; individual","GOOD"),
    ("FIRST Robotics Education Foundation","National","Robotics Organization","FIRST (For Inspiration and Recognition of Science and Technology) scholarship programs","FIRST Scholarships + Dean's List","$1,000-$10,000","Annual","https://www.firstinspires.org","https://www.firstinspires.org/ways-to-help/foundation","FIRST robotics scholarships; robotics community; VEX + FIRST overlap; accessible scholarships","GOOD"),
    ("VEX Robotics College Scholarship","National","Robotics Competition (VEX)","VEX Robotics official scholarship program for top competition performers","VEX Competition Scholarships","$1,000-$10,000","Annual","https://www.vexrobotics.com","https://www.roboticseducation.org/scholarships/","VEX DIRECTLY! VEX competition scholarships; Troy VEX cadets directly eligible; top priority","GOOD"),
    ("RECF Grants (Robotics Education and Competition Foundation)","National","Robotics Foundation","RECF (VEX's foundation) funds teams + events; grant applications available","Team Grants / Event Grants","$1,000-$10,000","Annual","https://www.roboticseducation.org","https://www.roboticseducation.org/grants/","RECF is VEX's governing foundation; DIRECTLY relevant; team grants available; apply now","GOOD"),
    ("American Society for Engineering Education (ASEE) Foundation","National","Professional Society Foundation","ASEE funds engineering education programs and outreach","Engineering Education Grants","$5,000-$25,000","Annual","https://www.asee.org","https://www.asee.org/public/pages/resources/ASEE-PreCollege-Engineering-Education-Division","Engineering education society; K-12 outreach programs; accessible for school programs","GOOD"),
    ("National Engineers Week Foundation","National","STEM Organization","DiscoverE (Engineers Week) funds engineering outreach programs","Future City / DiscoverE Outreach","$1,000-$10,000","Annual","https://www.discovere.org","https://www.discovere.org/programs/engineers-week","Engineers Week sponsor; Future City competition; STEM outreach; robotics-adjacent; accessible","GOOD"),
    ("Science Olympiad Foundation","National","STEM Competition Organization","Science Olympiad funds competitions + STEM education programs","Science Olympiad Scholarships + Grants","$1,000-$10,000","Annual","https://www.soinc.org","https://www.soinc.org/about/national-headquarters/science-olympiad-foundation","STEM competition organization; robotics events (Robot Tour, etc.); accessible scholarships","GOOD"),
    ("Conrad Foundation (Spirit of Innovation)","National","STEM Competition (Entrepreneurship)","Conrad Foundation Spirit of Innovation Challenge for STEM entrepreneurs","Innovation Challenge Awards","$5,000-$25,000","Annual","https://www.conradchallenge.org","https://www.conradchallenge.org","STEM entrepreneurship competition; accessible for high school teams; robotics solutions eligible","GOOD"),
    ("Army Educational Outreach Program (AEOP)","National","Military STEM Program","U.S. Army STEM education programs for students + teachers","AEOP Internships / Competitions","$5,000-$50,000","Annual","https://www.usaeop.com","https://www.usaeop.com","Army STEM programs; eCYBERMISSION, STEM competitions; NJROTC-adjacent; accessible programs","GOOD"),
    ("Office of Naval Research (ONR) STEM","National","Federal Military STEM Program","ONR funds Naval STEM education for K-12 students","Naval STEM / Sea Perch","$5,000-$50,000","Annual","https://www.nre.navy.mil","https://www.nre.navy.mil/work-with-us/","Navy STEM programs; Sea Perch (underwater robotics!); NJROTC directly relevant; accessible","GOOD"),

    # ---- FINAL BATCH - OC ROTARY / CIVIC CLUBS ----
    ("Rotary Club of Fullerton (District 5320)","Local","Civic Organization (Rotary)","Main Fullerton Rotary Club; local grants for community projects","Community / Youth Education Grants","$1,000-$10,000","Annual","https://www.rotaryfullerton.org","https://www.rotaryfullerton.org","Fullerton Rotary club; directly serves Troy HS community; accessible local grants; youth focus","GOOD"),
    ("Rotary Club of Anaheim","Local","Civic Organization (Rotary)","Anaheim Rotary Club (adjacent to Fullerton) community grants","Community / Education Grants","$1,000-$5,000","Annual","https://www.rotaryanahiem.org","https://www.rotaryanahiem.org","Adjacent to Fullerton; community + education grants; accessible for school programs","GOOD"),
    ("Fullerton Exchange Club","Local","Civic Organization (Exchange Club)","Fullerton Exchange Club supports youth and community programs","Youth / Community Grants","$500-$5,000","Annual","https://www.exchangeclubs.org","https://www.exchangeclubs.org","Fullerton civic club; youth + community; very accessible for local school programs","GOOD"),
    ("North OC American Association of University Women (AAUW)","Local","Civic Organization (Women's Education)","AAUW OC chapter funds women's education and STEM scholarships","STEM / Women's Education Scholarships","$1,000-$5,000","Annual","https://www.aauw.org","https://www.aauw.org/resources/programs/fellowships-grants/","Women in STEM scholarships; OC chapter; Troy NJROTC women cadets eligible; accessible","GOOD"),
    ("Sons of the American Revolution (SAR) OC Chapter","Local","Civic/Patriotic Organization","SAR funds scholarships and patriotic programs; JROTC connections","JROTC Medal / Scholarships","$500-$2,500","Annual","https://www.sar.org","https://www.sar.org/programs/scholarships/","Patriotic organization; JROTC medal program; NJROTC directly recognized; accessible","GOOD"),
    ("Daughters of the American Revolution (DAR) OC Chapter","Local","Civic/Patriotic Organization","DAR funds scholarships and JROTC programs; patriotic education","JROTC Scholarships / DAR Medals","$500-$5,000","Annual","https://www.dar.org","https://www.dar.org/national-society/scholarships","Patriotic organization; JROTC program scholarships; NJROTC directly relevant; accessible","GOOD"),
    ("American Legion Post 142 Fullerton","Local","Military Civic Organization (Fullerton)","Fullerton American Legion Post 142 supports local veterans + youth","JROTC / Youth Education Support","$500-$2,500","Annual","https://www.legion.org","https://www.legion.org","Fullerton Legion post; JROTC directly supported; very accessible; local veteran community","GOOD"),
    ("Veterans of Foreign Wars (VFW) Post Fullerton","Local","Military Civic Organization (Fullerton)","Fullerton VFW Post supports veterans + youth military programs","JROTC / Youth Grants","$500-$2,500","Annual","https://www.vfw.org","https://www.vfw.org","Fullerton VFW post; JROTC directly supported; very accessible; local veteran community","GOOD"),
    ("Naval Order of the United States (OC Commandery)","Local","Military Order (Naval Heritage)","Naval Order (OC chapter) supports naval heritage and NJROTC","NJROTC Support / Naval Heritage","$500-$5,000","Annual","https://www.navalorder.org","https://www.navalorder.org","Naval heritage organization; NJROTC directly relevant; OC chapter accessible; local funder","GOOD"),
    ("Navy League of the United States (OC Council)","Local","Military Organization (Navy League)","OC Navy League Council supports naval/NJROTC programs locally","NJROTC / Sea Cadet Support","$1,000-$10,000","Annual","https://www.navyleague.org","https://www.navyleague.org/councils/","OC council of Navy League; NJROTC DIRECTLY SUPPORTED; very accessible; local top priority","GOOD"),
]

with open(output_file, 'a', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerows(entries)

print(f"Batch 13 complete: {len(entries)} new entries appended")
