#!/usr/bin/env python3
# Batch 3: National Tech (FAANG+, semiconductors, cloud, networking, gaming, SoCal tech)

import csv

OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
("Apple Education Foundation","National","Corporate (Technology)","Apple's education programs fund K-12 STEM and coding; device grants and curriculum support for schools","Apple Education Grants","Varies - device/curriculum grants","Rolling","https://www.apple.com/education","https://www.apple.com/contact/","Device and curriculum grants for K-12 STEM; technology integration; Apple Distinguished Schools program","GOOD"),
("Meta Platforms Foundation","National","Corporate (Technology)","Meta funds K-12 CS education and STEM broadly; AR/VR education tools; community grants near Meta offices","Meta Education Grants / Community Grants","$10,000-$250,000","Annual","https://about.meta.com/social-impact","https://about.meta.com/social-impact/","CS and STEM education for underrepresented youth; AR/VR tools for education; Meta has SoCal offices","GOOD"),
("Salesforce.org","National","Corporate (Technology)","Salesforce philanthropic arm; funds K-12 CS and STEM broadly; 1-1-1 model donates 1% equity time and product","Technology and Education Grants","$10,000-$500,000","Annual","https://www.salesforce.org","https://www.salesforce.org/grant/","K-12 CS and STEM education; Salesforce has large CA presence; 1-1-1 philanthropy model","GOOD"),
("Oracle Education Foundation","National","Corporate (Technology)","Oracle funds K-12 STEM and CS education; ThinkQuest program alumni; tech career pipeline","STEM and CS Education","$10,000-$250,000","Annual","https://www.oracle.com","https://www.oracle.com/corporate/citizenship/","K-12 CS and STEM; Oracle has major CA presence; tech career pipeline for students","GOOD"),
("SAP America Foundation","National","Corporate (Technology)","SAP funds CS and STEM education globally; CSR programs for underserved youth; corporate skills volunteers","STEM and CS Community Grants","$10,000-$250,000","Annual","https://www.sap.com/usa/about/social-responsibility.html","https://www.sap.com/usa/about/social-responsibility.html","CS and STEM education; SAP has CA offices; corporate skills volunteers for mentorship","MEDIUM"),
("Adobe Foundation","National","Corporate (Technology)","Adobe funds creative and digital literacy education for youth; Creativity Scholarships; STEM-adjacent","Digital Literacy and Creativity Grants","$10,000-$250,000","Annual","https://www.adobe.com/about-adobe/corporate-responsibility.html","https://www.adobe.com/about-adobe/corporate-responsibility.html","Digital creativity and literacy; design tools useful for robotics documentation and CAD presentations","MEDIUM"),
("ServiceNow Foundation","National","Corporate (Technology)","ServiceNow funds STEM workforce development and digital equity for underserved communities; tech career pipeline","STEM Workforce Development","$10,000-$250,000","Annual","https://www.servicenow.com","https://www.servicenow.com/company/corporate-responsibility.html","STEM workforce development; tech career pipeline; underserved communities focus aligns with JROTC demographics","MEDIUM"),
("Workday Foundation","National","Corporate (Technology)","Workday funds K-12 education and STEM broadly; employee matching; career pipeline for underrepresented youth","Education and STEM Grants","$10,000-$100,000","Annual","https://www.workday.com","https://www.workday.com/en-us/company/corporate-social-responsibility.html","K-12 education and STEM; Workday has CA headquarters (Pleasanton); employee matching program","MEDIUM"),
("Intuit Education Initiative","National","Corporate (Technology)","Intuit funds financial literacy and STEM education for K-12 youth; prosperity initiatives for underserved communities","Financial Literacy and STEM","$10,000-$250,000","Annual","https://www.intuit.com","https://www.intuit.com/company/corporate-responsibility/","Financial literacy and STEM; Intuit has Mountain View CA HQ; underserved community focus","MEDIUM"),
("Zoom Foundation","National","Corporate (Technology)","Zoom Video Communications funds K-12 education and digital equity; community grants program","Digital Education Grants","$5,000-$100,000","Annual","https://www.zoom.us","https://www.zoom.us/en-us/about/social-impact.html","Digital education and equity; Zoom tools directly used by TroyVEX teams; San Jose CA HQ","MEDIUM"),
("Atlassian Foundation","National","Corporate (Technology)","Atlassian funds STEM education and social impact through Pledge 1% program; tech tools for nonprofits","STEM and Tech Nonprofit Grants","$10,000-$100,000","Annual","https://www.atlassian.com","https://www.atlassian.com/company/social-impact","STEM education and nonprofit tools; Sydney-based with large San Francisco office; Pledge 1% model","MEDIUM"),
("Palantir STEM Education","National","Corporate (Technology)","Palantir Technologies funds data science and STEM education for underserved youth; fellowship and scholarship programs","STEM Data Science Education","$5,000-$100,000","Annual","https://www.palantir.com","https://www.palantir.com/company/social-impact/","Data science STEM education; underrepresented youth focus; defense technology company aligns with JROTC mission","GOOD"),
("Snowflake Foundation","National","Corporate (Technology)","Snowflake funds STEM and data education for underserved students; tech career pipeline programs","Data and STEM Education","$5,000-$100,000","Annual","https://www.snowflake.com","https://www.snowflake.com/company/social-impact/","Data cloud technology; STEM education for underserved youth; tech career pipeline","MEDIUM"),
("HubSpot Foundation","National","Corporate (Technology)","HubSpot funds education and entrepreneurship for underserved youth; STEM adjacent through business technology","STEM and Entrepreneurship Grants","$5,000-$50,000","Annual","https://www.hubspot.com","https://www.hubspot.com/company/responsibility","Tech education and entrepreneurship; STEM adjacent; youth business and technology programs","MEDIUM"),
("Zendesk Neighbor Foundation","National","Corporate (Technology)","Zendesk funds education and social impact in communities where employees work; tech tools for nonprofits","Community Education Grants","$5,000-$100,000","Annual","https://www.zendesk.com","https://www.zendesk.com/company/social-impact/","Community education grants; Zendesk has CA presence; tech tools available for nonprofit teams","MEDIUM"),
("NVIDIA Foundation","National","Corporate (Technology/AI)","NVIDIA funds AI and STEM education broadly; AI for K-12 programs; robotics directly uses NVIDIA hardware","AI and STEM Education","$10,000-$500,000","Annual","https://www.nvidia.com","https://www.nvidia.com/en-us/about-nvidia/corporate-responsibility/","AI and GPU technology; VEX robots increasingly use AI/computer vision; NVIDIA HQ in Santa Clara CA","GOOD"),
("AMD Foundation","National","Corporate (Technology/Semiconductor)","AMD funds STEM education and diversity in technology; engineering career pipeline; HPC and computing programs","STEM and Computing Education","$5,000-$100,000","Annual","https://www.amd.com","https://www.amd.com/en/corporate/citizenship","Computing and engineering STEM; AMD processors used in robotics applications; Santa Clara CA HQ","GOOD"),
("Micron Technology Foundation","National","Corporate (Technology/Semiconductor)","Micron funds STEM education and diverse workforce pipeline; memory and storage technology company","STEM Education and Workforce","$10,000-$250,000","Annual","https://www.micron.com","https://www.micron.com/about/our-commitment/doing-good","K-12 STEM and diverse workforce pipeline; semiconductor engineering aligns with robotics electronics","GOOD"),
("Applied Materials Foundation","National","Corporate (Technology/Semiconductor)","Applied Materials funds STEM education and engineering for underserved students; semiconductor manufacturing equipment","STEM Engineering Education","$10,000-$250,000","Annual","https://www.appliedmaterials.com","https://www.appliedmaterials.com/company/responsibility","Semiconductor equipment manufacturer; STEM engineering education; Santa Clara CA HQ","GOOD"),
("Lam Research Foundation","National","Corporate (Technology/Semiconductor)","Lam Research funds STEM education and engineering programs; semiconductor etch and deposition equipment","STEM Engineering Grants","$10,000-$100,000","Annual","https://www.lamresearch.com","https://www.lamresearch.com/company/about-lam/sustainability/","Semiconductor equipment; STEM engineering education; Fremont CA HQ with SoCal operations","GOOD"),
("KLA Foundation","National","Corporate (Technology/Semiconductor)","KLA funds STEM education and diversity in semiconductor industry; process control equipment","STEM and Diversity in Tech","$10,000-$100,000","Annual","https://www.kla.com","https://www.kla.com/company/responsibility","Semiconductor process control; STEM education and diversity; Milpitas CA HQ","MEDIUM"),
("Marvell Technology Foundation","National","Corporate (Technology/Semiconductor)","Marvell funds STEM education and tech career pipeline; networking and storage semiconductor company","STEM Tech Career Pipeline","$5,000-$100,000","Annual","https://www.marvell.com","https://www.marvell.com/company/corporate-responsibility.html","Semiconductor networking; STEM education; Santa Clara CA HQ; networking technology relevant to robotics","MEDIUM"),
("Analog Devices Foundation","National","Corporate (Technology/Semiconductor)","Analog Devices funds STEM education; ADI signals and sensors relevant to robotics; engineering education","STEM Signals and Sensors Education","$5,000-$100,000","Annual","https://www.analog.com","https://www.analog.com/en/about-adi/corporate-social-responsibility.html","ADI sensors used in robotics; STEM engineering education; engineering pipeline relevant to TroyVEX","GOOD"),
("ON Semiconductor Foundation","National","Corporate (Technology/Semiconductor)","ON Semi funds STEM and engineering education; power management and sensing semiconductors","STEM Power Engineering","$5,000-$50,000","Annual","https://www.onsemi.com","https://www.onsemi.com/company/sustainability","Power management and sensing; STEM engineering education; electronics relevant to robotics power systems","MEDIUM"),
("Palo Alto Networks Foundation","National","Corporate (Technology/Cybersecurity)","Palo Alto Networks funds cybersecurity education for youth; STEM and cyber career pipeline; defense-adjacent","Cybersecurity and STEM Education","$10,000-$250,000","Annual","https://www.paloaltonetworks.com","https://www.paloaltonetworks.com/company/social-impact","Cybersecurity STEM education; youth career pipeline; defense-adjacent aligns with JROTC mission","GOOD"),
("CrowdStrike Foundation","National","Corporate (Technology/Cybersecurity)","CrowdStrike funds cybersecurity education for underserved youth; Next Generation STEM programs","Next Generation STEM / Cybersecurity","$10,000-$100,000","Annual","https://www.crowdstrike.com","https://www.crowdstrike.com/company/corporate-social-responsibility/","Cybersecurity STEM for underrepresented youth; Sunnyvale CA HQ; defense-adjacent mission","GOOD"),
("Fortinet Foundation","National","Corporate (Technology/Cybersecurity)","Fortinet funds cybersecurity education globally; Network Security Academy for youth; NSF grant recipient","Network Security Academy","$5,000-$100,000","Annual","https://www.fortinet.com","https://www.fortinet.com/corporate/csr","Cybersecurity education; Network Security Academy for youth; Sunnyvale CA HQ","GOOD"),
("Arista Networks Foundation","National","Corporate (Technology/Networking)","Arista Networks funds STEM education and diversity in technology; cloud networking company","STEM and Tech Diversity","$5,000-$50,000","Annual","https://www.arista.com","https://www.arista.com/en/company/overview/social-responsibility","Cloud networking; STEM education and diversity programs; Santa Clara CA HQ","MEDIUM"),
("Akamai Foundation","National","Corporate (Technology/CDN)","Akamai funds cybersecurity and STEM education; Internet safety and digital literacy for youth","Cybersecurity and Digital Literacy","$5,000-$100,000","Annual","https://www.akamai.com","https://www.akamai.com/company/corporate-responsibility","Internet CDN and cybersecurity; STEM education; digital literacy for youth programs","MEDIUM"),
("Juniper Networks Foundation","National","Corporate (Technology/Networking)","Juniper Networks funds STEM and education for underserved youth; networking and cloud technology","STEM Education Grants","$5,000-$50,000","Annual","https://www.juniper.net","https://www.juniper.net/us/en/company/social-responsibility.html","Network technology company; STEM education; Sunnyvale CA HQ; networking relevant to robotics","MEDIUM"),
("F5 Networks Foundation","National","Corporate (Technology/Networking)","F5 funds STEM education and diversity in technology; application delivery and security","STEM and Tech Diversity","$5,000-$50,000","Annual","https://www.f5.com","https://www.f5.com/company/social-responsibility","Application delivery technology; STEM education; Seattle HQ with CA offices","MEDIUM"),
("NetApp Foundation","National","Corporate (Technology/Storage)","NetApp funds STEM education and digital equity; data management technology company; hybrid cloud","STEM Digital Equity","$5,000-$100,000","Annual","https://www.netapp.com","https://www.netapp.com/company/sustainability/","Data storage and management; STEM education; San Jose CA HQ","MEDIUM"),
("Pure Storage Foundation","National","Corporate (Technology/Storage)","Pure Storage funds STEM education and workforce diversity; flash storage technology","STEM and Workforce Diversity","$5,000-$50,000","Annual","https://www.purestorage.com","https://www.purestorage.com/company/sustainability.html","Flash storage technology; STEM education; Mountain View CA HQ","MEDIUM"),
("Nutanix Foundation","National","Corporate (Technology/Cloud)","Nutanix funds STEM education and diversity in cloud computing; hyper-converged infrastructure","STEM Cloud Education","$5,000-$50,000","Annual","https://www.nutanix.com","https://www.nutanix.com/company/corporate-responsibility","Cloud computing; STEM education; San Jose CA HQ","MEDIUM"),
("Electronic Arts Foundation","National","Corporate (Technology/Gaming)","EA funds STEM and CS education; game development as STEM entry point; Play to Learn program","Play to Learn / STEM Education","$10,000-$250,000","Annual","https://www.ea.com","https://www.ea.com/commitments/positive-play/foundation","Game development as STEM; coding and CS education pipeline; Redwood City CA HQ near Fullerton","GOOD"),
("Epic Games Foundation (Unreal Engine)","National","Corporate (Technology/Gaming)","Epic Games funds education programs using Unreal Engine; STEM and creative technology for youth","Unreal Engine Education / MegaGrants","$5,000-$500,000","Rolling","https://www.unrealengine.com/en-US/megagrants","https://www.unrealengine.com/en-US/megagrants","MegaGrants program for education projects; Unreal Engine for simulation in robotics; rolling applications","GOOD"),
("Roblox Foundation","National","Corporate (Technology/Gaming)","Roblox funds digital citizenship and CS education for youth; 17M+ daily users; creator economy education","Digital Citizenship and CS Education","$10,000-$250,000","Annual","https://www.roblox.com","https://www.roblox.com/corporate-governance/social-impact","Youth CS education; game-based learning pipeline to STEM; San Mateo CA HQ","GOOD"),
("Unity Technologies Education","National","Corporate (Technology/Gaming)","Unity funds STEM and game development education; free Unity for students; robotics simulation tools","STEM Game Development Education","$5,000-$50,000","Rolling","https://unity.com","https://unity.com/education","Game engine used in robot simulation; free software for students; STEM education programs","GOOD"),
("Snap Foundation","National","Corporate (Technology/Social Media)","Snap funds AR/creativity and youth education programs; Yellow program for young entrepreneurs; SoCal headquarters","Yellow Program / AR Education","$10,000-$100,000","Annual","https://snap.com","https://snap.com/en-US/snap-social-impact","Santa Monica CA HQ; youth entrepreneurship and technology education; AR tools for STEM","GOOD"),
("Riot Games Foundation (Los Angeles)","National","Corporate (Technology/Gaming)","Riot Games (League of Legends) HQ in Los Angeles CA; funds education and social impact in LA; STEM and diversity focus","Community and Education Grants","$10,000-$250,000","Annual","https://www.riotgames.com","https://www.riotgames.com/en/social-impact","Los Angeles CA HQ (near Fullerton); community education grants; STEM and diversity focus","GOOD"),
("Blizzard Entertainment Foundation (Irvine CA)","State","Corporate (Technology/Gaming)","Blizzard Entertainment HQ in Irvine CA (OC); funds local education and community programs in OC; tech and gaming STEM","OC Community and Education Grants","$5,000-$50,000","Annual","https://www.blizzard.com","https://www.blizzard.com/en-us/community","Irvine OC HQ (near Fullerton); local community education grants; gaming and technology STEM pipeline","GOOD"),
("Activision Foundation (Santa Monica CA)","State","Corporate (Technology/Gaming)","Activision (now Microsoft Gaming) office in Santa Monica CA; funds education and community in SoCal; tech and gaming","SoCal Community Education","$5,000-$50,000","Annual","https://www.activision.com","https://www.activision.com/corporate/social-responsibility","SoCal office; gaming and technology education; Microsoft acquisition means access to Microsoft Philanthropies pipeline","GOOD"),
("DoorDash Foundation","National","Corporate (Technology/Gig)","DoorDash funds community economic opportunity and education; STEM and career pipeline for underserved youth","Community Education and Economic Opportunity","$5,000-$100,000","Annual","https://www.doordash.com","https://www.doordash.com/en-US/social-impact/","Community economic opportunity; STEM career pipeline; San Francisco CA HQ; underserved youth focus","MEDIUM"),
("Lyft Foundation","National","Corporate (Technology/Transportation)","Lyft funds underserved community education and economic mobility; tech career pipeline","Community Education Grants","$5,000-$100,000","Annual","https://www.lyft.com","https://www.lyft.com/social-impact","Community education and economic mobility; tech career pipeline; San Francisco CA HQ","MEDIUM"),
("Airbnb Foundation","National","Corporate (Technology/Travel)","Airbnb funds community connection and education; Open Homes for emergency housing and displacement support","Community Connection and Education","$5,000-$50,000","Annual","https://www.airbnb.com","https://www.airbnb.com/airbnb-nonprofit","Community programs; emergency housing; San Francisco CA HQ; limited direct STEM fit","MEDIUM"),
("PayPal Foundation","National","Corporate (Technology/Finance)","PayPal funds financial inclusion and economic opportunity for underserved communities; tech-enabled philanthropy","Financial Inclusion / Education","$10,000-$250,000","Annual","https://www.paypal.com","https://www.paypalobjects.com/en_US/i/logo/pp-logo-100px.png","Financial inclusion and economic opportunity; STEM through workforce pipeline; San Jose CA HQ","MEDIUM"),
("Visa Foundation","National","Corporate (Technology/Finance)","Visa funds inclusive economic growth and education; financial literacy and tech career pipeline","Financial Literacy and Tech Education","$10,000-$250,000","Annual","https://www.visafoundation.org","https://www.visafoundation.org/","Financial literacy and tech career pipeline; San Francisco CA HQ; underserved community focus","MEDIUM"),
("eBay Foundation","National","Corporate (Technology/E-commerce)","eBay funds microentrepreneurship and education for underserved youth; tech career access","Tech Career and Entrepreneurship","$5,000-$100,000","Annual","https://www.ebayinc.com","https://www.ebayinc.com/impact/","Tech career access and entrepreneurship; San Jose CA HQ; underserved youth STEM pipeline","MEDIUM"),
("Western Digital Foundation","National","Corporate (Technology/Storage)","Western Digital funds STEM education and workforce development; data storage technology company","STEM Workforce Education","$5,000-$100,000","Annual","https://www.westerndigital.com","https://www.westerndigital.com/company/social-responsibility","Data storage; STEM education; San Jose CA HQ; engineering pipeline relevant to robotics","MEDIUM"),
("Seagate Technology Foundation","National","Corporate (Technology/Storage)","Seagate funds STEM education and digital inclusion; data storage technology; workforce pipeline","STEM and Digital Inclusion","$5,000-$100,000","Annual","https://www.seagate.com","https://www.seagate.com/global-citizenship/","Data storage; STEM education; Fremont CA HQ; engineering pipeline","MEDIUM"),
("Garmin Foundation","National","Corporate (Technology/Navigation)","Garmin funds STEM and aviation education; GPS/navigation technology directly relevant to robotics navigation and autonomous systems","STEM Navigation and Aviation","$5,000-$100,000","Annual","https://www.garmin.com","https://www.garmin.com/en-US/company/about-garmin/","GPS/navigation technology directly used in robotics; STEM and aviation education pipeline; strong robotics fit","GOOD"),
("Logitech Foundation","National","Corporate (Technology/Hardware)","Logitech funds STEM creativity and education for youth; design and technology tools for schools","STEM Creativity Education","$5,000-$100,000","Annual","https://www.logitech.com","https://www.logitech.com/en-us/sustainability.html","Computer peripherals and design tools; STEM creativity education; Swiss HQ with US CA offices","MEDIUM"),
("Trimble Foundation","National","Corporate (Technology/Engineering)","Trimble funds STEM and engineering education; positioning and surveying technology; construction tech","STEM Engineering Education","$5,000-$100,000","Annual","https://www.trimble.com","https://www.trimble.com/en/our-company/sustainability","Positioning technology relevant to GPS in robotics; STEM engineering education; Sunnyvale CA HQ","GOOD"),
("Keysight Technologies Foundation","National","Corporate (Technology/Test Equipment)","Keysight funds STEM education and engineering; electronic test and measurement equipment; direct robotics relevance","STEM Test and Measurement Education","$5,000-$100,000","Annual","https://www.keysight.com","https://www.keysight.com/us/en/company/our-company/citizenship.html","Electronic test equipment used in robotics; STEM engineering education; Santa Rosa CA HQ","GOOD"),
("Teradyne Foundation","National","Corporate (Technology/Robotics)","Teradyne owns Universal Robots and MiR mobile robots; directly in robotics industry; STEM education pipeline","Robotics and STEM Education","$10,000-$100,000","Annual","https://www.teradyne.com","https://www.teradyne.com/about-teradyne/corporate-citizenship/","DIRECTLY IN ROBOTICS INDUSTRY (owns Universal Robots); STEM education for robotics; extremely high relevance","GOOD"),
("Cognex Foundation","National","Corporate (Technology/Machine Vision)","Cognex funds STEM and machine vision education; factory automation and quality inspection","Machine Vision STEM Education","$5,000-$100,000","Annual","https://www.cognex.com","https://www.cognex.com/about/corporate-responsibility","Machine vision directly used in robotics; STEM education; Natick MA HQ with national programs","GOOD"),
("Zebra Technologies Foundation","National","Corporate (Technology/AIDC)","Zebra Technologies funds STEM education and workforce development; enterprise mobile computing and barcode scanning","STEM Technology Education","$5,000-$50,000","Annual","https://www.zebra.com","https://www.zebra.com/us/en/about-zebra/company/corporate-responsibility.html","Enterprise technology; STEM education; Lincolnshire IL HQ with national programs","MEDIUM"),
("PTC Foundation (Engineering Software)","National","Corporate (Technology/Engineering Software)","PTC funds STEM and CAD/engineering education; ThingWorx IoT platform; used in advanced manufacturing","STEM CAD and IoT Education","$10,000-$100,000","Rolling","https://www.ptc.com","https://www.ptc.com/en/company/corporate-responsibility","CAD and IoT technology directly used in robotics design; STEM engineering education; free Creo for students","GOOD"),
("Dassault Systemes Foundation","National","Corporate (Technology/Engineering Software)","Dassault funds STEM and 3D experience education; SolidWorks CAD used in robotics design; virtual worlds for education","3D Experience STEM Education","$10,000-$100,000","Annual","https://www.3ds.com","https://www.3ds.com/company/3ds-foundation/","SolidWorks CAD used extensively in robotics design; STEM engineering education; 3DEXPERIENCE for students","GOOD"),
("Rockwell Automation Foundation","National","Corporate (Technology/Industrial Automation)","Rockwell Automation funds STEM and industrial automation education; PLC programming directly relevant to robotics","Industrial Automation STEM","$10,000-$250,000","Annual","https://www.rockwellautomation.com","https://www.rockwellautomation.com/en-us/company/social-responsibility.html","Industrial automation and PLC programming used in robotics; STEM education; Milwaukee WI HQ with national programs","GOOD"),
("UiPath Foundation","National","Corporate (Technology/RPA)","UiPath funds robotics process automation and STEM education; Academic Alliance for students","RPA and STEM Education","$5,000-$100,000","Annual","https://www.uipath.com","https://www.uipath.com/company/rpa-for-good","Robotics Process Automation - STEM pipeline to programming; Academic Alliance free software for students","GOOD"),
("Accenture Foundation","National","Corporate (Technology/Consulting)","Accenture funds STEM education and digital skills for underserved youth; Skills to Succeed program","Skills to Succeed / STEM","$25,000-$500,000","Annual","https://www.accenture.com","https://www.accenture.com/us-en/about/responsibility/corporate-citizenship","STEM and digital skills for underserved youth; Accenture has large CA presence; Skills to Succeed program","GOOD"),
("Cognizant Foundation","National","Corporate (Technology/Consulting)","Cognizant funds STEM education and workforce development for underserved youth; Outreach program","STEM Workforce Development","$10,000-$100,000","Annual","https://www.cognizant.com","https://www.cognizant.com/us/en/social-responsibility","STEM education for underserved communities; tech workforce pipeline; CA operations in several locations","MEDIUM"),
("Infosys Foundation USA","National","Corporate (Technology/Consulting)","Infosys Foundation USA explicitly funds CS and STEM education for K-12; Springboard program trains 10K teachers","Springboard / STEM Education","$10,000-$500,000","Annual RFP","https://www.infosys.com/infosys-foundation-usa.html","https://www.infosys.com/infosys-foundation-usa.html","CS and STEM teacher training explicitly funded; K-12 programming; Springboard trains 10K teachers","GOOD"),
("Tata Consultancy Services Foundation","National","Corporate (Technology/Consulting)","TCS funds STEM and education for underserved communities; goIT program for teens ages 13-18","goIT / STEM Teen Programs","$10,000-$100,000","Annual","https://www.tcs.com","https://www.tcs.com/who-we-are/corporate-sustainability","goIT program for teens 13-18 directly matches TroyVEX age range; STEM education; CA operations","GOOD"),
("LinkedIn (Microsoft) Foundation","National","Corporate (Technology/Social)","LinkedIn funds workforce development and economic opportunity through skills training; STEM career pathways","Economic Opportunity and STEM","$10,000-$250,000","Annual","https://linkedinforgood.linkedin.com","https://linkedinforgood.linkedin.com/","STEM career pathway support; LinkedIn for Jobs for cadets; Sunnyvale CA HQ; workforce development grants","MEDIUM"),
("Mastercard Center for Inclusive Growth","National","Corporate (Technology/Finance)","Mastercard funds economic inclusion and education for underserved communities; STEM workforce pipeline","Inclusive Growth / STEM Education","$25,000-$500,000","Annual","https://www.mastercardcenter.org","https://www.mastercardcenter.org/","Economic inclusion and education; STEM workforce pipeline; Purchase NY HQ with CA presence","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 3 complete: {len(ENTRIES)} new entries appended")
