#!/usr/bin/env python3
# Batch 4: Energy, Manufacturing, Automotive, Industrial, Chemicals

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Energy
("Halliburton Foundation","National","Corporate (Energy)","Oil field services; funds STEM education and engineering near facilities; energy workforce pipeline","STEM Energy Workforce","$5,000-$100,000","Annual","https://www.halliburton.com","https://www.halliburton.com/en/about-us/corporate-responsibility","Oil field engineering; STEM education; Houston TX HQ with CA operations","MEDIUM"),
("Baker Hughes Foundation","National","Corporate (Energy)","Baker Hughes funds STEM education and clean energy workforce; industrial AI and energy technology","STEM Clean Energy Education","$5,000-$100,000","Annual","https://www.bakerhughes.com","https://www.bakerhughes.com/company/corporate-responsibility","Energy technology; STEM education; clean energy pipeline; Houston TX HQ","MEDIUM"),
("Schlumberger / SLB Foundation","National","Corporate (Energy)","SLB funds STEM education and diversity in energy technology; Faculty for the Future program; global programs","Faculty for the Future / STEM","$10,000-$100,000","Annual","https://www.slb.com","https://www.slb.com/sustainability","Energy technology STEM; Faculty for the Future scholarship; international and national programs","MEDIUM"),
("Occidental Petroleum Foundation","National","Corporate (Energy)","Oxy funds STEM education and community programs near operations; engineering and energy career pipeline","STEM and Community Grants","$5,000-$100,000","Annual","https://www.oxy.com","https://www.oxy.com/sustainability/","Energy engineering STEM; community programs near operations; Westwood CA HQ","MEDIUM"),
("Phillips 66 Foundation","National","Corporate (Energy)","Phillips 66 funds STEM education and community programs; refining and chemicals company","STEM and Community Grants","$5,000-$100,000","Annual","https://www.phillips66.com","https://www.phillips66.com/sustainability/community","Refining and energy; STEM education; Houston TX HQ with CA refinery operations","MEDIUM"),
("Valero Energy Foundation","National","Corporate (Energy)","Valero funds STEM education near refineries; education and community programs","STEM Refinery Community Grants","$5,000-$100,000","Annual","https://www.valero.com","https://www.valero.com/corporate-responsibility","Refining company; STEM education near refineries; San Antonio TX HQ with CA refinery","MEDIUM"),
("NextEra Energy Foundation","National","Corporate (Energy)","NextEra funds STEM education and clean energy programs; largest US renewable energy company","STEM and Clean Energy Education","$10,000-$250,000","Annual","https://www.nexteraenergy.com","https://www.nexteraenergy.com/sustainability.html","Renewable energy leader; STEM education; clean energy aligns with STEM innovation agenda","GOOD"),
("Duke Energy Foundation","National","Corporate (Energy)","Duke Energy funds STEM education and workforce in communities it serves; STEM teacher training","STEM Teacher Training / Education","$10,000-$250,000","Annual","https://www.duke-energy.com","https://www.duke-energy.com/our-company/community","Utility company; STEM education and teacher training; Charlotte NC HQ with national programs","MEDIUM"),
("Exelon Foundation","National","Corporate (Energy)","Exelon funds STEM education and diversity in energy sector; largest US electric utility","STEM Energy Education","$10,000-$250,000","Annual","https://www.exeloncorp.com","https://www.exeloncorp.com/corporate-responsibility","Largest US electric utility; STEM education; Chicago IL HQ with CA operations","MEDIUM"),
("Dominion Energy Charitable Foundation","National","Corporate (Energy)","Dominion Energy funds STEM education and community programs in service territories","STEM and Community Grants","$5,000-$100,000","Annual","https://www.dominionenergy.com","https://www.dominionenergy.com/our-company/making-an-impact","Utility company; STEM education; Richmond VA HQ but national giving programs","MEDIUM"),
("American Electric Power Foundation","National","Corporate (Energy)","AEP funds STEM education and workforce; large US electric utility serving 11 states","STEM Workforce Education","$5,000-$100,000","Annual","https://www.aep.com","https://www.aep.com/community/","Utility; STEM education; Columbus OH HQ with national programs","MEDIUM"),
("Xcel Energy Foundation","National","Corporate (Energy)","Xcel Energy funds STEM education and clean energy programs; primarily Midwest and Southwest","STEM Clean Energy Education","$5,000-$100,000","Annual","https://www.xcelenergy.com","https://www.xcelenergy.com/company/community","Clean energy utility; STEM education; Minneapolis MN HQ","MEDIUM"),
("CenterPoint Energy Foundation","National","Corporate (Energy)","CenterPoint funds STEM education and community programs near operations; natural gas utility","STEM and Community Grants","$5,000-$50,000","Annual","https://www.centerpointenergy.com","https://www.centerpointenergy.com/en-us/corporate/pages/charitable-giving.aspx","Natural gas utility; STEM education; Houston TX HQ with national giving","MEDIUM"),
("Entergy Foundation","National","Corporate (Energy)","Entergy funds STEM education and workforce in Gulf Coast states; education and community investment","STEM Education Grants","$5,000-$100,000","Annual","https://www.entergy.com","https://www.entergy.com/responsibility/community/","Gulf Coast utility; STEM education; New Orleans LA HQ","MEDIUM"),
("Pacific Gas and Electric Foundation","State","Corporate (Energy)","PG&E serves Northern and Central California; funds STEM education and workforce near facilities","STEM and Community Grants","$5,000-$100,000","Annual","https://www.pge.com","https://www.pge.com/en_US/about-pge/company-information/giving-back/giving-back.page","California utility; STEM education; San Francisco CA HQ; CA focus relevant to TroyVEX","GOOD"),
("Westinghouse Electric Foundation","National","Corporate (Nuclear/Energy)","Nuclear energy technology company; funds STEM education and nuclear engineering pipeline","STEM Nuclear Engineering","$5,000-$100,000","Annual","https://www.westinghousenuclear.com","https://www.westinghousenuclear.com/about/corporate-responsibility","Nuclear technology; STEM engineering; career pipeline to energy engineering","MEDIUM"),
# Manufacturing / Industrial
("Deere and Company Foundation (John Deere)","National","Corporate (Manufacturing)","John Deere funds STEM education and agricultural engineering; FFA partner; engineering career pipeline","STEM Agricultural Engineering","$10,000-$250,000","Annual","https://www.deere.com","https://www.deere.com/en/our-company/john-deere-foundation/","Agricultural and industrial engineering STEM; FFA partnership; Moline IL HQ with national programs","GOOD"),
("Illinois Tool Works Foundation","National","Corporate (Manufacturing)","ITW funds STEM education and engineering workforce; diversified manufacturing company","STEM Engineering Workforce","$5,000-$100,000","Annual","https://www.itw.com","https://www.itw.com/corporate-responsibility/","Manufacturing engineering STEM; workforce pipeline; Glenview IL HQ with national programs","MEDIUM"),
("Danaher Foundation","National","Corporate (Manufacturing)","Danaher funds STEM education and science tools for K-12; life sciences and diagnostics instrumentation","STEM Science Tools Education","$10,000-$250,000","Annual","https://www.danaher.com","https://www.danaher.com/how-we-work/environmental-social-and-governance","Science instrumentation; STEM education; Washington DC HQ with national programs; water and life science tools","GOOD"),
("Roper Technologies Foundation","National","Corporate (Manufacturing)","Roper funds STEM education and engineering programs; diversified industrial company; software and engineered products","STEM Engineering Education","$5,000-$50,000","Annual","https://www.ropertech.com","https://www.ropertech.com/social-responsibility","Diversified industrial and software company; STEM engineering education; Sarasota FL HQ","MEDIUM"),
("Dover Corporation Foundation","National","Corporate (Manufacturing)","Dover funds STEM education and engineering career pipeline; diversified industrial manufacturer","STEM Manufacturing Engineering","$5,000-$100,000","Annual","https://www.dovercorporation.com","https://www.dovercorporation.com/our-company/corporate-responsibility/","Diversified manufacturing; STEM education and engineering career pipeline; Downers Grove IL HQ","MEDIUM"),
("Pentair Foundation","National","Corporate (Manufacturing)","Pentair funds STEM education and water technology; water treatment and flow control systems","STEM Water Technology","$5,000-$100,000","Annual","https://www.pentair.com","https://www.pentair.com/en-us/sustainability.html","Water technology company; STEM education; Reno NV HQ; water management relevant to engineering","MEDIUM"),
("Xylem Foundation","National","Corporate (Manufacturing)","Xylem funds STEM education and water technology programs for youth; Watermark program","Watermark / STEM Water Education","$10,000-$250,000","Annual","https://www.xylem.com","https://www.xylem.com/en-us/making-waves/xylem-watermark/","Water technology; Watermark STEM program for youth; Rye NY HQ with national programs","MEDIUM"),
("A.O. Smith Foundation","National","Corporate (Manufacturing)","A.O. Smith funds STEM education and water/heating technology programs; engineer career pipeline","STEM Engineering Education","$5,000-$50,000","Annual","https://www.aosmith.com","https://www.aosmith.com/corporate-responsibility/","Water heating and technology; STEM engineering education; Milwaukee WI HQ","MEDIUM"),
("Graco Foundation","National","Corporate (Manufacturing)","Graco funds STEM education and fluid handling engineering programs near facilities; Minnesota-based manufacturer","STEM Fluid Engineering","$5,000-$50,000","Annual","https://www.graco.com","https://www.graco.com/us/en/social-responsibility.html","Fluid handling equipment; STEM engineering; Minneapolis MN HQ with national programs","MEDIUM"),
("Lincoln Electric Foundation","National","Corporate (Manufacturing)","Lincoln Electric funds STEM and welding/fabrication education; career pathway to skilled manufacturing","STEM Welding and Fabrication","$5,000-$100,000","Annual","https://www.lincolnelectric.com","https://www.lincolnelectric.com/en-us/company/about-us/corporate-responsibility","Welding technology; STEM fabrication education; Cleveland OH HQ; robotics fabrication overlap","GOOD"),
("Kennametal Foundation","National","Corporate (Manufacturing)","Kennametal funds STEM education and materials engineering; cutting tools and industrial materials","STEM Materials Engineering","$5,000-$50,000","Annual","https://www.kennametal.com","https://www.kennametal.com/en/company/sustainability.html","Materials engineering STEM; cutting tools and industrial materials; Pittsburgh PA HQ","MEDIUM"),
("Nordson Corporation Foundation","National","Corporate (Manufacturing)","Nordson funds STEM education and precision dispensing technology; engineering career pipeline","STEM Precision Engineering","$5,000-$100,000","Annual","https://www.nordson.com","https://www.nordson.com/en/about-nordson/corporate-social-responsibility","Precision dispensing technology; STEM engineering education; Westlake OH HQ with CA operations","MEDIUM"),
("IDEX Corporation Foundation","National","Corporate (Manufacturing)","IDEX funds STEM education and flow control engineering; pumps and fire protection systems","STEM Flow Engineering","$5,000-$50,000","Annual","https://www.idexcorp.com","https://www.idexcorp.com/our-company/corporate-responsibility/","Flow control engineering; STEM education; Lake Forest IL HQ","MEDIUM"),
("Watts Water Technologies Foundation","National","Corporate (Manufacturing)","Watts Water funds STEM education and water technology programs; flow control and water quality","STEM Water Engineering","$5,000-$50,000","Annual","https://www.watts.com","https://www.watts.com/our-story/corporate-responsibility","Water technology engineering; STEM education; North Andover MA HQ","MEDIUM"),
# Automotive
("General Motors Foundation","National","Corporate (Automotive)","GM funds STEM education and automotive engineering; GM Next Generation award; manufacturing career pipeline","STEM Automotive Education","$10,000-$500,000","Annual","https://www.gm.com","https://www.gm.com/our-impact/community","Automotive engineering STEM; GM Next Generation award; Detroit MI HQ with CA design center","GOOD"),
("Ford Motor Company Foundation","National","Corporate (Automotive)","Ford funds STEM education and mobility; FIRST Robotics sponsor; engineering career pipeline; Ford Motor Fund","Ford Motor Fund / STEM Grants","$10,000-$250,000","Annual","https://www.fordfoundation.org","https://www.ford.com/about-ford/our-company/community/","FIRST Robotics sponsor; STEM engineering and mobility; Dearborn MI HQ with CA operations","GOOD"),
("Toyota USA Foundation","National","Corporate (Automotive)","Toyota funds STEM education and innovation; K-12 curriculum support; Torrance CA HQ (near Fullerton)","Toyota Driving Possibilities / STEM","$10,000-$500,000","Annual","https://www.toyotausa.com/community.html","https://www.toyotausa.com/community.html","Torrance CA HQ (near Fullerton); STEM education explicitly funded; K-12 curriculum support","GOOD"),
("Honda Foundation USA","National","Corporate (Automotive)","Honda North America funds STEM education and innovation; Power of Dreams scholarship; Torrance CA HQ","Power of Dreams / STEM Education","$10,000-$250,000","Annual","https://www.honda.com","https://www.honda.com/community","Torrance CA HQ near Fullerton; STEM education and innovation; Power of Dreams program","GOOD"),
("Stellantis Foundation","National","Corporate (Automotive)","Fiat Chrysler/Stellantis funds STEM education and manufacturing career pipeline; Auburn Hills MI HQ","STEM Manufacturing Education","$5,000-$100,000","Annual","https://www.stellantis.com","https://www.stellantis.com/en/sustainability/our-people-and-communities","Automotive manufacturing; STEM education; national programs with CA dealership network","MEDIUM"),
("Magna International Foundation","National","Corporate (Automotive)","Magna funds STEM education and automotive engineering; largest auto supplier in North America","STEM Automotive Engineering","$5,000-$100,000","Annual","https://www.magna.com","https://www.magna.com/company/company-overview/responsibility","Largest auto supplier; STEM engineering education; Aurora ON HQ with US facilities","MEDIUM"),
("BorgWarner Foundation","National","Corporate (Automotive)","BorgWarner funds STEM education and EV powertrain technology; clean mobility engineering pipeline","STEM EV Technology Education","$5,000-$100,000","Annual","https://www.borgwarner.com","https://www.borgwarner.com/sustainability","EV powertrain technology; STEM engineering; Auburn Hills MI HQ with CA EV operations","MEDIUM"),
("Aptiv Foundation","National","Corporate (Automotive)","Aptiv funds STEM education and autonomous driving technology; electrical vehicle architecture","STEM Autonomous Driving","$5,000-$100,000","Annual","https://www.aptiv.com","https://www.aptiv.com/en/insights/article/corporate-responsibility","Autonomous vehicle technology; STEM education; Dublin Ireland HQ with major US engineering centers","MEDIUM"),
("Rivian Foundation","National","Corporate (Automotive/EV)","Rivian funds community and education programs; EV truck and SUV startup; Irvine CA was previous HQ","Community and STEM Education","$5,000-$50,000","Annual","https://www.rivian.com","https://www.rivian.com/stories/responsibility","EV startup with CA roots; community and STEM education; electric vehicle engineering pipeline","GOOD"),
("Lucid Motors Foundation","State","Corporate (Automotive/EV)","Lucid Motors HQ in Newark CA; luxury EV company; funds STEM education and clean mobility programs","STEM Clean Mobility","$5,000-$50,000","Annual","https://www.lucidmotors.com","https://www.lucidmotors.com/us/about","CA-headquartered EV company; STEM education; clean mobility engineering relevant to robotics","GOOD"),
# Chemicals / Materials
("DuPont Foundation","National","Corporate (Chemicals/Materials)","DuPont funds STEM education and materials science programs; engineering career pipeline; Delaware HQ","STEM Materials Science","$5,000-$100,000","Annual","https://www.dupont.com","https://www.dupont.com/about/social-impact.html","Materials science STEM; engineering career pipeline; national programs with CA operations","MEDIUM"),
("Eastman Chemical Foundation","National","Corporate (Chemicals)","Eastman funds STEM education and chemistry programs; specialty chemicals and materials","STEM Chemistry Education","$5,000-$50,000","Annual","https://www.eastman.com","https://www.eastman.com/company/sustainability/Pages/default.aspx","Specialty chemicals; STEM chemistry education; Kingsport TN HQ with national programs","MEDIUM"),
("Olin Corporation Foundation","National","Corporate (Chemicals/Defense)","Olin makes ammunition and chemicals; funds STEM and defense-adjacent education programs","STEM and Defense Education","$5,000-$50,000","Annual","https://www.olin.com","https://www.olin.com/about-us/corporate-responsibility","Ammunition and chemicals; STEM education; defense-adjacent aligns with JROTC mission","MEDIUM"),
("PPG Industries Foundation","National","Corporate (Chemicals/Coatings)","PPG funds STEM education and COLORFUL COMMUNITIES program; paints coatings and specialty materials","STEM and Colorful Communities","$5,000-$100,000","Annual","https://www.ppg.com","https://www.ppg.com/en/global/sustainability/","Coatings and materials; STEM education; COLORFUL COMMUNITIES program; Pittsburgh PA HQ","MEDIUM"),
("Sherwin-Williams Foundation","National","Corporate (Chemicals/Coatings)","Sherwin-Williams funds education and community programs; coatings and paints company","Community Education Grants","$5,000-$50,000","Annual","https://www.sherwin-williams.com","https://www.sherwin-williams.com/home-and-family/ask-sherwin/corporate-responsibility","Coatings company; community education; Cleveland OH HQ with national programs","MEDIUM"),
("Nucor Steel Foundation","National","Corporate (Manufacturing/Steel)","Nucor funds STEM education and steelmaking career pipeline; employee scholarship program","STEM Steelmaking Education","$5,000-$100,000","Annual","https://www.nucor.com","https://www.nucor.com/sustainability/","Largest US steel producer; STEM education; Charlotte NC HQ; skilled trades and engineering pipeline","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 4 complete: {len(ENTRIES)} new entries appended")
