import csv, os

output_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'troyvex_donor_list.csv')

entries = [
    # ---- NATIONAL CORPORATE FOUNDATIONS (Consumer Goods / Retail) ----
    ("Target Foundation","National","Corporate Foundation (Retail)","Target's philanthropic arm; STEM education and youth development","Target Circle Community Giving / Foundation Grants","$5,000-$100,000","Annual (LOIs spring)","https://corporate.target.com/sustainability-governance/philanthropy","https://corporate.target.com/sustainability-governance/philanthropy/target-foundation","Fortune 50 retailer; STEM + youth development; apply via online portal; HQ Minneapolis MN","MEDIUM"),
    ("Walmart Foundation","National","Corporate Foundation (Retail)","Walmart Foundation funds community, workforce, and education programs","Walmart Community Grants","$250-$5,000","Rolling","https://walmart.org","https://walmart.org/how-we-give/local-giving-program","Local Walmart stores give community grants; apply at store level; easy application; accessible for school programs","GOOD"),
    ("Costco Wholesale Foundation","National","Corporate Foundation (Retail)","Costco focuses on children and education; youth-focused programs","Children's Miracle Network / Education Grants","$1,000-$25,000","Annual","https://www.costco.com/sustainability.html","https://www.costco.com/sustainability.html","Strong education focus; local warehouse giving; OC/SoCal Costcos in Fullerton area; youth programs","MEDIUM"),
    ("The Home Depot Foundation","National","Corporate Foundation (Home Improvement)","Home Depot Foundation focuses on veteran housing and disaster relief","Veteran Housing / Community Impact Grants","$5,000-$100,000","Rolling","https://corporate.homedepot.com/foundation","https://corporate.homedepot.com/foundation/grant-application","Veteran-adjacent (NJROTC tie-in possible); community resilience grants; major national funder","MEDIUM"),
    ("Lowes Foundation","National","Corporate Foundation (Home Improvement)","Lowe's funds skilled trades education and community improvement","Gable Grants (Trades Education)","$5,000-$50,000","Annual","https://lowesfoundation.org","https://lowesfoundation.org/our-grants/","Skilled trades and career/technical education; engineering and construction adjacent; school programs","MEDIUM"),
    ("Dollar General Literacy Foundation","National","Corporate Foundation (Retail)","Dollar General Foundation focuses on literacy and education","Youth Literacy Grants","$1,000-$5,000","Annual (Feb deadline)","https://www.dollargeneral.com/about-us/dollar-general-literacy-foundation.html","https://www.dollargeneral.com/about-us/dollar-general-literacy-foundation/grant-application.html","Literacy/education focus; not robotics-specific; accessible grant; broad school eligibility","BAD"),
    ("Best Buy Foundation","National","Corporate Foundation (Electronics Retail)","Best Buy Teen Tech Centers and youth technology programs","Teen Tech Center Grants / Community Grants","$10,000-$100,000","Annual","https://corporate.bestbuy.com/bby-foundation/","https://corporate.bestbuy.com/bby-foundation/","Electronics/tech retailer; teen tech programs; STEM focus for underserved youth; relevant to robotics","MEDIUM"),
    ("GameStop Foundation","National","Corporate Foundation (Gaming Retail)","GameStop Foundation focuses on youth gaming and STEM","PowerUp Grants","$1,000-$10,000","Annual","https://www.gamestopfoundation.org","https://www.gamestopfoundation.org/grant-application","Gaming/tech adjacent; youth STEM; small grants; accessible for school programs","BAD"),

    # ---- NATIONAL CORPORATE - FINANCIAL SERVICES ----
    ("Vanguard Strong Start for Kids","National","Corporate Foundation (Financial)","Vanguard's early education and youth financial literacy programs","Community Stewardship Grants","$5,000-$50,000","Annual","https://about.vanguard.com/investment-stewardship/","https://about.vanguard.com/vanguard-charitable/","Youth education; financial literacy focus; not robotics-specific; accessible for education programs","MEDIUM"),
    ("Fidelity Charitable","National","Foundation (Financial Services)","Fidelity Charitable is a donor-advised fund sponsor; grants from DAF accounts","Donor-Advised Fund Grants","Varies","Rolling","https://www.fidelitycharitable.org","https://www.fidelitycharitable.org/guidance/philanthropy/nonprofits.html","DAF ecosystem; major donors often give through Fidelity Charitable; worth being registered as eligible org","MEDIUM"),
    ("Charles Schwab Foundation","National","Corporate Foundation (Financial)","Schwab Foundation funds financial literacy and education","Employee Giving Match / Community Grants","$5,000-$50,000","Annual","https://www.aboutschwab.com/schwab-foundation","https://www.aboutschwab.com/schwab-foundation","Financial literacy + education; STEM adjacent; employee giving match program; accessible","MEDIUM"),
    ("BlackRock Foundation","National","Corporate Foundation (Financial)","BlackRock's philanthropic arm focused on economic opportunity","Emergency Savings Initiative / Economic Opportunity","$25,000-$500,000","Annual (RFP)","https://www.blackrock.com/corporate/social-impact","https://www.blackrock.com/corporate/social-impact/blackrock-foundation","Economic mobility focus; large grants; invitation-heavy but has open RFPs; workforce development tie-in","BAD"),
    ("Visa Foundation","National","Corporate Foundation (Financial Technology)","Visa Foundation focuses on economic empowerment and small businesses","Economic Empowerment Grants","$50,000-$1,000,000","Annual (RFP)","https://usa.visa.com/about-visa/visa-foundation.html","https://usa.visa.com/about-visa/visa-foundation.html","Large grants; economic focus; not education-specific; very competitive; primarily invitation-based","BAD"),
    ("Mastercard Foundation","National","Corporate Foundation (Financial Technology)","Mastercard Foundation funds education and economic inclusion globally","Young Africa Works / Education Pathways","$100,000+","Annual (invitation)","https://mastercardfdn.org","https://mastercardfdn.org/our-work/","Primarily Africa-focused education; invitation-only at scale; unlikely for CA high school robotics","BAD"),
    ("PayPal Gives","National","Corporate Foundation (Fintech)","PayPal's charitable giving platform and foundation","PayPal Employee Giving / Community Impact","$5,000-$100,000","Rolling","https://www.paypal.com/us/webapps/mpp/paypal-gives","https://newsroom.paypal.com/us/2021-04-22-PayPal-Commits-to-5-Year-536-Million-Commitment-to-Support-Underrepresented-Small-Businesses-and-Nonprofits","Economic inclusion; fintech/tech adjacent; HQ San Jose CA; SoCal presence; STEM-adjacent programs","MEDIUM"),
    ("Square / Block Foundation","National","Corporate Foundation (Fintech)","Block (Square) focuses on economic empowerment for underserved communities","Community Grants / Economic Empowerment","$10,000-$100,000","Annual","https://block.xyz","https://block.xyz/impact","Economic empowerment; tech company (Jack Dorsey); SF-based; STEM-adjacent; underserved youth focus","MEDIUM"),

    # ---- NATIONAL - DEFENSE / AEROSPACE ADDITIONAL ----
    ("General Dynamics Information Technology Foundation","National","Corporate Foundation (Defense IT)","GDIT supports STEM, veterans, and community programs","STEM Education / Veteran Support Grants","$10,000-$100,000","Annual","https://www.gdit.com","https://www.gdit.com/perspectives/our-people-and-community/","Defense IT contractor; STEM education; veteran/military community support; NJROTC-relevant","GOOD"),
    ("BAE Systems STEM","National","Corporate (Defense)","BAE Systems UK/US defense contractor with STEM outreach programs","STEM School Programs / Apprenticeships","$5,000-$50,000","Annual","https://www.baesystems.com","https://www.baesystems.com/en-us/careers/careers-in-the-us/students-and-graduates/stem-outreach","Major defense contractor; STEM education pipeline; military/government contractor; relevant to NJROTC","GOOD"),
    ("SAIC Foundation","National","Corporate Foundation (Defense/IT)","Science Applications International Corp foundation supports STEM","STEM Education / Military Community Grants","$5,000-$50,000","Annual","https://www.saic.com","https://www.saic.com/who-we-are/our-community","SAIC is major defense/IT contractor; strong STEM + military community support; Virginia HQ; accessible","GOOD"),
    ("Leidos Foundation","National","Corporate Foundation (Defense Technology)","Leidos (defense/tech) has education and community programs","STEM / Military Family Support","$10,000-$100,000","Annual","https://www.leidos.com","https://www.leidos.com/company/citizenship","Defense technology company; STEM education; military family support; Virginia HQ; accessible programs","GOOD"),
    ("Booz Allen Hamilton Foundation","National","Corporate Foundation (Defense Consulting)","Booz Allen supports STEM, veterans, and national security workforce","STEM Workforce / Veteran Programs","$10,000-$100,000","Annual","https://www.boozallen.com","https://www.boozallen.com/e/insight/blog/booz-allen-foundation-mission.html","Defense/cyber consulting firm; STEM education for national security workforce; military-aligned; GOOD fit","GOOD"),

    # ---- NATIONAL - SEMICONDUCTOR / ELECTRONICS ADDITIONAL ----
    ("Marvell Technology Foundation","National","Corporate Foundation (Semiconductor)","Marvell Technology (SSD/networking chips) has STEM education programs","STEM / Education Grants","$10,000-$100,000","Annual","https://www.marvell.com","https://www.marvell.com/company/corporate-responsibility/","Semiconductor company; STEM education; Silicon Valley HQ; accessible school programs","MEDIUM"),
    ("Analog Devices Foundation","National","Corporate Foundation (Semiconductor)","Analog Devices (ADI) makes precision sensors and electronics; strong STEM programs","STEM Education / University Programs","$5,000-$50,000","Annual","https://www.analog.com","https://www.analog.com/en/about-adi/sustainability-responsibility/community.html","Electronics/sensors company; STEM education pipeline; engineering education; accessible","MEDIUM"),
    ("Microchip Technology Foundation","National","Corporate Foundation (Semiconductor)","Microchip Technology makes microcontrollers (used in robotics); education programs","STEM / Engineering Education","$5,000-$25,000","Annual","https://www.microchip.com","https://www.microchip.com/about/company-information","Microcontrollers used in robotics projects; Chandler AZ HQ; STEM education; very relevant to VEX","GOOD"),
    ("ON Semiconductor (onsemi) Foundation","National","Corporate Foundation (Semiconductor)","onsemi (Scottsdale AZ) makes power semiconductors; STEM education","STEM / Power Electronics Education","$5,000-$25,000","Annual","https://www.onsemi.com","https://www.onsemi.com/company/responsibility","Power electronics for motors/robotics; Scottsdale AZ HQ; Phoenix near SoCal; STEM education focus","MEDIUM"),
    ("Lattice Semiconductor","National","Corporate (FPGA/Semiconductor)","Lattice makes FPGAs used in embedded systems; some education programs","STEM / Electronics Education","$5,000-$25,000","Annual","https://www.latticesemi.com","https://www.latticesemi.com/company/corporate-responsibility","FPGAs used in robotics; Hillsboro OR HQ; education programs; smaller but relevant","MEDIUM"),
    ("Renesas Electronics","National","Corporate (Semiconductor)","Renesas makes microcontrollers and auto chips; STEM and robotics education","Robotics / STEM Education","$5,000-$50,000","Annual","https://www.renesas.com","https://www.renesas.com/about/corporate-social-responsibility","Japanese company US-listed; microcontrollers for robotics; STEM education; relevant to VEX","MEDIUM"),

    # ---- NATIONAL - AUTOMOTIVE TECHNOLOGY ADDITIONAL ----
    ("Rivian Foundation","National","Corporate Foundation (EV)","Rivian (EV trucks) has education and environmental programs","STEM / Environmental Education","$10,000-$100,000","Annual","https://www.rivian.com","https://www.rivian.com/foundation","EV startup; STEM education + environmental focus; Irvine CA (OC!) HQ originally; very relevant","GOOD"),
    ("Lucid Motors Foundation","National","Corporate Foundation (EV)","Lucid Motors (luxury EV) based in Newark CA; STEM education programs","STEM / EV Technology Education","$5,000-$50,000","Annual","https://www.lucidmotors.com","https://www.lucidmotors.com/company/community","Luxury EV maker; Newark CA HQ; STEM education; engineering focus; CA-based very relevant","GOOD"),
    ("Waymo (Alphabet) Community","National","Corporate (Autonomous Vehicles)","Waymo (Google's AV company) supports STEM education and safety","STEM / AV Safety Education","$10,000-$100,000","Annual","https://waymo.com","https://waymo.com/company/","Autonomous vehicles; robotics-adjacent; Alphabet subsidiary; Mountain View CA; STEM focus","MEDIUM"),
    ("Aurora Innovation","National","Corporate (Autonomous Vehicles)","Aurora develops self-driving trucks; STEM education and engineering","STEM / Autonomous Systems Education","$5,000-$25,000","Annual","https://aurora.tech","https://aurora.tech/company/community","Self-driving tech; robotics-adjacent; Pittsburgh PA + Dallas TX HQ; STEM education programs","MEDIUM"),
    ("Zoox (Amazon)","National","Corporate (Autonomous Vehicles)","Zoox (Amazon's robotaxi subsidiary) has STEM outreach programs","STEM / Robotics Education","$10,000-$50,000","Annual","https://zoox.com","https://zoox.com/","Amazon subsidiary doing robotaxis; Foster City CA HQ; STEM/robotics education very relevant","GOOD"),

    # ---- NATIONAL - COMMUNICATIONS / TELECOM ADDITIONAL ----
    ("T-Mobile Foundation","National","Corporate Foundation (Telecom)","T-Mobile's charitable arm funds education and connectivity","Hometown Grants / Education Programs","$5,000-$50,000","Annual (Rolling)","https://www.t-mobile.com/responsibility","https://www.t-mobile.com/responsibility/philanthropic-giving","Connected device/education focus; Hometown Grant program for nonprofits/schools; accessible","GOOD"),
    ("AT&T Foundation","National","Corporate Foundation (Telecom)","AT&T Foundation funds education, workforce, and STEM","AT&T Aspire (STEM/Education)","$10,000-$100,000","Annual","https://about.att.com/csr/home/philanthropy","https://about.att.com/csr/home/philanthropy/att-foundation","STEM + education; AT&T Aspire program; Fortune 500 funder; Dallas TX HQ; accessible school programs","GOOD"),
    ("Verizon Foundation","National","Corporate Foundation (Telecom)","Verizon Foundation funds digital literacy and education","Verizon Innovative Learning (STEM)","$10,000-$100,000","Annual","https://www.verizon.com/about/responsibility/charitable-giving","https://www.verizoninnovativelearning.com","Digital literacy and STEM; Verizon Innovative Learning for Title I schools; accessible + relevant","GOOD"),
    ("Comcast NBCUniversal Foundation","National","Corporate Foundation (Media/Cable)","Comcast's philanthropic arm focused on digital equity and education","Internet Essentials / Digital Equity Grants","$10,000-$100,000","Annual","https://corporate.comcast.com/impact/comcast-nbcuniversal-foundation","https://corporate.comcast.com/impact/comcast-nbcuniversal-foundation/grants","Digital equity + education; Philadelphia HQ; accessible grant programs; NBC Universal media reach","MEDIUM"),
    ("Charter Communications / Spectrum Foundation","National","Corporate Foundation (Cable/Telecom)","Charter Spectrum supports digital literacy and education","Spectrum Digital Education","$5,000-$50,000","Annual","https://corporate.charter.com/our-impact","https://corporate.charter.com/our-impact/spectrum-digital-education","Digital education focus; STEM-adjacent; Stamford CT HQ; accessible for school programs","MEDIUM"),

    # ---- NATIONAL - INSURANCE / FINANCIAL ADDITIONAL ----
    ("State Farm Companies Foundation","National","Corporate Foundation (Insurance)","State Farm supports education, safety, and community development","Neighborhood Assist / Education Grants","$25,000-$50,000","Annual (voting)","https://www.statefarm.com/about-us/state-farm-companies-foundation","https://neighborhoodassist.com","Education + community; Neighborhood Assist online voting competition; open application; accessible","MEDIUM"),
    ("Allstate Foundation","National","Corporate Foundation (Insurance)","Allstate Foundation focuses on youth empowerment and community safety","Purple Purse / Youth Empowerment","$10,000-$100,000","Annual","https://www.allstatefoundation.org","https://www.allstatefoundation.org/what-we-do","Youth empowerment programs; community safety focus; Northbrook IL HQ; accessible programs","MEDIUM"),
    ("USAA Foundation","National","Corporate Foundation (Military Insurance)","USAA serves military families; foundation supports military community","Military Family / Education Grants","$10,000-$100,000","Annual","https://www.usaa.com/inet/wc/about_us_usaa_giving","https://www.usaa.com/inet/wc/about_us_usaa_giving","Military insurance company; NJROTC directly relevant; military family support; San Antonio TX HQ","GOOD"),
    ("Armed Forces Benefit Association Foundation","National","Military Foundation","AFBA supports military members and their families","Military Family Support / Education","$5,000-$25,000","Annual","https://www.afba.com","https://www.afba.com/foundation","Military-focused nonprofit; NJROTC relevant; education for military families; accessible programs","GOOD"),

    # ---- NATIONAL - FOOD/BEVERAGE CORPORATE ----
    ("PepsiCo Foundation","National","Corporate Foundation (Food/Beverage)","PepsiCo Foundation funds food security, water, and education","STEM / Education Grants","$25,000-$500,000","Annual","https://www.pepsico.com/our-impact/philanthropy","https://www.pepsico.com/our-impact/philanthropy/pepsico-foundation","Large corporate funder; education programs; Purchase NY HQ; accessible grant programs","MEDIUM"),
    ("Coca-Cola Foundation","National","Corporate Foundation (Beverage)","The Coca-Cola Foundation funds education, water, and community","Education Grants","$25,000-$200,000","Annual (LOI)","https://www.coca-colacompany.com/shared-future/coca-cola-foundation","https://www.coca-colacompany.com/shared-future/coca-cola-foundation","Large corporate funder; education focus; Atlanta GA HQ; LOI-based but open process; accessible","MEDIUM"),
    ("Kellogg Foundation","National","Foundation (Food/Philanthropy)","W.K. Kellogg Foundation funds children, families, and communities","Education / Youth Development Grants","$50,000-$1,000,000","Annual (RFP)","https://www.wkkf.org","https://www.wkkf.org/grants/grant-opportunities","Major national funder; youth + education; Battle Creek MI; large grants but competitive; accessible","MEDIUM"),
    ("General Mills Foundation","National","Corporate Foundation (Food)","General Mills Foundation focuses on hunger, education, and sustainability","Youth Education / Community Grants","$5,000-$100,000","Annual","https://www.generalmills.com/responsibility","https://www.generalmills.com/responsibility/philanthropy","Youth education focus; Minneapolis MN HQ; accessible programs; broad school eligibility","MEDIUM"),
    ("Kraft Heinz Company Foundation","National","Corporate Foundation (Food)","Kraft Heinz funds hunger, education, and community programs","Community Grants / Education","$5,000-$50,000","Annual","https://www.kraftheinzcompany.com/esg/social/communities.html","https://www.kraftheinzcompany.com/esg/social/communities.html","Food + community focus; education programs; Chicago HQ; accessible for school programs","MEDIUM"),

    # ---- NATIONAL - HEALTHCARE ADDITIONAL ----
    ("Baxter International Foundation","National","Corporate Foundation (Healthcare)","Baxter (IV/infusion medical devices) supports STEM and communities","STEM / Healthcare Education","$10,000-$100,000","Annual","https://www.baxter.com/baxter-newsroom/community-responsibility","https://www.baxter.com/baxter-newsroom/community-responsibility","Medical devices; STEM education pipeline; Deerfield IL HQ; accessible for school programs","MEDIUM"),
    ("Becton Dickinson Foundation","National","Corporate Foundation (Medical Devices)","BD (medical devices/diagnostics) supports healthcare STEM education","STEM Healthcare Education","$10,000-$100,000","Annual","https://www.bd.com/en-us/company/social-responsibility","https://www.bd.com/en-us/company/social-responsibility","Medical device maker; STEM education; Franklin Lakes NJ HQ; accessible programs","MEDIUM"),
    ("Zimmer Biomet Foundation","National","Corporate Foundation (Medical Devices)","Zimmer Biomet (orthopaedic devices) has STEM and community programs","STEM / Healthcare Community","$5,000-$50,000","Annual","https://www.zimmerbiomet.com/en/corporate-responsibility.html","https://www.zimmerbiomet.com/en/corporate-responsibility.html","Orthopaedic devices; robotics-adjacent (surgical robots); Warsaw IN HQ; STEM education","MEDIUM"),
    ("Stryker Foundation","National","Corporate Foundation (Medical Devices)","Stryker (medical/surgical devices + robots) has STEM programs","STEM / Surgical Robotics Education","$5,000-$100,000","Annual","https://www.stryker.com/us/en/about/responsibility.html","https://www.stryker.com/us/en/about/responsibility.html","Makes surgical robots (Mako); robotics-adjacent; Kalamazoo MI HQ; STEM education programs","GOOD"),
    ("Intuitive Foundation","National","Corporate Foundation (Surgical Robotics)","Intuitive Surgical (da Vinci robot) has STEM and robotics programs","STEM / Robotics Education","$10,000-$100,000","Annual","https://www.intuitive.com/en-us/about-us/foundation","https://www.intuitive.com/en-us/about-us/foundation","Makes da Vinci surgical robot; EXTREMELY relevant to robotics; Sunnyvale CA HQ; excellent fit","GOOD"),

    # ---- NATIONAL - ENERGY/UTILITIES ADDITIONAL ----
    ("Exelon Foundation","National","Corporate Foundation (Energy/Utility)","Exelon (electric utility) has STEM education programs","STEM / Energy Education","$10,000-$100,000","Annual","https://www.exeloncorp.com/community","https://www.exeloncorp.com/community","Major electric utility; STEM education; Chicago IL HQ; accessible programs; energy/engineering focus","MEDIUM"),
    ("Dominion Energy Charitable Foundation","National","Corporate Foundation (Utility)","Dominion Energy funds community, education, and environment","Education / Community Grants","$5,000-$50,000","Annual (Rolling)","https://www.dominionenergy.com/company/in-the-community","https://www.dominionenergy.com/company/in-the-community","Electric utility; STEM education; Richmond VA HQ; accessible rolling grants; school programs","MEDIUM"),
    ("Duke Energy Foundation","National","Corporate Foundation (Utility)","Duke Energy supports education and environment in its service territory","STEM / Workforce Education","$5,000-$100,000","Annual","https://www.duke-energy.com/home/products/duke-energy-foundation","https://www.duke-energy.com/home/products/duke-energy-foundation","Electric utility; STEM education; Charlotte NC HQ; service territory focus but accessible","MEDIUM"),
    ("NextEra Energy Foundation","National","Corporate Foundation (Utility)","NextEra (Florida Power & Light / wind/solar) funds STEM education","STEM / Clean Energy Education","$10,000-$100,000","Annual","https://www.nexteraenergy.com/community.html","https://www.nexteraenergy.com/community.html","Largest US utility; STEM + clean energy education; Juno Beach FL HQ; accessible programs","MEDIUM"),
    ("Southern California Edison Foundation","Local/Regional","Corporate Foundation (Utility)","SCE is Troy's local electric utility; strong STEM/education programs in service area","STEM Workforce / Education Grants","$5,000-$100,000","Annual","https://www.sce.com/about-sce/community/foundation","https://www.sce.com/about-sce/community/foundation","DIRECTLY serves Fullerton/OC; STEM workforce development; very accessible for local schools; HIGH PRIORITY","GOOD"),
    ("Southern California Gas Foundation","Local/Regional","Corporate Foundation (Utility)","SoCalGas (Sempra) foundation supports energy + STEM in SoCal","Energy/STEM Education Grants","$5,000-$50,000","Annual","https://www.socalgas.com/sustainability/community","https://www.socalgas.com/sustainability/community","Directly serves OC/Fullerton; STEM education; accessible for local schools; utility community grants","GOOD"),

    # ---- CALIFORNIA STATE PROGRAMS ADDITIONAL ----
    ("California Education Foundation (CEF)","State","State-Affiliated Foundation","California Teachers Association foundation for education innovation","Education Innovation Grants","$5,000-$50,000","Annual","https://cef.org","https://cef.org/grants","CTA-affiliated; California teachers + schools; education innovation; accessible state-level grants","MEDIUM"),
    ("California STEM Learning Network (CSLNet)","State","State STEM Network","CSLNet is California's STEM education intermediary network","STEM Network / Capacity Building","$5,000-$25,000","Annual","https://www.cslnet.org","https://www.cslnet.org/resources","California STEM intermediary; connects schools to resources; relevant for Troy STEM programs","MEDIUM"),
    ("California Career Pathways Trust","State","State Grant Program","CA Dept of Ed career pathways including engineering and manufacturing","Career Pathways / CTE Grants","$100,000-$1,000,000","Annual (RFP)","https://www.cde.ca.gov/ci/ct/gi/cptgrantinfo.asp","https://www.cde.ca.gov/ci/ct/gi/cptgrantinfo.asp","CTE engineering pathways; CA Dept of Ed administered; school-district eligible; large grants","GOOD"),
    ("California Partnership Academies","State","State Grant Program","CA Partnership Academies link schools with industry; engineering academies eligible","Partnership Academy Grants","$50,000-$100,000","Annual","https://www.cde.ca.gov/ci/gs/hs/cpaoverviewinfo.asp","https://www.cde.ca.gov/ci/gs/hs/cpaoverviewinfo.asp","CA high school partnership academies; engineering/technology focus; accessible for Troy HS","GOOD"),
    ("California Coastal Commission Education","State","State Agency (Environment)","CA Coastal Commission has STEM/environment education grant programs","Coastal Education Grants","$5,000-$25,000","Annual","https://www.coastal.ca.gov","https://www.coastal.ca.gov/publiced/grants.html","Environmental/STEM education; CA state agency; accessible for schools near coast","MEDIUM"),
    ("CalRecycle Green Schools","State","State Agency (Environment)","California Dept of Resources Recycling and Recovery school programs","Green Schools / STEM Environment","$5,000-$25,000","Annual","https://calrecycle.ca.gov","https://calrecycle.ca.gov/schools/","Environmental STEM; California schools eligible; green school programs; sustainability focus","MEDIUM"),

    # ---- ORANGE COUNTY / SOUTHERN CALIFORNIA LOCAL ----
    ("Orange County United Way","Local","Community Organization","OC United Way funds education, health, and financial stability in OC","Education Impact Grants","$5,000-$50,000","Annual","https://www.unitedwayoc.org","https://www.unitedwayoc.org/grants/","Directly serves OC; education focus; STEM-adjacent; accessible for OC school programs","GOOD"),
    ("Anaheim Community Foundation","Local","Community Foundation","Community foundation for Anaheim and surrounding cities","Community Grants","$2,500-$25,000","Annual","https://www.anaheimcf.org","https://www.anaheimcf.org/grants","Adjacent to Fullerton; community education grants; accessible; OC local funder","GOOD"),
    ("Brea Community Fund","Local","Community Foundation","Brea (adjacent to Fullerton) community foundation grants","Community Education Grants","$1,000-$10,000","Annual","https://www.breacf.org","https://www.breacf.org","Adjacent Brea CA; local community grants; education-focused; accessible for nearby schools","GOOD"),
    ("Placentia Community Foundation","Local","Community Foundation","Placentia (adjacent to Fullerton) community foundation","Community Grants","$1,000-$10,000","Annual","https://www.placentiacf.org","https://www.placentiacf.org","Adjacent to Fullerton CA; community education grants; accessible for local schools","GOOD"),
    ("Yorba Linda Community Foundation","Local","Community Foundation","Yorba Linda community foundation grants for education","Community Education Grants","$1,000-$10,000","Annual","https://www.yorbalindacf.org","https://www.yorbalindacf.org","Adjacent to Fullerton; education grants; accessible; OC north local funder","GOOD"),
    ("La Habra Community Foundation","Local","Community Foundation","La Habra (adjacent to Fullerton) community foundation","Community Grants","$1,000-$10,000","Annual","https://www.lahabracf.org","https://www.lahabracf.org","Adjacent to Fullerton CA; local community grants; accessible for nearby Troy HS area","GOOD"),
    ("NOCCCD Foundation (North OC Community College)","Local","Community College Foundation","North Orange County Community College District foundation","Education / STEM Grants","$5,000-$25,000","Annual","https://www.nocccd.edu","https://www.nocccd.edu/foundation","Local community college district; Fullerton College + Cypress College; STEM education pathway","GOOD"),
    ("Fullerton College Foundation","Local","Community College Foundation","Fullerton College (adjacent to Troy HS) foundation supports education","Student / STEM Education Grants","$1,000-$10,000","Annual","https://www.fullcoll.edu","https://www.fullcoll.edu/foundation","Adjacent to Troy HS; shared student population; STEM education; very accessible local funder","GOOD"),
    ("Chapman University Foundation","Local","University Foundation","Chapman University (Orange CA, adjacent) foundation for education","STEM / Education Grants","$5,000-$25,000","Annual","https://www.chapman.edu","https://www.chapman.edu/giving","Adjacent OC university; STEM education; Orange CA; accessible for local high school programs","MEDIUM"),
    ("Cal Poly Pomona Foundation","Regional","University Foundation","Cal Poly Pomona (engineering school near OC) foundation","Engineering / STEM Education","$5,000-$25,000","Annual","https://www.cpp.edu","https://www.cpp.edu/foundation/","Adjacent engineering school; strong engineering/robotics focus; Pomona CA; STEM education focus","GOOD"),

    # ---- NATIONAL - FOUNDATIONS ADDITIONAL ----
    ("Schulz Family Foundation","National","Private Foundation (Tech/Philanthropy)","Howard Schulz (Starbucks) family foundation focused on opportunity","Youth Opportunity / Education","$50,000-$500,000","Annual (invitation)","https://www.schulzfamilyfoundation.org","https://www.schulzfamilyfoundation.org","Primarily invitation-based; youth opportunity; education focus; Seattle WA; competitive","BAD"),
    ("Schmidt Futures","National","Foundation (Tech Philanthropy)","Eric Schmidt (Google) foundation for STEM and education innovation","STEM / Science Education","$50,000-$1,000,000","Annual (invitation)","https://www.schmidtfutures.com","https://www.schmidtfutures.com/our-work/","STEM + science focus; Google/tech-aligned; primarily invitation-based; STEM education tie-in","BAD"),
    ("Ewing Marion Kauffman Foundation","National","Foundation (Entrepreneurship)","Kauffman Foundation supports entrepreneurship and STEM education","STEM / Entrepreneurship Education","$25,000-$500,000","Annual (RFP)","https://www.kauffman.org","https://www.kauffman.org/grants/","Entrepreneurship + STEM; Kansas City MO; competitive but has open RFPs; education focus","MEDIUM"),
    ("Conrad N. Hilton Foundation","National","Private Foundation","Hilton Foundation supports humanitarian causes including education","Education / Youth Development","$100,000-$5,000,000","Annual (invitation)","https://www.hiltonfoundation.org","https://www.hiltonfoundation.org/grants","Primarily invitation-based; education and youth development; Westlake Village CA; large grants","BAD"),
    ("Packard Foundation (David and Lucile)","National","Private Foundation (Tech)","David & Lucile Packard Foundation (HP co-founder) funds science + education","Science / Education Grants","$100,000-$5,000,000","Annual (invitation)","https://www.packard.org","https://www.packard.org/grants-and-investments/for-grantseekers/","HP co-founder; science + education; Los Altos CA; primarily invitation-based; large foundation","BAD"),
    ("Moore Foundation (Gordon and Betty)","National","Private Foundation (Tech)","Gordon Moore (Intel co-founder) foundation funds science and environment","Science / STEM Research","$100,000-$5,000,000","Annual (invitation)","https://www.moore.org","https://www.moore.org/grant-portfolio","Intel co-founder; science + STEM; Palo Alto CA; primarily invitation-based; large foundation","BAD"),
    ("Robertson Foundation","National","Private Foundation","Robertson Foundation focuses on education and human rights","Education Grants","$50,000-$1,000,000","Annual (invitation)","https://robertsonfoundation.org","https://robertsonfoundation.org/grant-making/","Education focus; primarily invitation; New York; less accessible for high school programs","BAD"),
    ("Overdeck Family Foundation","National","Private Foundation (Finance/Education)","John Overdeck (hedge fund) foundation for STEM education","STEM / Early Education Grants","$50,000-$500,000","Annual (invitation)","https://www.overdeck.org","https://www.overdeck.org/grantees/","STEM education; primarily invitation; NYC; focused on K-12 STEM innovation; accessible in theory","MEDIUM"),
    ("Simons Foundation","National","Private Foundation (Math/Science)","Jim Simons (mathematician/hedge fund) for math and science education","Math / Science Education","$50,000-$5,000,000","Annual (invitation/RFP)","https://www.simonsfoundation.org","https://www.simonsfoundation.org/funding-opportunities/","Math + science education; NYC; some open programs; STEM-focused; competitive","MEDIUM"),
    ("AMS (American Mathematical Society) Foundation","National","Professional Society Foundation","AMS supports math education at all levels","Math Education / Outreach Grants","$5,000-$25,000","Annual","https://www.ams.org","https://www.ams.org/programs/programs-for-students","Math outreach grants; STEM adjacent; accessible for school programs; robotics uses math","MEDIUM"),
]

with open(output_file, 'a', newline='', encoding='utf-8-sig') as f:
    writer = csv.writer(f)
    writer.writerows(entries)

print(f"Batch 10 complete: {len(entries)} new entries appended")
