#!/usr/bin/env python3
# Batch 9: Final push to 1000+ — Fortune 500 mid-tier, additional sectors, employee matching,
# scholarships, corporate sponsors, additional SoCal/CA, remaining categories

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Additional Fortune 500 corporate foundations
("3M Foundation - Education Program","National","Corporate (Manufacturing)","3M funds additional K-12 STEM teacher development and classroom innovation beyond Inspiring Innovations","3M Teacher Development Grants","$500-$5,000","Annual","https://www.3m.com/3M/en_US/gives-us/","https://www.3m.com/3M/en_US/gives-us/","Teacher development grants; no 501c3 needed for some programs; 3M has Fullerton area employees","GOOD"),
("Corning Foundation","National","Corporate (Technology/Glass)","Corning funds STEM education and materials science programs; glass and fiber optics manufacturer","STEM Materials Science Education","$5,000-$100,000","Annual","https://www.corning.com","https://www.corning.com/worldwide/en/sustainability/social-impact/corning-foundation.html","Optical fiber and glass technology; STEM education; Corning NY HQ with national programs","MEDIUM"),
("Illinois Tool Works STEM","National","Corporate (Manufacturing)","ITW funds STEM education through employee volunteer programs and community grants","Employee Volunteer STEM Grants","$500-$5,000","Annual","https://www.itw.com","https://www.itw.com/corporate-responsibility/","Manufacturing conglomerate; STEM education; employee volunteer grants accessible","MEDIUM"),
("Hubbell Foundation","National","Corporate (Manufacturing)","Hubbell electrical products; funds STEM education and electrical engineering career pipeline","STEM Electrical Engineering","$5,000-$50,000","Annual","https://www.hubbell.com","https://www.hubbell.com/hubbell/en/about-us/sustainability","Electrical products; STEM engineering; career pipeline to electrical and power systems engineering","MEDIUM"),
("Rockwell Collins Foundation","National","Corporate (Aerospace/Technology)","Rockwell Collins (now Collins Aerospace/RTX) additional foundation programs beyond Collins Aerospace entry","Aerospace Technology STEM","$5,000-$50,000","Annual","https://www.collinsaerospace.com","https://www.collinsaerospace.com/community","Aerospace technology STEM; additional Collins Aerospace foundation programs","GOOD"),
("Delphi Technologies Foundation","National","Corporate (Automotive Technology)","Delphi Technologies (BorgWarner) funds STEM education and advanced automotive engineering","Automotive STEM Engineering","$5,000-$50,000","Annual","https://www.borgwarner.com","https://www.borgwarner.com/sustainability","Automotive technology; STEM engineering; EV powertrain pipeline to engineering careers","MEDIUM"),
("SPX Technologies Foundation","National","Corporate (Manufacturing)","SPX funds STEM education and industrial technology programs; vehicle service equipment","STEM Industrial Technology","$5,000-$50,000","Annual","https://www.spx.com","https://www.spx.com/corporate-social-responsibility/","Industrial technology; STEM education; Charlotte NC HQ with national programs","MEDIUM"),
("Crane Holdings Foundation","National","Corporate (Manufacturing)","Crane Co funds STEM education and industrial engineering; payment technology and industrial products","STEM Industrial Engineering","$5,000-$50,000","Annual","https://www.craneco.com","https://www.craneco.com/corporate-responsibility/","Industrial products; STEM engineering; Stamford CT HQ with national programs","MEDIUM"),
("National Oilwell Varco Foundation","National","Corporate (Energy Equipment)","NOV makes drilling equipment; funds STEM education in energy communities; Houston TX HQ","STEM Energy Equipment","$5,000-$50,000","Annual","https://www.nov.com","https://www.nov.com/company/sustainability","Oil drilling equipment; STEM education near facilities; Houston TX HQ with CA energy sector connections","MEDIUM"),
("Flowserve Foundation","National","Corporate (Manufacturing)","Flowserve makes pumps and flow control; funds STEM education and engineering programs","STEM Flow Engineering","$5,000-$50,000","Annual","https://www.flowserve.com","https://www.flowserve.com/sustainability","Flow control engineering; STEM education; Irving TX HQ with national programs","MEDIUM"),
("Littelfuse Foundation","National","Corporate (Electronics)","Littelfuse makes electronic components and circuit protection; funds STEM education","STEM Electronics Education","$5,000-$50,000","Annual","https://www.littelfuse.com","https://www.littelfuse.com/about-littelfuse/sustainability.aspx","Electronic components; STEM education; Chicago IL HQ; electronics directly relevant to robotics","MEDIUM"),
("Vishay Intertechnology Foundation","National","Corporate (Electronics)","Vishay makes electronic components; funds STEM education near facilities","STEM Electronics Grants","$5,000-$25,000","Annual","https://www.vishay.com","https://www.vishay.com/about/corporate-responsibility/","Electronic components manufacturer; STEM education; Malvern PA HQ","MEDIUM"),
("Amphenol Foundation","National","Corporate (Electronics)","Amphenol makes connectors and sensors; funds STEM education and engineering programs","STEM Connector Engineering","$5,000-$50,000","Annual","https://www.amphenol.com","https://www.amphenol.com/en/corporate-responsibility","Connectors and sensors; STEM engineering education; Wallingford CT HQ; connectors used in robotics","GOOD"),
("TE Connectivity Foundation","National","Corporate (Electronics)","TE Connectivity makes sensors and connectors for industrial and automotive applications","STEM Sensor Engineering","$5,000-$100,000","Annual","https://www.te.com","https://www.te.com/usa-en/about-te/corporate-responsibility.html","Sensors and connectors used in robotics; STEM engineering education; Berwyn PA HQ with CA operations","GOOD"),
("Molex Foundation","National","Corporate (Electronics)","Molex makes electronic connectors and fiber optic solutions; funds STEM education","STEM Electronics Connectivity","$5,000-$50,000","Annual","https://www.molex.com","https://www.molex.com/content/dam/molex/molex-dot-com/products/normal/our-company/csr/","Electronic connectors; STEM education; Lisle IL HQ; connectors directly used in robotics builds","GOOD"),
("National Semiconductor Foundation","National","Corporate (Technology)","Additional semiconductor company foundations - broadly relevant to robotics electronics","STEM Semiconductor Education","$5,000-$50,000","Annual","https://www.semiconductor.org","https://www.semiconductors.org/","Semiconductor industry association foundation; STEM education pipeline; national programs","MEDIUM"),
("SEMI Foundation (Semiconductor Equipment)","National","Industry Association","SEMI funds STEM workforce development for semiconductor industry; global industry association","STEM Semiconductor Workforce","$5,000-$50,000","Annual","https://www.semi.org","https://www.semi.org/en/communities/semi-foundation","Semiconductor equipment; STEM workforce; Milpitas CA HQ; directly relevant to electronic design in robotics","GOOD"),
("Global Semiconductor Alliance Foundation","National","Industry Association","GSA funds STEM education and semiconductor industry workforce; innovation ecosystem","STEM Innovation Workforce","$5,000-$25,000","Annual","https://www.gsaglobal.org","https://www.gsaglobal.org/","Semiconductor alliance; STEM education; Dallas TX HQ with CA members","MEDIUM"),
# Additional employee matching / giving programs
("ADP Foundation","National","Corporate (Technology)","ADP payroll technology; funds education and workforce development; employee matching program","Education and Workforce Grants","$5,000-$100,000","Annual","https://www.adp.com","https://www.adp.com/about-adp/corporate-responsibility.aspx","Payroll technology; education and workforce; employee matching; Roseland NJ HQ with CA offices","MEDIUM"),
("Fiserv Foundation","National","Corporate (Technology/Fintech)","Fiserv funds financial technology education and workforce; STEM career pipeline","Fintech STEM Education","$5,000-$50,000","Annual","https://www.fiserv.com","https://www.fiserv.com/en-us/about-fiserv/corporate-citizenship.html","Financial technology; STEM education; Milwaukee WI HQ with national programs","MEDIUM"),
("NCR Foundation","National","Corporate (Technology)","NCR makes payment technology and digital banking solutions; funds STEM education","STEM Technology Education","$5,000-$50,000","Annual","https://www.ncr.com","https://www.ncr.com/company/sustainability","Payment technology; STEM education; Atlanta GA HQ with national programs","MEDIUM"),
("Jabil Foundation","National","Corporate (Manufacturing)","Jabil is contract manufacturer of electronics; funds STEM education in manufacturing communities","STEM Manufacturing Education","$5,000-$100,000","Annual","https://www.jabil.com","https://www.jabil.com/about/sustainability.html","Electronics contract manufacturer; STEM education; St. Petersburg FL HQ with CA manufacturing","GOOD"),
("Flex Ltd Foundation","National","Corporate (Manufacturing)","Flex (formerly Flextronics) is global electronics manufacturer; funds STEM education and workforce","STEM Electronics Manufacturing","$5,000-$100,000","Annual","https://www.flex.com","https://www.flex.com/our-impact","Electronics manufacturing; STEM education; San Jose CA HQ near Fullerton; CA operations","GOOD"),
("Celestica Foundation","National","Corporate (Manufacturing)","Celestica is electronics manufacturer; funds STEM education programs in manufacturing communities","STEM Electronics Education","$5,000-$50,000","Annual","https://www.celestica.com","https://www.celestica.com/corporate-responsibility","Electronics manufacturing; STEM education; Toronto Canada with major US CA operations","MEDIUM"),
("Benchmark Electronics Foundation","National","Corporate (Manufacturing)","Benchmark Electronics is contract manufacturer; funds STEM education programs","STEM Manufacturing Education","$1,000-$25,000","Annual","https://www.bench.com","https://www.bench.com/sustainability","Contract manufacturing; STEM education; Angleton TX HQ with CA operations","MEDIUM"),
# Additional scholarships directly for cadets
("FIRST Robotics Scholarship Database","National","Education (Scholarships)","Aggregated FIRST-affiliated scholarships many applicable to VEX alumni; comprehensive database","FIRST Alumni Scholarships","$500-$25,000","Annual","https://www.firstinspires.org/alumni/scholarships","https://www.firstinspires.org/alumni/scholarships","Many FIRST scholarships apply to VEX alumni; promote scholarship database to graduating cadets","GOOD"),
("VEX/RECF Alumni Scholarship Fund","National","Foundation (Robotics)","RECF administers scholarship programs for VEX alumni pursuing STEM degrees; directly applicable","RECF Alumni Scholarships","$1,000-$25,000","Annual","https://recf.org/teams/for-participants/scholarships","https://recf.org/teams/for-participants/scholarships","Most directly applicable scholarship for Troy VEX graduating seniors pursuing STEM; HIGH PRIORITY","GOOD"),
("Astronaut Scholarship Foundation","National","Foundation (STEM)","Founded by Mercury astronauts; funds STEM scholarships for top college students in STEM fields","Astronaut Scholarships","$15,000/yr","Annual","https://www.astronautscholarship.org","https://www.astronautscholarship.org/scholarship.html","Founded by Mercury astronauts; STEM scholarship; aerospace career pipeline for JROTC cadets entering college","GOOD"),
("Society of Exploration Geophysicists Foundation","National","Professional Society","SEG funds STEM scholarships for geophysics and related earth science students","Geophysics STEM Scholarships","$1,000-$10,000","Annual","https://www.seg.org","https://seg.org/Scholarships","Earth science STEM scholarships; engineering pipeline; geophysical exploration technology","MEDIUM"),
("Achievement Rewards for College Scientists (ARCS)","National","Foundation (STEM)","ARCS Foundation funds college scholars in STEM; SoCal chapter supports CA students","ARCS Scholar Awards","$5,000-$15,000","Annual","https://www.arcsfoundation.org","https://www.arcsfoundation.org/become-a-scholar","STEM scholars; SoCal chapter for CA students; graduating TroyVEX seniors entering college STEM","GOOD"),
# Additional local SoCal small businesses and banks
("Southern California Gas Company (SoCalGas) STEM 2","Local","Corporate (Utility)","SoCalGas serves Fullerton directly; additional STEM workforce programs beyond prior entry","STEM Energy Workforce CA","$5,000-$25,000","Annual","https://www.socalgas.com","https://www.sempra.com/performance/community-giving","SoCalGas direct Fullerton service; STEM workforce pipeline; additional programs beyond community grants","MEDIUM"),
("The Gas Company Foundation","Local","Corporate (Utility)","SoCalGas (The Gas Company) funds OC and LA community programs; energy efficiency and education","OC LA Education and Community","$1,000-$10,000","Annual","https://www.socalgas.com","https://www.socalgas.com/about-us/community","The Gas Company brand; OC and LA community education; Fullerton is in service territory","MEDIUM"),
("Southern California Telephone Company","Local","Corporate (Telecom)","AT&T SoCal (formerly Pacific Bell/SBC) funds STEM education and digital equity in SoCal communities","SoCal STEM Digital Education","$5,000-$50,000","Annual","https://about.att.com","https://about.att.com/csr/home","AT&T SoCal presence; STEM digital education; Fullerton is in AT&T service territory","MEDIUM"),
("Cox Communications Orange County","Local","Corporate (Telecom)","Cox Communications serves OC; funds education and STEM programs in OC communities","OC Education and STEM","$1,000-$25,000","Annual","https://www.cox.com","https://cox.com/residential/local-news-community/charities.html","OC cable/internet provider; education and STEM community grants; direct Fullerton service area","GOOD"),
("Charter Communications / Spectrum Foundation (SoCal)","Regional","Corporate (Telecom)","Spectrum serves SoCal including OC; Spectrum Digital Education funds K-12 STEM and digital literacy","Spectrum Digital Education / K-12","$5,000-$50,000","Annual","https://www.spectrum.com","https://corporate.charter.com/corporate-social-responsibility/","SoCal cable/internet provider; K-12 digital education; Spectrum serves Fullerton area","GOOD"),
# Additional non-profits and foundations
("Afterschool Alliance","National","Education Nonprofit","National advocacy and grant organization for afterschool STEM programs; connects to federal funding streams","Afterschool STEM Grants","$5,000-$50,000","Annual","https://www.afterschoolalliance.org","https://www.afterschoolalliance.org/","Afterschool STEM advocacy; connects programs to federal funding; partner for 21st CCLC applications","MEDIUM"),
("National Alliance for Public Charter Schools Foundation","National","Education Nonprofit","Funds STEM and innovation in public charter schools; Troy is public HS not charter but allies useful","STEM Charter Innovation","$10,000-$100,000","Annual","https://www.publiccharters.org","https://www.publiccharters.org/","Charter school focus but public school STEM innovation grant adjacent; advocacy partner","MEDIUM"),
("Partnership for 21st Century Learning","National","Education Nonprofit","Funds 21st century skills education including STEM and critical thinking for K-12","21st Century Skills Grants","$5,000-$50,000","Annual","https://www.battelleforkids.org","https://www.battelleforkids.org/","21st century skills; STEM critical thinking; Battelle for Kids affiliation; national programs","MEDIUM"),
("America STEM Academy Foundation","National","Education Nonprofit","Funds STEM academies and specialized STEM education programs for K-12 youth","STEM Academy Grants","$5,000-$50,000","Annual","https://www.amsaonline.org","https://www.amsaonline.org/","STEM academies and specialized programs; K-12 focus; national programs","MEDIUM"),
("Siemens STEM Academy","National","Corporate (Technology)","Siemens STEM Academy provides resources and grants for K-12 STEM education programs","Siemens STEM Academy Grants","$1,000-$25,000","Annual","https://www.siemens.com/us/en/company/about/usa-foundations.html","https://www.siemens.com/us/en/company/about/usa-foundations.html","Siemens STEM Academy directly funds K-12 STEM; submit through Siemens academic programs","GOOD"),
("Lemelson Foundation","National","Foundation (STEM/Invention)","Lemelson funds invention and STEM education; InvenTeams grants for HS students to invent","InvenTeams Grants","Up to $10,000","Annual","https://lemelson.mit.edu","https://lemelson.mit.edu/inventeams","InvenTeams for high school invention projects; robotics adjacent; MIT-affiliated; APPLY NOW","GOOD"),
("Conrad Spirit of Innovation Challenge","National","Education STEM Competition)","Conrad Foundation funds student innovation competitions with prize grants for STEM projects","Innovation Challenge Grants","$1,000-$10,000","Annual","https://www.conradchallenge.org","https://www.conradchallenge.org/","Student innovation challenge; STEM competition grants; high school students eligible; robotics category","GOOD"),
("ExploraVision (Toshiba/NSTA)","National","Corporate/Education Partnership","Toshiba and NSTA co-sponsor ExploraVision STEM competition for K-12; cash prizes and grants","ExploraVision Competition Grants","$500-$10,000","Annual","https://www.exploravision.org","https://www.exploravision.org/","K-12 STEM competition; Toshiba and NSTA collaboration; prizes for winning teams","GOOD"),
("Science Olympiad Foundation","National","Education Nonprofit","Science Olympiad funds STEM competition and education programs for K-12 youth","Science Olympiad Grants","$1,000-$10,000","Annual","https://www.soinc.org","https://www.soinc.org/","STEM competition education; K-12 programs; cross-applicable to robotics team culture and competition mindset","GOOD"),
("VEX Signature Event Sponsors","National","Corporate (VEX Ecosystem)","Companies that sponsor VEX Signature Events often provide team grants and scholarships - research each event sponsor","Signature Event Team Grants","Varies","Annual through RECF","https://www.robotevents.com","https://recf.org/","Research current VEX Signature Event sponsors; each may offer team grants; contact through RECF","GOOD"),
("NASA Armstrong Flight Research Center (Edwards CA)","State","Government/Research","NASA Armstrong in Edwards CA (90 miles from Fullerton); aeronautics research center; STEM education for SoCal youth","NASA Armstrong STEM Education","$5,000-$25,000","Annual","https://www.nasa.gov/armstrong","https://www.nasa.gov/armstrong/education/","Edwards CA near Fullerton; aeronautics STEM education; SoCal youth programs; direct NASA connection","GOOD"),
("Space Launch Delta 30 (Vandenberg AFB) STEM","State","Government/Military","Vandenberg Space Force Base near Santa Barbara CA; STEM education outreach for youth in SoCal and Central Coast","Vandenberg STEM Outreach","$1,000-$10,000","Annual","https://www.vandenberg.spaceforce.mil","https://www.vandenberg.spaceforce.mil/","Space Force installation; STEM outreach; military education; JROTC connection through Space Force branch","GOOD"),
# Additional CA foundations and nonprofits
("California Wellness Foundation","State","Foundation (California)","California Wellness Foundation funds health and STEM wellness programs in CA; youth-focused","Health and STEM Wellness CA","$10,000-$250,000","Annual","https://www.calwellness.org","https://www.calwellness.org/grants/","CA-focused foundation; health and wellness STEM; youth programs in CA directly eligible","MEDIUM"),
("The James Irvine Foundation (Additional Programs)","State","Foundation (California)","James Irvine has additional open programs beyond leadership focus; arts and STEM intersections","STEM and Arts Integration","$25,000-$500,000","Annual RFP","https://www.irvine.org","https://www.irvine.org/our-grants/","Additional Irvine Foundation programs; STEM and arts integration; CA focus","MEDIUM"),
("First 5 California","State","Government (State)","First 5 California funds early childhood STEM learning; tobacco tax funded; K-3 focus primarily","Early STEM Learning Grants","$10,000-$250,000","Annual","https://www.first5california.com","https://www.first5california.com/","Early childhood STEM; K-3 age primarily but middle/high school pipeline connection; CA funded","MEDIUM"),
("California Community Foundation (Additional Programs)","State","Foundation (Community)","CCF has additional programs beyond main education grants; capacity building and collaboration grants","Capacity Building and Collaboration","$10,000-$250,000","Annual","https://www.calfund.org","https://www.calfund.org/grants/","Additional CCF programs; capacity building for nonprofits; STEM nonprofit collaboration grants","MEDIUM"),
("The Ahmanson Foundation (Additional)","Regional","Foundation (Education)","Additional Ahmanson programs beyond main education grants; special project and capacity grants","Special Project Grants","$10,000-$100,000","Annual","https://www.theahmansonfoundation.org","https://www.theahmansonfoundation.org/","Additional Ahmanson Foundation programs; special project grants for education and STEM","GOOD"),
("Discovery Science Center Foundation (Santa Ana CA)","Local","Nonprofit (STEM/Museum)","Discovery Cube in Santa Ana OC; STEM education museum; grant partner for OC schools and STEM programs","OC STEM Museum Partnership","$5,000-$25,000","Annual","https://discoverycube.org","https://discoverycube.org/","OC science museum; STEM partnership with schools; Santa Ana adjacent to Fullerton","GOOD"),
("Aquarium of the Pacific Foundation (Long Beach)","Regional","Nonprofit (Science/Education)","Aquarium in Long Beach CA; funds ocean and STEM education for SoCal youth; science exploration","Ocean STEM Education Grants","$5,000-$25,000","Annual","https://www.aquariumofpacific.org","https://www.aquariumofpacific.org/about/sustainability","Long Beach CA near Fullerton; ocean and STEM education; SoCal youth programs","MEDIUM"),
("California Science Center Foundation (Los Angeles)","Regional","Nonprofit (Science/Education)","CA Science Center in LA; funds STEM education for SoCal youth; Space Shuttle Endeavour exhibit","STEM Education Partnership","$5,000-$25,000","Annual","https://californiasciencecenter.org","https://californiasciencecenter.org/support/","LA science museum; STEM education for SoCal youth; Space Shuttle inspires aerospace-minded cadets","GOOD"),
# Additional individual/family philanthropists active in STEM
("The Broad Foundation","State","Individual Philanthropist (LA)","Eli Broad's foundation (now closed but legacy programs); LA-based major philanthropy; STEM and arts","Education and STEM Legacy Grants","Varies","Contact successor programs","https://www.broadfoundation.org","https://www.broadfoundation.org/","LA-based major foundation; STEM and arts education; legacy programs through successor organizations","MEDIUM"),
("Gordon and Betty Moore Foundation","State","Foundation (California)","Intel co-founder Gordon Moore's foundation; funds STEM education and science; CA-based","Science and STEM Education","$25,000-$1,000,000","Annual","https://www.moore.org","https://www.moore.org/","Intel co-founder; science and STEM education; CA-based; major foundation with rolling LOI","GOOD"),
("Pritzker Foundation","National","Individual Philanthropist","Chicago-based Pritzker family funds education and STEM broadly; Hyatt Hotels connection","Education and STEM Grants","$25,000-$500,000","Invitation","https://www.pritzker.com","https://www.pritzker.com/","Chicago philanthropy; education and STEM; Hyatt Hotels family; invitation-based","MEDIUM"),
# More telecom and media
("iHeartMedia Foundation","National","Corporate (Media)","iHeartMedia funds community and education programs through local radio markets","Community Education Grants","$1,000-$10,000","Annual","https://www.iheartmedia.com","https://www.iheartmedia.com/csr/","Local radio stations; community education; iHeartMedia serves Fullerton/OC market","MEDIUM"),
("Clear Channel Outdoor Foundation","National","Corporate (Media)","Clear Channel Outdoor funds community programs through billboard advertising support and grants","Community Education Support","$1,000-$10,000","Annual","https://www.clearchanneloutdoor.com","https://www.clearchanneloutdoor.com/social-responsibility/","Outdoor advertising; community grants; can provide free billboard space for TroyVEX fundraising","MEDIUM"),
# Additional JROTC-specific and military scholarship programs
("ROTC National Scholarship Program","National","Government (Military)","Army Navy Air Force ROTC scholarships for high school seniors pursuing college STEM; JROTC cadets directly eligible","ROTC College Scholarships","Full tuition + stipend","Annual (Oct-Nov deadline)","https://www.goarmy.com/rotc/high-school-students.html","https://www.goarmy.com/rotc/high-school-students.html","ROTC scholarships for JROTC cadets entering college; STEM majors preferred; HIGH VALUE for individual cadets","GOOD"),
("Navy ROTC Scholarship Program","National","Government (Military)","Navy ROTC scholarships specifically relevant to Troy NJROTC cadets pursuing college degrees","Navy ROTC Scholarships","Full tuition + stipend","Annual","https://www.nrotc.navy.mil","https://www.nrotc.navy.mil/scholarship_programs.html","NJROTC direct pipeline; Navy ROTC college scholarships; cadets pursuing STEM at college level","GOOD"),
("Seabee Memorial Scholarship Foundation","National","Military-Affiliated Foundation","Navy Seabees (Construction Battalions) scholarship for Navy-connected youth; construction and engineering focus","Seabee Memorial Scholarships","$2,000-$3,500","Annual","https://www.seabee-memorial-scholarship.org","https://www.seabee-memorial-scholarship.org/","Navy Construction Battalion scholarships; Navy-connected (NJROTC) youth; engineering construction focus","GOOD"),
("Surface Navy Association Scholarship","National","Military-Affiliated Foundation","SNA funds scholarships for Navy-connected youth including NJROTC cadets; surface warfare focus","SNA Scholarships","$1,000-$5,000","Annual","https://www.surfacenavyassociation.org","https://www.surfacenavyassociation.org/","Surface Navy scholarships; NJROTC cadets eligible; sea service career pipeline","GOOD"),
("Naval Helicopter Association Scholarship","National","Military-Affiliated Foundation","NHA funds scholarships for Navy aviation community youth; aviation and aerospace focus","NHA Scholarships","$1,000-$3,500","Annual","https://navalhelicopterassn.org","https://navalhelicopterassn.org/scholarship/","Naval aviation scholarships; JROTC aviation-interested cadets; aerospace career pipeline","MEDIUM"),
("Navy League Cadet Scholarship","National","Military-Affiliated Foundation","Navy League specifically funds scholarships for NJROTC cadets and Sea Cadet members","NJROTC Cadet Scholarships","$2,500-$5,000","Annual","https://www.navyleague.org","https://www.navyleague.org/scholarship/","NJROTC DIRECTLY eligible; sea service scholarship for cadets; HIGH PRIORITY for Troy NJROTC seniors","GOOD"),
("Tailhook Educational Foundation","National","Military-Affiliated Foundation","Carrier aviation community scholarship foundation; naval aviation and carrier ops focus","Naval Aviation Scholarships","$2,000-$15,000","Annual","https://www.tailhook.net","https://www.tailhook.net/Education%20Foundation.htm","Naval carrier aviation; scholarships for Navy-connected youth; NJROTC cadets interested in aviation eligible","GOOD"),
# Additional SoCal companies
("Ingram Micro Foundation (Irvine) 2","Local","Corporate (Technology)","Ingram Micro additional OC community programs; tech distribution giant with OC campus","OC Technology Community Grants","$5,000-$25,000","Annual","https://www.ingrammicro.com","https://www.ingrammicro.com/en-us/about-ingram/corporate-responsibility","Irvine OC HQ; OC technology community programs; large local employer with STEM alignment","MEDIUM"),
("Broadcom Employee Giving (OC)","Local","Corporate (Technology/Semiconductor)","Broadcom employee giving programs in OC; engineers in Irvine can volunteer and donate","Employee Volunteer and Matching Grants","$500-$5,000 per employee","Rolling - employee triggered","https://www.broadcom.com","https://www.broadcom.com/company/social-responsibility","Irvine OC major employer; employee volunteer grants; Broadcom engineers as TroyVEX mentors","GOOD"),
("Qualcomm Employee Matching (San Diego/OC)","State","Corporate (Technology/Semiconductor)","Qualcomm employee matching gifts program; engineers in SoCal can match donations to TroyVEX","Employee Gift Matching Program","Dollar-for-dollar match up to $5,000/employee","Rolling - employee triggered","https://www.qualcomm.com","https://www.qualcomm.com/company/responsibility/","San Diego HQ with OC operations; employee matching; Qualcomm engineers as TroyVEX STEM mentors","GOOD"),
("Edwards Lifesciences Employee Giving (OC)","Local","Corporate (Healthcare)","Edwards Lifesciences employees in Irvine can volunteer and donate with company matching","Employee Volunteer and Match Grants","$500-$5,000 per employee","Rolling - employee triggered","https://www.edwards.com","https://www.edwards.com/gb/about-us/sustainability","Irvine OC headquarters; employee volunteer grants; Edwards engineers as STEM mentors for TroyVEX","GOOD"),
# More national tech
("Workiva Foundation","National","Corporate (Technology/Reporting)","Workiva funds education and community programs; financial reporting software company; Ames IA HQ","Education and Community Grants","$5,000-$25,000","Annual","https://www.workiva.com","https://www.workiva.com/about/social-responsibility","Financial reporting software; education funding; Ames IA HQ with national programs","MEDIUM"),
("Verint Systems Foundation","National","Corporate (Technology/Analytics)","Verint funds community and education programs; customer engagement analytics","Community Education Grants","$1,000-$10,000","Annual","https://www.verint.com","https://www.verint.com/company/corporate-responsibility/","Analytics technology; education and community; Melville NY HQ","MEDIUM"),
("SS&C Technologies Foundation","National","Corporate (Technology/Financial)","SS&C funds financial technology education and community programs","Fintech Education Grants","$1,000-$10,000","Annual","https://www.ssctech.com","https://www.ssctech.com/company/social-responsibility","Financial technology; education programs; Windsor CT HQ with national programs","MEDIUM"),
("Tyler Technologies Foundation","National","Corporate (Technology/Government)","Tyler Technologies funds education and STEM for youth; government software company","STEM Education Grants","$1,000-$25,000","Annual","https://www.tylertech.com","https://www.tylertech.com/social-responsibility","Government technology; STEM education; Plano TX HQ with national programs","MEDIUM"),
# Additional foundations/grants not yet captured
("Lemelson Center (Smithsonian)","National","Foundation (Invention/STEM)","Smithsonian Lemelson Center funds invention and STEM education exhibits and programs","Invention and STEM Education","$5,000-$50,000","Annual","https://invention.si.edu","https://invention.si.edu/","Smithsonian invention center; STEM education; invention and innovation for youth programs","GOOD"),
("National Inventors Hall of Fame Foundation","National","Foundation (STEM/Invention)","NIHF funds STEM education through Camp Invention and educational outreach programs","Camp Invention / STEM Education","$1,000-$10,000","Annual","https://www.invent.org","https://www.invent.org/foundation","Camp Invention for K-8; STEM education; engineering pipeline; Akron OH HQ","GOOD"),
("Society of Automotive Engineers - SoCal Chapter","Regional","Professional Society (Engineering)","SAE SoCal chapter hosts STEM events and connects with local automotive/aerospace engineers","Local STEM Engineering Events","$500-$5,000","Annual","https://www.saelosmangeles.org","https://www.saelosmangeles.org/","SAE SoCal chapter; local STEM engineering events; networking with automotive and aerospace engineers near Fullerton","GOOD"),
("IEEE Orange County Section","Local","Professional Society (Engineering)","IEEE OC Section funds local STEM events and student programs; electrical engineering focus","Local STEM Student Programs","$500-$5,000","Annual","https://ieeela.org","https://ieeela.org/","IEEE OC section; local STEM student programs; electrical engineering in OC; TroyVEX connection to local engineers","GOOD"),
("AIAA SoCal Section","Regional","Professional Society (Engineering)","AIAA SoCal section funds aerospace STEM events and student programs; Caltech and JPL connections","Aerospace STEM Events","$500-$5,000","Annual","https://www.aiaasocalernational.org","https://www.aiaasocalernational.org/","AIAA SoCal; aerospace STEM events; Caltech and JPL connections near Fullerton; aerospace career pipeline","GOOD"),
("ASME SoCal Section","Regional","Professional Society (Engineering)","ASME SoCal section funds mechanical engineering STEM events and student programs","Mechanical STEM Events","$500-$5,000","Annual","https://event.asme.org/SoCal","https://event.asme.org/SoCal","ASME SoCal; mechanical engineering STEM events; student programs; robotics builds on mechanical engineering","GOOD"),
("SME Greater LA Chapter","Regional","Professional Society (Engineering)","Society of Manufacturing Engineers LA chapter funds manufacturing STEM and student programs","Manufacturing STEM Events","$500-$5,000","Annual","https://www.sme.org","https://www.sme.org/communities/chapters/","SME LA chapter; manufacturing STEM events; fabrication and CNC education; robotics manufacturing overlap","GOOD"),
# Final gap fillers
("Western Growers Foundation (Irvine CA)","State","Foundation (Agriculture)","Western Growers Foundation in Irvine OC; funds agricultural tech and STEM education for CA","AgTech and STEM Education CA","$5,000-$50,000","Annual","https://www.wga.com/western-growers-foundation/","https://www.wga.com/western-growers-foundation/","Irvine OC HQ; agricultural technology STEM; precision agriculture and robotics overlap","MEDIUM"),
("California Science Project","State","Government (State)","CDE-funded network supporting K-12 science education in CA; professional development grants","Science Education Professional Development","$5,000-$25,000","Annual","https://www.cascience.org","https://www.cascience.org/","CA-funded science education network; professional development for TroyVEX coaches; statewide grants","GOOD"),
("OC Department of Education STEM Initiative","Local","Government (Local)","OCDE supports STEM education initiatives for Orange County schools; professional development","OC STEM Teacher Development","$1,000-$10,000","Annual","https://www.ocde.us/stem","https://www.ocde.us/","OC government education; STEM teacher development; Troy High School directly eligible as OC school","GOOD"),
("Fullerton Police Department Community Foundation","Local","Civic/Government","FPD community foundation funds local youth programs; law enforcement STEM adjacent through technology","Youth Programs and Safety","$500-$5,000","Annual","https://www.cityoffullerton.com","https://www.cityoffullerton.com/gov/departments/police/","Local Fullerton government; youth programs; community partnership opportunity for TroyVEX","MEDIUM"),
("City of Fullerton Arts and Recreation Grants","Local","Government (Local)","City of Fullerton funds arts and recreation programs; STEM presentations and demonstrations could qualify","Arts and Recreation Grants","$500-$5,000","Annual","https://www.cityoffullerton.com","https://www.cityoffullerton.com/","Local Fullerton government grants; arts and recreation programs; TroyVEX STEM demonstrations could qualify","MEDIUM"),
("Fullerton Public Library Foundation","Local","Foundation (Education)","Fullerton Public Library Foundation funds literacy and education programs for Fullerton youth","Literacy and Education Grants","$500-$5,000","Annual","https://fullertonlibraryfoundation.org","https://fullertonlibraryfoundation.org/","Local Fullerton library foundation; literacy and education; STEM programming partnership opportunity","MEDIUM"),
("EDF (Environmental Defense Fund) SoCal","Regional","Nonprofit (Environment/STEM)","EDF funds environmental STEM and clean technology; climate action and youth engagement","Environmental STEM Grants","$5,000-$50,000","Annual","https://www.edf.org","https://www.edf.org/","Environmental STEM; clean technology; SoCal office; robotics in sustainability context","MEDIUM"),
("Sierra Club Foundation","National","Foundation (Environment/STEM)","Sierra Club Foundation funds environmental education and STEM; youth outdoors and science","Environmental STEM Education","$5,000-$50,000","Annual","https://www.sierraclubfoundation.org","https://www.sierraclubfoundation.org/","Environmental STEM education; youth outdoors; Oakland CA HQ; clean energy and robotics context","MEDIUM"),
("National Wildlife Federation Foundation","National","Foundation (Environment/STEM)","NWF funds environmental STEM and wildlife education for youth; Eco-Schools USA program","Eco-Schools / Environmental STEM","$5,000-$25,000","Annual","https://www.nwf.org","https://www.nwf.org/","Environmental STEM; youth wildlife education; Eco-Schools USA program for K-12","MEDIUM"),
("Robert Wood Johnson Foundation","National","Foundation (Health/STEM)","RWJF funds health STEM and community wellbeing; health workforce and health sciences education","Health STEM Education","$25,000-$1,000,000","Annual","https://www.rwjf.org","https://www.rwjf.org/en/grants.html","Health STEM; health sciences education pipeline; Princeton NJ HQ with national programs","MEDIUM"),
("W.K. Kellogg Foundation STEM","National","Foundation (Education)","Kellogg Foundation funds STEM and educational equity for vulnerable youth and underserved communities","STEM Education Equity","$50,000-$1,000,000","Rolling","https://www.wkkf.org","https://www.wkkf.org/grants","Education equity and STEM; underserved youth; Battle Creek MI HQ with national programs","MEDIUM"),
("Joyce Foundation STEM","National","Foundation (Education)","Joyce Foundation funds STEM and education policy in Great Lakes states; quarterly deadlines","STEM Education Policy Grants","$50,000-$500,000","Quarterly deadlines Apr/Aug/Dec","https://www.joycefdn.org","https://www.joycefdn.org/apply","STEM education policy; Great Lakes states; quarterly deadlines; Midwest geographic limitation","MEDIUM"),
("Luminos Fund","National","Foundation (Education)","Luminos Fund works in education for marginalized youth globally; STEM acceleration programs","STEM Acceleration Programs","$10,000-$100,000","Annual","https://luminosfund.org","https://luminosfund.org/get-involved/","Education for marginalized youth; STEM acceleration; global but US programs","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 9 complete: {len(ENTRIES)} new entries appended")
