#!/usr/bin/env python3
# Batch 5: Healthcare/Pharma additional, Financial additional, Retail/Consumer, Food/Bev, Media/Airlines

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Healthcare / Pharma additional
("Stryker Foundation","National","Corporate (Healthcare)","Stryker funds STEM education and orthopedic health access; medical devices and robotics surgical systems","STEM Medical Robotics Education","$10,000-$100,000","Annual","https://www.stryker.com","https://www.stryker.com/us/en/about/social-responsibility.html","Surgical robotics company - directly in robotics industry; STEM education; Kalamazoo MI HQ","GOOD"),
("Boston Scientific Foundation","National","Corporate (Healthcare)","Boston Scientific funds STEM education and healthcare career pipeline; medical devices company","STEM Healthcare Education","$5,000-$100,000","Annual","https://www.bostonscientific.com","https://www.bostonscientific.com/en-US/corporate-responsibility.html","Medical devices; STEM education; Marlborough MA HQ with CA manufacturing","GOOD"),
("Edwards Lifesciences Foundation (Irvine CA)","State","Corporate (Healthcare)","Edwards Lifesciences HQ in Irvine CA (OC); funds STEM and healthcare education in OC; heart valves and hemodynamic monitoring","STEM Health and OC Education","$10,000-$250,000","Annual","https://www.edwards.com","https://www.edwards.com/gb/about-us/sustainability","Irvine OC headquarters; STEM and healthcare education; OC community investment","GOOD"),
("Baxter International Foundation","National","Corporate (Healthcare)","Baxter funds STEM education and healthcare access; medical products and renal therapies","STEM Healthcare Grants","$5,000-$100,000","Annual","https://www.baxter.com","https://www.baxter.com/healthcare-sustainability","Medical products; STEM education; Deerfield IL HQ with national programs","MEDIUM"),
("Becton Dickinson Foundation","National","Corporate (Healthcare)","BD funds STEM education and healthcare access for underserved communities; medical devices","STEM Healthcare Access","$10,000-$100,000","Annual","https://www.bd.com","https://www.bd.com/en-us/company/sustainability","Medical devices; STEM education; Franklin Lakes NJ HQ with CA operations","MEDIUM"),
("ResMed Foundation (San Diego CA)","State","Corporate (Healthcare)","ResMed HQ in San Diego CA; sleep technology and digital health company; funds STEM education in SoCal","STEM Digital Health Education","$5,000-$50,000","Annual","https://www.resmed.com","https://www.resmed.com/en-us/company/corporate-social-responsibility/","San Diego CA HQ near Fullerton; STEM digital health education; SoCal community investment","GOOD"),
("Illumina Foundation","National","Corporate (Healthcare/Biotech)","Illumina funds STEM education and genomics literacy; DNA sequencing technology; science pipeline","STEM Genomics Education","$10,000-$250,000","Annual","https://www.illumina.com","https://www.illumina.com/company/social-responsibility.html","Genomics and biotech STEM; science education pipeline; San Diego CA HQ","GOOD"),
("Agilent Technologies Foundation","National","Corporate (Healthcare/Technology)","Agilent funds STEM education and measurement science; life science and chemical analysis instruments","STEM Measurement Science","$10,000-$250,000","Annual","https://www.agilent.com","https://www.agilent.com/en/company-information/corporate-social-responsibility","Scientific instruments and STEM education; Santa Clara CA HQ; measurement science relevant to robotics","GOOD"),
("Waters Corporation Foundation","National","Corporate (Healthcare/Technology)","Waters funds STEM education and analytical science; liquid chromatography and mass spectrometry","STEM Analytical Science","$5,000-$50,000","Annual","https://www.waters.com","https://www.waters.com/waters/en_US/Sustainability/nav.htm","Analytical science instruments; STEM education; Milford MA HQ","MEDIUM"),
("Masimo Foundation (Irvine CA)","State","Corporate (Healthcare)","Masimo medical monitoring technology HQ in Irvine CA (OC); funds STEM and healthcare education in OC","OC STEM Healthcare","$5,000-$50,000","Annual","https://www.masimo.com","https://www.masimo.com/company/about/","Irvine OC HQ; medical monitoring technology; OC STEM education funding","GOOD"),
("Hologic Foundation","National","Corporate (Healthcare)","Hologic funds women's health STEM education and science career pipeline; medical technology","STEM Women's Health Science","$5,000-$100,000","Annual","https://www.hologic.com","https://www.hologic.com/company/corporate-social-responsibility","Women's health technology; STEM education; Marlborough MA HQ with national programs","MEDIUM"),
("UnitedHealth Group Foundation","National","Corporate (Healthcare)","UnitedHealth funds health sciences education and community wellness programs; workforce pipeline","Health Sciences STEM","$25,000-$500,000","Annual","https://www.unitedhealthgroup.com","https://www.unitedhealthgroup.com/giving-back.html","Health sciences pipeline; K-12 access programs funded; Minnetonka MN HQ with national programs","MEDIUM"),
("CVS Health Foundation","National","Corporate (Healthcare/Retail)","CVS Health funds health education and youth workforce programs broadly; health and wellness career pipeline","Health Education Grants","$25,000-$200,000","Annual","https://www.cvshealth.com","https://www.cvshealth.com/impact/cvs-health-foundation.html","Youth health workforce; STEM adjacent through health sciences; Woonsocket RI HQ with CA stores","MEDIUM"),
("Zimmer Biomet Foundation","National","Corporate (Healthcare)","Zimmer Biomet funds STEM education and orthopedic health access for underserved youth; Warsaw IN HQ","STEM and Health Education","$5,000-$50,000","Annual","https://www.zimmerbiomet.com","https://www.zimmerbiomet.com/en/about-zimmer-biomet/corporate-responsibility.html","Medical devices STEM education; engineering career pipelines; orthopedic technology","MEDIUM"),
# Financial / Banking additional
("Raymond James Foundation","National","Corporate (Financial)","Raymond James funds STEM education and community programs; St. Petersburg FL HQ","STEM and Community Grants","$5,000-$100,000","Annual","https://www.raymondjames.com","https://www.raymondjames.com/raymond-james-foundation","Financial services; STEM education; St. Petersburg FL HQ with CA offices","MEDIUM"),
("Edward Jones Foundation","National","Corporate (Financial)","Edward Jones funds education and community programs; St. Louis MO HQ; nationwide branch network","Education and Community Grants","$1,000-$50,000","Annual","https://www.edwardjones.com","https://www.edwardjones.com/us-en/about-edward-jones/responsible-business/community-involvement","Financial services; education funding; nationwide branch network including Fullerton CA","MEDIUM"),
("Vanguard Charitable","National","Corporate (Financial)","Vanguard funds charitable giving through donor-advised fund; investment management company","Donor-Advised Fund Grants","Varies by donor","Rolling","https://www.vanguardcharitable.org","https://www.vanguardcharitable.org/","Donor-advised fund; connect with Vanguard investors for grants to TroyVEX; Malvern PA HQ","MEDIUM"),
("Ameriprise Financial Foundation","National","Corporate (Financial)","Ameriprise funds education and community programs; employee matching program","Education and Community Grants","$5,000-$50,000","Annual","https://www.ameriprise.com","https://www.ameriprise.com/financial-goals-priorities/giving-back/","Financial services; education funding; Minneapolis MN HQ with CA offices","MEDIUM"),
("Principal Financial Foundation","National","Corporate (Financial)","Principal funds education and workforce development; insurance and investment company","Education and Workforce Grants","$5,000-$100,000","Annual","https://www.principal.com","https://www.principal.com/about-us/our-company/corporate-social-responsibility","Insurance and investment; education funding; Des Moines IA HQ with national programs","MEDIUM"),
("Unum Foundation","National","Corporate (Financial/Insurance)","Unum funds education and disability inclusion; employee benefits and disability insurance","Education and Inclusion Grants","$5,000-$50,000","Annual","https://www.unum.com","https://www.unum.com/about/corporate-social-responsibility","Disability insurance; education inclusion funding; Chattanooga TN HQ","MEDIUM"),
("Aflac Foundation","National","Corporate (Financial/Insurance)","Aflac funds childhood cancer research and education; duck logo company; supplemental insurance","Childhood Cancer / Education Grants","$10,000-$100,000","Annual","https://www.aflac.com","https://www.aflac.com/about-aflac/corporate-social-responsibility/","Supplemental insurance; childhood cancer and education focus; Columbus GA HQ; not STEM specific","BAD"),
("Protective Life Foundation","National","Corporate (Financial/Insurance)","Protective Life funds education and community programs; Birmingham AL HQ life insurance","Education and Community Grants","$5,000-$50,000","Annual","https://www.protective.com","https://www.protective.com/about-protective/community-involvement/","Life insurance; education and community; Birmingham AL HQ with national programs","MEDIUM"),
("Nationwide Foundation","National","Corporate (Financial/Insurance)","Nationwide funds education and community programs; Columbus OH HQ; farm bureau history","Education and Ag STEM Grants","$5,000-$100,000","Annual","https://www.nationwide.com","https://www.nationwide.com/about/social-responsibility.jsp","Insurance; education and agriculture STEM; Columbus OH HQ with national programs","MEDIUM"),
("Travelers Foundation","National","Corporate (Financial/Insurance)","Travelers funds STEM education and disaster preparedness; property casualty insurance","STEM and Safety Education","$5,000-$100,000","Annual","https://www.travelers.com","https://www.travelers.com/about-travelers/corporate-citizenship","Property insurance; STEM and safety education; Hartford CT HQ with national programs","MEDIUM"),
("Morgan Stanley Foundation","National","Corporate (Financial)","Morgan Stanley funds youth health and STEM innovation; Children's Innovation Awards program","Innovation Awards / Education","$10,000-$100,000","Annual","https://www.morganstanley.com","https://www.morganstanley.com/about-us/giving-back","Children's Innovation Awards; youth STEM innovation; New York HQ with CA wealth management offices","MEDIUM"),
("PNC Foundation","National","Corporate (Financial)","PNC funds early childhood and K-12 education broadly; Grow Up Great flagship; math and science mentioned","Grow Up Great / K-12 Education","$10,000-$250,000","Rolling regional","https://www.pnc.com","https://www.pnc.com/en/about-pnc/corporate-responsibility/philanthropy/pnc-foundation.html","Math and science mentioned; contact regional PNC officer; Pittsburgh PA HQ with CA branches","MEDIUM"),
# Retail / Consumer
("Nike Foundation","National","Corporate (Retail/Sports)","Nike funds youth empowerment and education; active youth community programs; Beaverton OR HQ","Youth Empowerment and Education","$10,000-$250,000","Annual","https://www.nikeinc.com","https://www.nikeinc.com/pages/social-responsibility","Youth empowerment and education; Nike has major CA presence; active youth programs","MEDIUM"),
("Starbucks Foundation","National","Corporate (Retail/Food)","Starbucks funds youth opportunity and education; Opportunity for All program; Seattle WA HQ","Opportunity for All / Youth Education","$10,000-$250,000","Annual","https://www.starbucks.com","https://www.starbucks.com/responsibility/community/","Youth opportunity and education; Starbucks has stores throughout Fullerton CA area","MEDIUM"),
("McDonald's Foundation / RMHC","National","Corporate (Retail/Food)","McDonald's Ronald McDonald House Charities funds youth health and education; RMHC scholarships","RMHC Scholarships / Youth Health","$1,000-$5,000 scholarships","Annual","https://www.rmhc.org","https://www.rmhc.org/scholarships","RMHC scholarships for youth; McDonald's has Fullerton area locations; youth programs","MEDIUM"),
("Gap Foundation","National","Corporate (Retail)","Gap Inc funds career opportunities and STEM education for youth; This Way Ahead internship program","This Way Ahead / Youth Career Grants","$5,000-$100,000","Annual","https://www.gapinc.com","https://www.gapinc.com/en-us/articles/2023/03/gap-inc-social-responsibility","Youth career development and education; San Francisco CA HQ; This Way Ahead program","MEDIUM"),
("Nordstrom Foundation","National","Corporate (Retail)","Nordstrom funds youth programs and education; Building Stronger Communities initiative","Youth Programs and Education","$10,000-$250,000","Annual","https://www.nordstrom.com","https://www.nordstrom.com/browse/nordstrom-gives","Youth education and community; Seattle WA HQ; Nordstrom stores in OC malls","MEDIUM"),
("REI Co-op Foundation","National","Corporate (Retail/Outdoor)","REI funds outdoor education and environmental STEM; youth outdoors and conservation","Outdoor and Environmental STEM","$5,000-$100,000","Annual","https://www.rei.com","https://www.rei.com/stewardship/grants.html","Outdoor and environmental STEM; youth outdoors programs; Kent WA HQ with CA stores","MEDIUM"),
("Patagonia Environmental Grant","National","Corporate (Retail/Outdoor)","Patagonia funds environmental activism and STEM; 1% for the Planet member; Ventura CA HQ","Environmental STEM Grants","$5,000-$50,000","Annual","https://www.patagonia.com","https://www.patagonia.com/our-footprint/environmental-grants.html","Environmental STEM; 1% for the Planet; Ventura CA HQ near Fullerton; grant program open","GOOD"),
("Under Armour Foundation","National","Corporate (Retail/Sports)","Under Armour funds youth athletic and education programs; Power in Pink and community grants","Youth Athletic and Education Grants","$5,000-$100,000","Annual","https://www.underarmour.com","https://www.underarmour.com/en-us/t/about-ua/","Youth athletic programs and education; Baltimore MD HQ with national programs","MEDIUM"),
("Kroger Foundation","National","Corporate (Retail/Grocery)","Kroger funds hunger relief and education for youth; Zero Hunger Zero Waste foundation","Zero Hunger Zero Waste / Education","$5,000-$100,000","Annual","https://www.kroger.com","https://www.kroger.com/i/community/hunger-relief","Grocery company; hunger relief and education; Cincinnati OH HQ with CA Ralphs stores","MEDIUM"),
("Albertsons Companies Foundation","National","Corporate (Retail/Grocery)","Albertsons funds hunger relief and education; Albertsons Safeway Vons Jewel Osco all included","Education and Hunger Relief","$5,000-$100,000","Annual","https://www.albertsonscompanies.com","https://www.albertsonscompanies.com/about-us/our-impact.html","Albertsons and Vons stores in Fullerton; education and community programs; Boise ID HQ","MEDIUM"),
("Costco Wholesale Foundation","National","Corporate (Retail)","Costco funds education and community programs; employee-directed local giving","Education and Community Grants","$5,000-$100,000","Annual regional","https://www.costco.com","https://www.costco.com/charitable-giving.html","Costco warehouse in Fullerton area; education and community giving; Issaquah WA HQ","MEDIUM"),
("Dollar General Literacy Foundation","National","Corporate (Retail)","Dollar General funds literacy and education for K-12 and adults; STEM tangential","Literacy Grants","$500-$5,000","Annual spring cycle","https://www.dgliteracy.org","https://www.dgliteracy.org/grants","Literacy and basic education; STEM tangential; low barrier to entry; small but accessible","MEDIUM"),
("Best Buy Teen Tech Centers","National","Corporate (Retail)","Best Buy Foundation Teen Tech Centers provide technology education spaces for teens 13-18","Teen Tech Centers","$10,000-$500,000","Annual RFP","https://corporate.bestbuy.com","https://corporate.bestbuy.com/best-buy-foundation/","Already included in Batch 1 - additional program: Best Buy provides free devices for qualifying centers","GOOD"),
# Food / Beverage additional
("Hershey Company Foundation","National","Corporate (Food)","Hershey funds education and community programs; Milton Hershey School model; employee community focus","Education and Community Grants","$5,000-$50,000","Annual","https://www.thehersheycompany.com","https://www.thehersheycompany.com/en_us/home/social-responsibility.html","Chocolate company; education and community; Hershey PA HQ with national programs","MEDIUM"),
("Colgate-Palmolive Foundation","National","Corporate (Consumer Goods)","Colgate funds STEM education and oral health; Bright Smiles Bright Futures program","STEM and Health Education","$5,000-$50,000","Annual","https://www.colgate.com","https://www.colgatepalmolive.com/en-us/core-values/social-responsibility","Consumer goods; education and health programs; New York HQ with national programs","MEDIUM"),
("Procter and Gamble Foundation","National","Corporate (Consumer Goods)","P&G funds education and community programs; supplier diversity and education investment","Education and Community Grants","$10,000-$100,000","Annual","https://www.pg.com","https://www.pg.com/en_US/sustainability/community-impact.shtml","Consumer goods giant; education and community; Cincinnati OH HQ with CA operations","MEDIUM"),
("Unilever Foundation","National","Corporate (Consumer Goods)","Unilever funds STEM education and sustainable living programs; global consumer goods company","STEM and Sustainable Living","$10,000-$100,000","Annual","https://www.unilever.com","https://www.unilever.com/planet-and-society/","Consumer goods; STEM and sustainability education; Englewood Cliffs NJ HQ","MEDIUM"),
# Media / Entertainment
("Walt Disney Company Foundation","National","Corporate (Media/Entertainment)","Disney funds education and youth programs; Disney Dreamer Academy; STEM and creativity grants","Disney Dreamer Academy / Education","$10,000-$500,000","Annual","https://www.thewaltdisneycompany.com","https://www.thewaltdisneycompany.com/responsibility/social-impact/","Youth education and dreams programs; Burbank CA HQ near Fullerton; STEM and creativity focus","GOOD"),
("NBCUniversal Foundation","National","Corporate (Media)","NBCUniversal funds education and diversity programs; 21st Century Solutions; mentorship programs","21st Century Solutions / Education","$25,000-$500,000","Annual","https://www.nbcuniversal.com","https://www.nbcuniversal.com/corporate-social-responsibility","Universal City CA (near Fullerton); education and diversity programs; media and technology pipeline","GOOD"),
("Warner Bros. Discovery Foundation","National","Corporate (Media)","WarnerMedia funds education and storytelling programs; Burbank CA HQ near Fullerton","Education and Storytelling Grants","$10,000-$250,000","Annual","https://www.wbd.com","https://www.wbd.com/corporate-responsibility","Burbank CA HQ near Fullerton; education programs; media and technology career pipeline","GOOD"),
("Sony Pictures Entertainment Foundation","State","Corporate (Media)","Sony Pictures HQ in Culver City CA; funds education and community programs in SoCal","SoCal Education and Community","$10,000-$250,000","Annual","https://www.sonypictures.com","https://www.sonypictures.com/corp/social_responsibility.html","Culver City CA HQ (near Fullerton); education and community programs in SoCal","GOOD"),
("Paramount Pictures Foundation","State","Corporate (Media)","Paramount HQ in Hollywood CA; funds education and community programs in SoCal; entertainment industry","SoCal Education Grants","$5,000-$100,000","Annual","https://www.paramount.com","https://www.paramount.com/corporate-responsibility","Hollywood CA HQ (near Fullerton); education and community programs; entertainment industry","MEDIUM"),
("Discovery Education Foundation","National","Corporate (Media/Education)","Discovery Education funds STEM curriculum and learning resources for K-12; directly relevant to robotics","STEM Curriculum and Resources","$10,000-$250,000","Annual","https://www.discoveryeducation.com","https://www.discoveryeducation.com/solutions/professional-learning/grants/","K-12 STEM curriculum and learning resources directly applicable to TroyVEX program","GOOD"),
("National Geographic Society Education","National","Nonprofit (Media/Science)","National Geographic funds STEM and geography education; exploration and science grants for youth","Exploration and STEM Education","$5,000-$50,000","Annual","https://www.nationalgeographic.org","https://www.nationalgeographic.org/funding-opportunities/grants/","Science and geography STEM education; exploration grants for youth; Washington DC HQ","GOOD"),
("PBS Foundation","National","Nonprofit (Media/Education)","PBS funds education and STEM media programming for K-12 youth; LearningMedia platform","PBS LearningMedia / STEM Education","$10,000-$100,000","Annual","https://www.pbs.org","https://www.pbs.org/about/corporate-responsibility/","Education media and STEM programming; PBS serves Fullerton via SoCal station KCET/PBS SoCal","GOOD"),
("Entertainment Industry Foundation","National","Nonprofit (Media)","Entertainment Industry Foundation funds health and education; Hollywood Walk of Fame campaigns","Health and Education Grants","$10,000-$250,000","Annual","https://eifoundation.org","https://eifoundation.org/programs/","Hollywood-based nonprofit; health and education grants; connects with entertainment industry donors","MEDIUM"),
("DreamWorks Animation Foundation","State","Corporate (Media)","DreamWorks Animation studio in Glendale CA; funds education and creativity programs in SoCal","SoCal Education and Creativity","$5,000-$50,000","Annual","https://www.dreamworks.com","https://www.dreamworks.com/","Glendale CA (near Fullerton); animation STEM; creativity and technology education pipeline","GOOD"),
# Airlines / Travel
("Southwest Airlines Foundation","National","Corporate (Airlines)","Southwest Airlines funds education and community programs; Heart of the Community initiative","Heart of the Community / Education","$5,000-$100,000","Annual","https://www.southwest.com","https://www.southwest.com/about-southwest/charitable-giving/","Aviation airline; education and community; Dallas TX HQ; flies from SNA (Orange County) airport","MEDIUM"),
("American Airlines Foundation","National","Corporate (Airlines)","American Airlines funds education and community programs; AA flies from LAX near Fullerton","Community and Education Grants","$5,000-$100,000","Annual","https://www.aa.com","https://www.aa.com/i18n/customer-service/about-us/social-responsibility.jsp","Aviation airline; education; Fort Worth TX HQ; LAX is 30 miles from Fullerton","MEDIUM"),
("Delta Air Lines Foundation","National","Corporate (Airlines)","Delta funds education and community programs; Force for Global Good; science and math focus","Force for Global Good / Education","$10,000-$250,000","Annual","https://www.delta.com","https://www.delta.com/us/en/about-delta/citizenship","Aviation airline; STEM and education; Atlanta GA HQ; flies from LAX near Fullerton","MEDIUM"),
("United Airlines Foundation","National","Corporate (Airlines)","United Airlines funds community and education programs; United We Rise initiative","United We Rise / Education","$5,000-$100,000","Annual","https://www.united.com","https://www.united.com/en/us/fly/about/responsibility.html","Aviation airline; community and education; Chicago IL HQ; major SoCal hub operations","MEDIUM"),
("Alaska Airlines Foundation","National","Corporate (Airlines)","Alaska Airlines funds community and education programs primarily in West Coast states","West Coast Community and Education","$5,000-$100,000","Annual","https://www.alaskaair.com","https://www.alaskaair.com/content/about-us/social-responsibility","West Coast airline; community and education; Seattle WA HQ; SoCal is major market","MEDIUM"),
("JetBlue Foundation","National","Corporate (Airlines)","JetBlue funds STEM and aviation education; Blue Horizons for a Better Tomorrow; youth aviation","STEM Aviation Education","$5,000-$100,000","Annual","https://www.jetblue.com","https://www.jetblue.com/jets-and-crewmembers/community","Aviation STEM education; youth aviation pipeline; Long Beach CA is a JetBlue hub near Fullerton","GOOD"),
("Marriott Foundation","National","Corporate (Hospitality)","Marriott funds community and education programs; Bridges to Employment for youth","Bridges to Employment / Education","$10,000-$100,000","Annual","https://www.marriott.com","https://serve360.marriott.com/","Youth employment and education; Bethesda MD HQ with CA hotel properties","MEDIUM"),
("Hilton Foundation (general programs)","National","Corporate (Hospitality)","Hilton funds community and education programs; Travel with Purpose; youth workforce development","Travel with Purpose / Youth Workforce","$5,000-$100,000","Annual","https://www.hilton.com","https://cr.hilton.com/","Youth workforce development; Mclean VA HQ with major Fullerton area hotels","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 5 complete: {len(ENTRIES)} new entries appended")
