#!/usr/bin/env python3
# Batch 7: National/state foundations, civic orgs, community foundations (all states), education orgs

import csv
OUT = r"C:\Users\ryanz\Downloads\ClaudeCode Contacts\troyvex_donor_list.csv"

ENTRIES = [
# Civic / Fraternal organizations
("Rotary International Foundation","National","Civic/Club","Rotary Foundation funds STEM education and youth vocational programs worldwide; Paul Harris Fellows and club grants","Rotary Foundation Grants / Youth Programs","$500-$50,000","Annual","https://www.rotary.org/en/our-programs/grants","https://www.rotary.org/en/about-rotary/rotary-foundation","Rotary clubs in Fullerton can apply; STEM and youth vocational programs; Rotary Vocational Service aligns well","GOOD"),
("Lions International Foundation","National","Civic/Club","Lions Club International funds vision health and youth STEM programs; Lions Quest program for youth","Lions Foundation Youth Grants","$500-$10,000","Annual","https://www.lionsclubs.org","https://www.lionsclubs.org/en/lions-global-community/our-impact","Youth programs and STEM; Lions clubs in Fullerton CA; Lions Quest leadership program for youth","GOOD"),
("Kiwanis International Foundation","National","Civic/Club","Kiwanis funds youth programs and education globally; Circle K International; youth leadership","Youth Programs / Education Grants","$500-$10,000","Annual","https://www.kiwanis.org","https://www.kiwanis.org/community/kiwanis-foundation","Fullerton Kiwanis club can access national funding; youth leadership and education programs","GOOD"),
("Elks National Foundation","National","Civic/Club","Elks funds STEM education scholarships and youth programs; Most Valuable Student award; community grants","Most Valuable Student / Community Grants","$1,000-$15,000","Annual","https://www.elks.org","https://www.elks.org/enf/scholars/scholarship.cfm","MVS scholarships for high school seniors; community grants through local Fullerton Elks lodge","GOOD"),
("Optimist International Foundation","National","Civic/Club","Optimist funds youth STEM and communication programs; Oratorical Contest; club service grants","Oratorical / Youth Service Grants","$500-$5,000","Annual","https://www.optimist.org","https://www.optimist.org/e/member/scholarships4.cfm","Youth communication and service programs; local Fullerton Optimist club can apply; low barrier grants","MEDIUM"),
("JCI USA (Jaycees) Foundation","National","Civic/Club","Junior Chamber International funds youth leadership and community programs; STEM and civic engagement","Youth Leadership and STEM Grants","$500-$5,000","Annual","https://www.usjaycees.org","https://www.usjaycees.org/","Youth leadership and community programs; civic engagement aligns with JROTC mission","MEDIUM"),
("Knights of Columbus Foundation","National","Civic/Club","K of C funds Catholic education and community programs; STEM scholarships for Catholic youth; McGivney Grants","McGivney Grants / Youth Education","$1,000-$10,000","Annual","https://www.kofc.org","https://www.kofc.org/en/programs/education/scholarships.html","Youth education scholarships; community programs; Catholic focus but open to community grants","MEDIUM"),
("Boy Scouts of America Foundation","National","Civic/Club","BSA funds STEM Scouts programs and merit badges in robotics; STEM Scouts program directly relevant","STEM Scouts Grants / Merit Badge Programs","$1,000-$10,000","Annual","https://www.scouting.org","https://www.scouting.org/programs/scouts-bsa/stem-programs/","STEM Scouts program directly relevant; robotics merit badge pipeline; collaborative opportunity","GOOD"),
("4-H Foundation (National 4-H Council)","National","Civic/Club","4-H funds STEM and agricultural education for youth; National 4-H STEM Challenge; robotics programs","National 4-H STEM Challenge","$1,000-$25,000","Annual","https://www.4-h.org","https://4-h.org/parents/grants-scholarships/","4-H has robotics programs; STEM education for youth; collaborative pipeline opportunity","GOOD"),
("National FFA Foundation","National","Civic/Club","FFA funds agricultural and STEM education; precision agriculture technology; career development","Agricultural STEM / Career Development","$1,000-$25,000","Annual","https://www.ffa.org","https://www.ffa.org/financials/national-ffa-foundation/","Agricultural STEM pipeline; precision agriculture technology; robotics in agriculture relevant","MEDIUM"),
("Fraternal Order of Eagles Foundation","National","Civic/Club","Eagles funds community and youth programs; humanitarian programs education grants","Community and Youth Grants","$500-$5,000","Annual","https://www.foe.com","https://www.foe.com/","Youth community programs; education grants through local aerie chapters; accessible civic organization","MEDIUM"),
("Moose International Foundation","National","Civic/Club","Moose International funds youth programs and education through Mooseheart and Moosehaven","Youth Education Grants","$500-$5,000","Annual","https://www.mooseintl.org","https://www.mooseintl.org/","Youth education programs; community grants; low barrier to entry through local lodges","MEDIUM"),
("Sons of the American Revolution Foundation","National","Civic/Club","SAR funds patriotic education and history scholarships; JROTC award programs specifically","JROTC Awards / Patriotic Education","$500-$5,000","Annual","https://www.sar.org","https://www.sar.org/education/scholarships/","JROTC awards specifically offered by SAR; patriotic education; JROTC direct connection","GOOD"),
("Daughters of the American Revolution Foundation","National","Civic/Club","DAR funds patriotic education and scholarships; JROTC awards program; American history focus","JROTC Awards / Scholarship","$500-$5,000","Annual","https://www.dar.org","https://www.dar.org/national-society/scholarships","JROTC awards specifically; patriotic education scholarships; NJROTC direct alignment","GOOD"),
("American Legion Auxiliary","National","Military-Affiliated Civic","ALA funds education and programs for military families; youth STEM programs through auxiliaries","ALA Education Grants / Youth Programs","$500-$5,000","Annual","https://www.alaforveterans.org","https://www.alaforveterans.org/scholarships/","Military family programs; youth education; Fullerton American Legion Auxiliary chapter exists","GOOD"),
("Veterans of Foreign Wars Auxiliary","National","Military-Affiliated Civic","VFW Auxiliary funds education and youth programs for military families; Voice of Democracy scholarships","Voice of Democracy / Youth Grants","$500-$5,000","Annual","https://www.vfwauxiliary.org","https://www.vfwauxiliary.org/scholarship/","Military family education; Voice of Democracy for youth; JROTC cadets from veteran families eligible","GOOD"),
("Air Force Association Chapbook Education","National","Military-Affiliated Civic","AFA funds STEM scholarships for AFJROTC and related youth; aerospace career pipeline","AFJROTC Scholarships / STEM","$500-$10,000","Annual","https://www.afa.org","https://www.afa.org/afa-foundation/scholarships/","Aerospace STEM scholarships; AFJROTC focused but cross-branch overlap; career pipeline","GOOD"),
("YMCA Foundation","National","Civic/Nonprofit","YMCA funds youth development and education; STEM programs through Y afterschool programs","Youth Development and STEM","$5,000-$50,000","Annual","https://www.ymca.org","https://www.ymca.org/","Youth development programs; STEM afterschool; local Fullerton YMCA can connect to national grants","MEDIUM"),
("Boys and Girls Club of America Foundation","National","Civic/Nonprofit","BGCA funds youth STEM and education programs; Tech Girls and robotics programs at clubs","Youth STEM and Tech Programs","$10,000-$250,000","Annual","https://www.bgca.org","https://www.bgca.org/","Youth STEM and technology programs; robotics at clubs directly relevant; national foundation","GOOD"),
("Big Brothers Big Sisters Foundation","National","Civic/Nonprofit","BBBS funds mentorship programs for youth; STEM mentorship matches with industry professionals","Youth Mentorship / STEM Mentors","$5,000-$100,000","Annual","https://www.bbbs.org","https://www.bbbs.org/","Mentorship programs; connect TroyVEX cadets with STEM mentors; cross-program collaboration","MEDIUM"),
("Junior Achievement USA Foundation","National","Civic/Nonprofit","JA funds entrepreneurship and STEM education for K-12 youth; JA BizTown and finance park","Entrepreneurship / STEM Education","$5,000-$100,000","Annual","https://www.juniorachievement.org","https://www.juniorachievement.org/","Entrepreneurship and STEM education; K-12 focus; Fullerton area JA chapter can connect nationally","GOOD"),
("City Year Foundation","National","Civic/Nonprofit","City Year places corps members in high-need schools; STEM tutoring and mentorship; AmeriCorps affiliated","STEM Tutoring / School Support","$10,000-$100,000","Annual","https://www.cityyear.org","https://www.cityyear.org/partners/","AmeriCorps affiliated; places STEM tutors in high-need schools; collaborative partnership opportunity","MEDIUM"),
# Education organizations / STEM specific
("Khan Academy Foundation","National","Education Nonprofit","Khan Academy funds free STEM education globally; can be platform partner for TroyVEX learning resources","Free STEM Education Platform","In-kind / partnership","Rolling","https://www.khanacademy.org","https://www.khanacademy.org/about","Free STEM education platform; partnership for supplemental learning; Mountain View CA HQ","MEDIUM"),
("Code.org Foundation","National","Education Nonprofit","Code.org funds CS education for K-12 youth; Hour of Code and CS curriculum programs","CS Education Grants","$5,000-$100,000","Annual","https://www.code.org","https://www.code.org/","CS education for K-12; coding directly relevant to robotics programming; Seattle WA HQ","GOOD"),
("National Science Teaching Association Foundation","National","Education Nonprofit","NSTA funds science teacher grants and STEM curriculum; teacher-focused grants","Science Teacher Grants","$500-$10,000","Annual","https://www.nsta.org","https://www.nsta.org/grants","Science teacher grants; TroyVEX coaches can apply directly; no 501c3 needed for teacher grants","GOOD"),
("DonorsChoose.org","National","Education Nonprofit","DonorsChoose funds individual classroom projects; teachers post projects for public funding","Classroom Project Funding","$500-$10,000","Rolling","https://www.donorschoose.org","https://www.donorschoose.org/teachers","Teacher posts robotics project; public donors fund it; APPLY NOW - rolling; easy entry point","GOOD"),
("National Education Association Foundation","National","Education Nonprofit","NEA funds teacher professional development and classroom innovation grants","Learning and Leadership Grants","$2,000-$5,000","Annual","https://www.neafoundation.org","https://www.neafoundation.org/for-educators/student-achievement-grants/","Teacher professional development and innovation grants; TroyVEX coaches can apply","GOOD"),
("Change the Equation","National","Education Nonprofit","Change the Equation funds STEM education equity programs for underserved communities","STEM Equity Grants","$10,000-$100,000","Annual","https://changetheequation.org","https://changetheequation.org/","STEM education equity; underrepresented youth programs; business and education partnership model","GOOD"),
("BootUp Foundation","National","Education Nonprofit","BootUp funds CS and coding education in underprivileged schools; robotics adjacent","CS Education Grants","$5,000-$50,000","Annual","https://www.bootup.org","https://www.bootup.org/","CS and coding education; underprivileged schools; robotics programming pipeline","GOOD"),
("Girls Who Code Foundation","National","Education Nonprofit","Girls Who Code funds CS education for girls grades 3-12; summer immersion and clubs","CS Education for Girls","$5,000-$100,000","Annual","https://www.girlswhocode.com","https://girlswhocode.com/about-us/mission-vision","CS education for girls; if TroyVEX has female cadets highlight for grants; New York HQ","GOOD"),
("Black Girls Code Foundation","National","Education Nonprofit","Black Girls Code funds technology education for Black girls ages 7-17; coding and STEM","Technology and STEM for Black Girls","$5,000-$100,000","Annual","https://www.blackgirlscode.com","https://www.blackgirlscode.com/","Technology STEM for underrepresented girls; if TroyVEX demographics align this is HIGH PRIORITY","GOOD"),
("All Star Code Foundation","National","Education Nonprofit","All Star Code funds CS education for young men of color; STEM career pipeline","CS STEM for Men of Color","$5,000-$50,000","Annual","https://www.allstarcode.org","https://www.allstarcode.org/","CS education for underrepresented men; JROTC demographics may align; New York HQ","MEDIUM"),
("FIRST Robotics Canada Model (cross-applicable)","National","Education Nonprofit","FIRST programs and grant models applicable to US VEX teams; FIRST Tech Challenge cross-pollination","FTC Grant Programs","$1,000-$25,000","Rolling/Annual","https://www.firstinspires.org","https://www.firstinspires.org/resource-library/fundraising-and-sponsorship","FIRST and VEX sponsor overlap; many FIRST sponsors fund VEX teams; APPLY THROUGH SHARED SPONSORS","GOOD"),
# Community foundations - major US cities
("Seattle Foundation","National","Community Foundation","Funds education and STEM in Seattle metro area; technology sector philanthropy hub","Education and STEM Grants","$10,000-$250,000","Annual","https://www.seattlefoundation.org","https://www.seattlefoundation.org/nonprofits/","Pacific Northwest tech hub; STEM education; Seattle WA - geographic limitation but model for CA","MEDIUM"),
("Greater Boston Community Foundation","National","Community Foundation","Funds education and community programs in Greater Boston; STEM and equity focus","Education and STEM Grants","$10,000-$250,000","Annual","https://www.grantmakers.io/profiles/v0/04-2105741/","https://www.tbf.org/","Boston area; geographic limitation; STEM education model; tech sector philanthropy hub","MEDIUM"),
("Philadelphia Foundation","National","Community Foundation","Funds education and community programs in Philadelphia metro area; STEM and equity","Education Grants","$10,000-$100,000","Annual","https://www.philafound.org","https://www.philafound.org/grants/","Philadelphia area; geographic limitation; education and STEM model","MEDIUM"),
("Denver Foundation","National","Community Foundation","Funds education and community programs in Denver metro; STEM and innovation focus","Education and Innovation Grants","$10,000-$100,000","Annual","https://www.denverfoundation.org","https://www.denverfoundation.org/grants/","Denver CO; geographic limitation; education and STEM; aerospace industry hub community","MEDIUM"),
("Oregon Community Foundation","National","Community Foundation","Funds STEM education and equity programs in Oregon; Pacific Northwest focus","STEM Education Grants","$10,000-$250,000","Annual","https://www.oregoncf.org","https://www.oregoncf.org/grants-and-scholarships","Oregon; geographic limitation; STEM education; Pacific Northwest tech community","MEDIUM"),
("Nevada Community Foundation","National","Community Foundation","Funds education and community programs in Nevada; tech and gaming industry philanthropy hub","Education and STEM Grants","$5,000-$100,000","Annual","https://www.nevadacf.org","https://www.nevadacf.org/nonprofits/grants/","Nevada community; geographic limitation for TroyVEX but Las Vegas tech scene philanthropy model","MEDIUM"),
("Arizona Community Foundation","National","Community Foundation","Funds K-12 education innovation in Arizona including STEM; statewide grants","Education Innovation Grants","$5,000-$100,000","Annual statewide cycle","https://www.azfoundation.org","https://www.azfoundation.org/grants/","AZ focus; geographic limitation; STEM education model for CA community foundation approaches","MEDIUM"),
("Community Foundation of Greater Atlanta","National","Community Foundation","Funds education and STEM in Greater Atlanta area; tech sector philanthropy hub","Education and STEM Grants","$10,000-$250,000","Annual","https://www.cfgreateratlanta.org","https://www.cfgreateratlanta.org/nonprofits/grants/","Atlanta area; geographic limitation; tech hub philanthropic model; STEM education","MEDIUM"),
("Triangle Community Foundation (NC)","National","Community Foundation","Funds education and STEM in Research Triangle area NC; pharmaceutical and tech hub","STEM and Education Grants","$10,000-$100,000","Annual","https://www.trianglecf.org","https://www.trianglecf.org/grants/","NC Research Triangle; geographic limitation; pharma and tech hub philanthropy","MEDIUM"),
("Communities Foundation of Texas","National","Community Foundation","Funds education and STEM broadly in Texas; large energy and tech sector philanthropy hub","Education and STEM Grants","$10,000-$250,000","Annual","https://www.cftexas.org","https://www.cftexas.org/for-nonprofits/contact/","Texas; geographic limitation; large foundation with national reach; STEM education funded","MEDIUM"),
("Greater Kansas City Community Foundation","National","Community Foundation","Funds K-12 education and STEM in Kansas City metro area; Midwest philanthropy hub","Education and STEM Grants","$5,000-$250,000","Rolling","https://www.growyourgiving.org","https://www.growyourgiving.org/contact/","Kansas City; geographic limitation; education and STEM pipeline","MEDIUM"),
("Pittsburgh Foundation","National","Community Foundation","Funds education and economic mobility in Allegheny County broadly; manufacturing and tech hub","Education Grants","$10,000-$100,000","Annual","https://www.pittsburghfoundation.org","https://www.pittsburghfoundation.org/contact-us","Pittsburgh manufacturing and robotics hub; geographic limitation; STEM and manufacturing education model","MEDIUM"),
("Greater Cincinnati Foundation","National","Community Foundation","Funds K-12 education with Learning Innovation Grants open now; STEM eligible","Learning Innovation Grants","Up to $5,000","Rolling - open now","https://www.gcfdn.org","https://www.gcfdn.org/grants/","Learning Innovation Grants open; STEM eligible; contact Adison Nelson anelson@gcfdn.org; APPLY NOW","GOOD"),
("Houston Endowment","National","Community Foundation","Funds K-12 education reform and STEM in Houston TX area; energy sector philanthropy hub","K-12 Education Grants","$25,000-$500,000","Annual","https://www.houstonendowment.org","https://www.houstonendowment.org/about-us/contact/","Energy sector philanthropy; Texas; geographic limitation for direct TroyVEX application","MEDIUM"),
("Cleveland Foundation","National","Community Foundation","Funds education and economic development in Greater Cleveland; manufacturing and aerospace philanthropy","Education and Economy Grants","$10,000-$250,000","Rolling","https://www.clevelandfoundation.org","https://www.clevelandfoundation.org/contact/","Cleveland manufacturing and aerospace hub; geographic limitation; education STEM model","MEDIUM"),
("Minneapolis Foundation","National","Community Foundation","Funds education equity in Twin Cities metro area; medical device and tech philanthropy","Education Equity Grants","$10,000-$250,000","Annual","https://www.minneapolisfoundation.org","https://www.minneapolisfoundation.org/grantseekers/","Medical device and tech hub; geographic limitation; education equity model","MEDIUM"),
("Community Foundation of Greater Memphis","National","Community Foundation","Funds education and community development in Memphis area; FedEx and AutoZone philanthropy hub","Education and Community Grants","$5,000-$100,000","Annual","https://www.cfgm.org","https://www.cfgm.org/nonprofits/grants/","Memphis; geographic limitation; logistics and automotive aftermarket philanthropy","MEDIUM"),
("St. Louis Community Foundation","National","Community Foundation","Funds education and STEM in St. Louis area; aerospace (Boeing St. Louis) philanthropy hub","Education and STEM Grants","$5,000-$100,000","Annual","https://www.stlgives.org","https://www.stlgives.org/nonprofits/grants/","St. Louis aerospace hub (Boeing facility); geographic limitation; STEM education model","MEDIUM"),
("Hawaii Community Foundation","National","Community Foundation","Funds education and STEM in Hawaii; military community philanthropy hub due to Pearl Harbor presence","STEM and Military Community Grants","$5,000-$100,000","Annual","https://www.hawaiicommunityfoundation.org","https://www.hawaiicommunityfoundation.org/for-nonprofits/apply","Hawaii; geographic limitation; military community philanthropy due to large military presence","MEDIUM"),
("Alaska Community Foundation","National","Community Foundation","Funds education and community in Alaska; military and energy philanthropy hub","Education Grants","$5,000-$50,000","Annual","https://www.alaskacf.org","https://www.alaskacf.org/grants/","Alaska; geographic limitation; military and oil industry philanthropy hub","MEDIUM"),
("Utah Community Foundation","National","Community Foundation","Funds education and STEM in Utah; tech sector (Silicon Slopes) philanthropy hub","STEM and Education Grants","$5,000-$100,000","Annual","https://www.utahcf.org","https://www.utahcf.org/grants","Utah Silicon Slopes tech hub; geographic limitation; STEM education model from tech philanthropy","MEDIUM"),
# Major national foundations not yet included
("Bezos Family Foundation","National","Major National Foundation","Funds early childhood and K-12 education; Vroom program for learning; invitation-based","Education Grants","Varies","Invitation only","https://www.bezosfamilyfoundation.org","https://www.bezosfamilyfoundation.org/contact/","Invitation only; early childhood and K-12 learning; Jeff Bezos family connection","BAD"),
("Schmidt Futures Foundation","National","Major National Foundation","Eric Schmidt (Google) funds STEM talent development; advanced research; not K-12 focused","STEM Talent Programs","Varies","Invitation only","https://www.schmidtsciences.org","https://schmidtfutures.org/contact/","Invitation only; advanced research not K-12; limited fit for high school team grants","BAD"),
("MacKenzie Scott Yield Giving","National","Major National Foundation","MacKenzie Scott funds education and social equity broadly; invitation-only unrestricted giving; massive grants","Unrestricted Education Grants",">$1,000,000","Invitation only","https://www.yieldgiving.com","https://www.yieldgiving.com/","Extremely invitation-based; massive unrestricted grants; not suitable for direct applications from HS teams","BAD"),
("Jack Dorsey Start Small Foundation","National","Major National Foundation","Jack Dorsey funds criminal justice and global health; limited education focus; invitation-only","Criminal Justice / Global Health",">$500,000","Invitation only","https://twitter.com/jack","https://twitter.com/jack","Very limited education fit; criminal justice and global health focus; not suitable for robotics team","BAD"),
("Open Philanthropy Project","National","Major National Foundation","Effective altruism-oriented giving; global health and biosecurity focus; invitation-only; not K-12 STEM","Global Health / Biosecurity",">$1,000,000","Invitation only","https://www.openphilanthropy.org","https://www.openphilanthropy.org/contact/","Effective altruism; global health focus; not suitable for high school robotics team grants","BAD"),
("Lumina Foundation","National","Regional Education Foundation","Funds post-secondary education access broadly; limited K-12 STEM direct; invitation-only","Higher Education Access",">$100,000","Invitation only","https://www.luminafoundation.org","https://www.luminafoundation.org/contact/","Higher education focus; K-12 limited; invitation-only; not suitable for HS robotics team","BAD"),
("Elon Musk Foundation","National","Individual Philanthropist","Elon Musk's foundation funds STEM science education and renewable energy; through Tesla and SpaceX adjacent","STEM Science Grants","$1,000-$100,000","Rolling","https://www.musksf.org","https://www.musksf.org/","Musk Foundation does fund some STEM projects; SpaceX connection; send compelling proposal","MEDIUM"),
("Reid Hoffman Foundation","National","Individual Philanthropist","LinkedIn co-founder funds education and technology; invitation-based but some open programs","Education and Technology Grants","$25,000-$250,000","Invitation-preferred","https://www.reidhoffman.org","https://www.reidhoffman.org/philanthropy/","Education and technology focus; invitation-preferred; LinkedIn connection relevant to STEM career pipeline","MEDIUM"),
("Ken Griffin Foundation","National","Individual Philanthropist","Citadel founder funds education and STEM broadly; major Chicago philanthropy; STEM competitions","STEM Education Grants","$25,000-$500,000","Invitation-based","https://www.kengriffinphilanthropy.com","https://www.kengriffinphilanthropy.com/","Major education philanthropy; STEM competitions supported; Chicago IL HQ","MEDIUM"),
("Paul Allen / Allen Institute","National","Individual Philanthropist","Paul Allen estate funds science and technology education; Allen Institute for AI and brain science","Science and Technology Education","$25,000-$500,000","Invitation-based","https://www.paulallen.com","https://www.vulcan.com/","Science and technology education; AI and brain science focus; Seattle WA - Pacific Northwest","MEDIUM"),
]

with open(OUT, 'a', newline='', encoding='utf-8-sig') as f:
    w = csv.writer(f)
    for e in ENTRIES:
        w.writerow(e)

print(f"Batch 7 complete: {len(ENTRIES)} new entries appended")
